'use client';
/**
 * Browser-side full video composition via a Web Worker.
 *
 * The FFmpeg encoding and media fetching run entirely in a dedicated worker
 * thread, keeping the main thread free for UI interactions. The worker loads
 * the single-thread FFmpeg core (no COOP/COEP needed) and posts progress
 * updates back.
 *
 * Generic capability: composes multiple "slide + narrator/voiceover" sections
 * into one complete video. course-studio is the first consumer; SKU/drama/podcast
 * can reuse the same function.
 */

export interface ComposeSection {
  slideUrl?: string; // slide image (16:9)
  videoUrl?: string; // narrator digital human video (with built-in voiceover track), if present uses left-right split layout
  audioUrl?: string; // voiceover audio when no narrator, slide fills the frame + this audio track
}

export interface ComposeProgress {
  frac: number; // 0-1
  note: string;
}

let worker: Worker | null = null;

function getWorker(): Worker {
  if (worker) return worker;
  worker = new Worker(new URL('./compose-worker.ts', import.meta.url), { type: 'module' });
  return worker;
}

/**
 * Compose a course: each section → slide|narrator left-right split (with voiceover audio) or slide+voiceover; then concat into the full video.
 * Outputs a 720p mp4 Blob (for download).
 * All FFmpeg work runs in a Web Worker to avoid blocking the main thread.
 */
export async function composeCourseVideo(
  sections: ComposeSection[],
  onProgress?: (p: ComposeProgress) => void,
): Promise<Blob> {
  const w = getWorker();
  return new Promise<Blob>((resolve, reject) => {
    const handler = (e: MessageEvent) => {
      const msg = e.data;
      if (msg.type === 'progress') {
        onProgress?.({ frac: msg.frac, note: msg.note });
      } else if (msg.type === 'done') {
        w.removeEventListener('message', handler);
        resolve(msg.blob as Blob);
      } else if (msg.type === 'error') {
        w.removeEventListener('message', handler);
        reject(new Error(msg.message));
      }
    };
    w.addEventListener('message', handler);
    w.postMessage({ type: 'compose', job: 'course', sections });
  });
}

/**
 * Vertical ad reel concatenation: multiple vertical video shots with built-in dialogue audio → each normalized to 1080x1920/30fps →
 * concat into one complete ad. Used by lazynext-studio's multi-shot voiceover ads (each shot generated by Veo i2v).
 * All FFmpeg work runs in a Web Worker to avoid blocking the main thread.
 */
export async function composeAdReel(
  videoUrls: string[],
  onProgress?: (p: ComposeProgress) => void,
): Promise<Blob> {
  const w = getWorker();
  return new Promise<Blob>((resolve, reject) => {
    const handler = (e: MessageEvent) => {
      const msg = e.data;
      if (msg.type === 'progress') {
        onProgress?.({ frac: msg.frac, note: msg.note });
      } else if (msg.type === 'done') {
        w.removeEventListener('message', handler);
        resolve(msg.blob as Blob);
      } else if (msg.type === 'error') {
        w.removeEventListener('message', handler);
        reject(new Error(msg.message));
      }
    };
    w.addEventListener('message', handler);
    w.postMessage({ type: 'compose', job: 'reel', videoUrls });
  });
}
