/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/it/*
 * Consolidates 16 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as assets__expiring from '@/lib/api-handlers/it/assets__expiring';
import * as assets__stats from '@/lib/api-handlers/it/assets__stats';
import * as contracts__expiring from '@/lib/api-handlers/it/contracts__expiring';
import * as contracts__stats from '@/lib/api-handlers/it/contracts__stats';
import * as assets from '@/lib/api-handlers/it/assets';
import * as contracts from '@/lib/api-handlers/it/contracts';
import * as procurement from '@/lib/api-handlers/it/procurement';
import * as assets___id__assign from '@/lib/api-handlers/it/assets___id__assign';
import * as assets___id__unassign from '@/lib/api-handlers/it/assets___id__unassign';
import * as procurement___id__approve from '@/lib/api-handlers/it/procurement___id__approve';
import * as procurement___id__ordered from '@/lib/api-handlers/it/procurement___id__ordered';
import * as procurement___id__received from '@/lib/api-handlers/it/procurement___id__received';
import * as procurement___id__reject from '@/lib/api-handlers/it/procurement___id__reject';
import * as assets___id from '@/lib/api-handlers/it/assets___id';
import * as contracts___id from '@/lib/api-handlers/it/contracts___id';
import * as procurement___id from '@/lib/api-handlers/it/procurement___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["assets","expiring"], paramNames: [], handlers: { GET: assets__expiring.GET } },
  { segments: ["assets","stats"], paramNames: [], handlers: { GET: assets__stats.GET } },
  { segments: ["contracts","expiring"], paramNames: [], handlers: { GET: contracts__expiring.GET } },
  { segments: ["contracts","stats"], paramNames: [], handlers: { GET: contracts__stats.GET } },
  { segments: ["assets"], paramNames: [], handlers: { GET: assets.GET, POST: assets.POST } },
  { segments: ["contracts"], paramNames: [], handlers: { GET: contracts.GET, POST: contracts.POST } },
  { segments: ["procurement"], paramNames: [], handlers: { GET: procurement.GET, POST: procurement.POST } },
  { segments: ["assets","[id]","assign"], paramNames: ["id"], handlers: { POST: assets___id__assign.POST } },
  { segments: ["assets","[id]","unassign"], paramNames: ["id"], handlers: { POST: assets___id__unassign.POST } },
  { segments: ["procurement","[id]","approve"], paramNames: ["id"], handlers: { POST: procurement___id__approve.POST } },
  { segments: ["procurement","[id]","ordered"], paramNames: ["id"], handlers: { POST: procurement___id__ordered.POST } },
  { segments: ["procurement","[id]","received"], paramNames: ["id"], handlers: { POST: procurement___id__received.POST } },
  { segments: ["procurement","[id]","reject"], paramNames: ["id"], handlers: { POST: procurement___id__reject.POST } },
  { segments: ["assets","[id]"], paramNames: ["id"], handlers: { GET: assets___id.GET, PATCH: assets___id.PATCH, DELETE: assets___id.DELETE } },
  { segments: ["contracts","[id]"], paramNames: ["id"], handlers: { GET: contracts___id.GET, PATCH: contracts___id.PATCH, DELETE: contracts___id.DELETE } },
  { segments: ["procurement","[id]"], paramNames: ["id"], handlers: { GET: procurement___id.GET, PATCH: procurement___id.PATCH, DELETE: procurement___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
