/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/legal/*
 * Consolidates 20 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as contracts__by_type from '@/lib/api-handlers/legal/contracts__by_type';
import * as contracts__expired from '@/lib/api-handlers/legal/contracts__expired';
import * as contracts__expiring from '@/lib/api-handlers/legal/contracts__expiring';
import * as contracts__stats from '@/lib/api-handlers/legal/contracts__stats';
import * as matters__open from '@/lib/api-handlers/legal/matters__open';
import * as matters__stats from '@/lib/api-handlers/legal/matters__stats';
import * as obligations__breached from '@/lib/api-handlers/legal/obligations__breached';
import * as obligations__overdue from '@/lib/api-handlers/legal/obligations__overdue';
import * as obligations__stats from '@/lib/api-handlers/legal/obligations__stats';
import * as obligations__upcoming from '@/lib/api-handlers/legal/obligations__upcoming';
import * as contracts from '@/lib/api-handlers/legal/contracts';
import * as matters from '@/lib/api-handlers/legal/matters';
import * as obligations from '@/lib/api-handlers/legal/obligations';
import * as contracts___id__status from '@/lib/api-handlers/legal/contracts___id__status';
import * as matters___id__assign from '@/lib/api-handlers/legal/matters___id__assign';
import * as matters___id__status from '@/lib/api-handlers/legal/matters___id__status';
import * as obligations___id__status from '@/lib/api-handlers/legal/obligations___id__status';
import * as contracts___id from '@/lib/api-handlers/legal/contracts___id';
import * as matters___id from '@/lib/api-handlers/legal/matters___id';
import * as obligations___id from '@/lib/api-handlers/legal/obligations___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["contracts","by-type"], paramNames: [], handlers: { GET: contracts__by_type.GET } },
  { segments: ["contracts","expired"], paramNames: [], handlers: { GET: contracts__expired.GET } },
  { segments: ["contracts","expiring"], paramNames: [], handlers: { GET: contracts__expiring.GET } },
  { segments: ["contracts","stats"], paramNames: [], handlers: { GET: contracts__stats.GET } },
  { segments: ["matters","open"], paramNames: [], handlers: { GET: matters__open.GET } },
  { segments: ["matters","stats"], paramNames: [], handlers: { GET: matters__stats.GET } },
  { segments: ["obligations","breached"], paramNames: [], handlers: { GET: obligations__breached.GET } },
  { segments: ["obligations","overdue"], paramNames: [], handlers: { GET: obligations__overdue.GET } },
  { segments: ["obligations","stats"], paramNames: [], handlers: { GET: obligations__stats.GET } },
  { segments: ["obligations","upcoming"], paramNames: [], handlers: { GET: obligations__upcoming.GET } },
  { segments: ["contracts"], paramNames: [], handlers: { GET: contracts.GET, POST: contracts.POST } },
  { segments: ["matters"], paramNames: [], handlers: { GET: matters.GET, POST: matters.POST } },
  { segments: ["obligations"], paramNames: [], handlers: { GET: obligations.GET, POST: obligations.POST } },
  { segments: ["contracts","[id]","status"], paramNames: ["id"], handlers: { POST: contracts___id__status.POST } },
  { segments: ["matters","[id]","assign"], paramNames: ["id"], handlers: { POST: matters___id__assign.POST } },
  { segments: ["matters","[id]","status"], paramNames: ["id"], handlers: { POST: matters___id__status.POST } },
  { segments: ["obligations","[id]","status"], paramNames: ["id"], handlers: { POST: obligations___id__status.POST } },
  { segments: ["contracts","[id]"], paramNames: ["id"], handlers: { GET: contracts___id.GET, PATCH: contracts___id.PATCH, DELETE: contracts___id.DELETE } },
  { segments: ["matters","[id]"], paramNames: ["id"], handlers: { GET: matters___id.GET, PATCH: matters___id.PATCH, DELETE: matters___id.DELETE } },
  { segments: ["obligations","[id]"], paramNames: ["id"], handlers: { GET: obligations___id.GET, PATCH: obligations___id.PATCH, DELETE: obligations___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
