/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/asset-lifecycle/*
 * Consolidates 16 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as depreciation__report from '@/lib/api-handlers/asset-lifecycle/depreciation__report';
import * as depreciation__summary from '@/lib/api-handlers/asset-lifecycle/depreciation__summary';
import * as disposals__stats from '@/lib/api-handlers/asset-lifecycle/disposals__stats';
import * as maintenance__overdue from '@/lib/api-handlers/asset-lifecycle/maintenance__overdue';
import * as maintenance__stats from '@/lib/api-handlers/asset-lifecycle/maintenance__stats';
import * as maintenance__upcoming from '@/lib/api-handlers/asset-lifecycle/maintenance__upcoming';
import * as warranties__expired from '@/lib/api-handlers/asset-lifecycle/warranties__expired';
import * as warranties__expiring from '@/lib/api-handlers/asset-lifecycle/warranties__expiring';
import * as warranties__stats from '@/lib/api-handlers/asset-lifecycle/warranties__stats';
import * as disposals from '@/lib/api-handlers/asset-lifecycle/disposals';
import * as maintenance from '@/lib/api-handlers/asset-lifecycle/maintenance';
import * as tags from '@/lib/api-handlers/asset-lifecycle/tags';
import * as warranties from '@/lib/api-handlers/asset-lifecycle/warranties';
import * as maintenance___id__complete from '@/lib/api-handlers/asset-lifecycle/maintenance___id__complete';
import * as maintenance___id from '@/lib/api-handlers/asset-lifecycle/maintenance___id';
import * as warranties___id from '@/lib/api-handlers/asset-lifecycle/warranties___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["depreciation","report"], paramNames: [], handlers: { GET: depreciation__report.GET } },
  { segments: ["depreciation","summary"], paramNames: [], handlers: { GET: depreciation__summary.GET } },
  { segments: ["disposals","stats"], paramNames: [], handlers: { GET: disposals__stats.GET } },
  { segments: ["maintenance","overdue"], paramNames: [], handlers: { GET: maintenance__overdue.GET } },
  { segments: ["maintenance","stats"], paramNames: [], handlers: { GET: maintenance__stats.GET } },
  { segments: ["maintenance","upcoming"], paramNames: [], handlers: { GET: maintenance__upcoming.GET } },
  { segments: ["warranties","expired"], paramNames: [], handlers: { GET: warranties__expired.GET } },
  { segments: ["warranties","expiring"], paramNames: [], handlers: { GET: warranties__expiring.GET } },
  { segments: ["warranties","stats"], paramNames: [], handlers: { GET: warranties__stats.GET } },
  { segments: ["disposals"], paramNames: [], handlers: { GET: disposals.GET, POST: disposals.POST } },
  { segments: ["maintenance"], paramNames: [], handlers: { GET: maintenance.GET, POST: maintenance.POST } },
  { segments: ["tags"], paramNames: [], handlers: { GET: tags.GET } },
  { segments: ["warranties"], paramNames: [], handlers: { GET: warranties.GET, POST: warranties.POST } },
  { segments: ["maintenance","[id]","complete"], paramNames: ["id"], handlers: { POST: maintenance___id__complete.POST } },
  { segments: ["maintenance","[id]"], paramNames: ["id"], handlers: { GET: maintenance___id.GET, PATCH: maintenance___id.PATCH, DELETE: maintenance___id.DELETE } },
  { segments: ["warranties","[id]"], paramNames: ["id"], handlers: { GET: warranties___id.GET, PATCH: warranties___id.PATCH, DELETE: warranties___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
