/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/capacity/*
 * Consolidates 12 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as utilization__team from '@/lib/api-handlers/capacity/utilization__team';
import * as workload__by_project from '@/lib/api-handlers/capacity/workload__by_project';
import * as workload__by_user from '@/lib/api-handlers/capacity/workload__by_user';
import * as allocations from '@/lib/api-handlers/capacity/allocations';
import * as bottlenecks from '@/lib/api-handlers/capacity/bottlenecks';
import * as forecast from '@/lib/api-handlers/capacity/forecast';
import * as overallocated from '@/lib/api-handlers/capacity/overallocated';
import * as stats from '@/lib/api-handlers/capacity/stats';
import * as underutilized from '@/lib/api-handlers/capacity/underutilized';
import * as allocations___id__status from '@/lib/api-handlers/capacity/allocations___id__status';
import * as utilization__user___userId from '@/lib/api-handlers/capacity/utilization__user___userId';
import * as allocations___id from '@/lib/api-handlers/capacity/allocations___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["utilization","team"], paramNames: [], handlers: { GET: utilization__team.GET } },
  { segments: ["workload","by-project"], paramNames: [], handlers: { GET: workload__by_project.GET } },
  { segments: ["workload","by-user"], paramNames: [], handlers: { GET: workload__by_user.GET } },
  { segments: ["allocations"], paramNames: [], handlers: { GET: allocations.GET, POST: allocations.POST } },
  { segments: ["bottlenecks"], paramNames: [], handlers: { GET: bottlenecks.GET } },
  { segments: ["forecast"], paramNames: [], handlers: { GET: forecast.GET } },
  { segments: ["overallocated"], paramNames: [], handlers: { GET: overallocated.GET } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["underutilized"], paramNames: [], handlers: { GET: underutilized.GET } },
  { segments: ["allocations","[id]","status"], paramNames: ["id"], handlers: { POST: allocations___id__status.POST } },
  { segments: ["utilization","user","[userId]"], paramNames: ["userId"], handlers: { GET: utilization__user___userId.GET } },
  { segments: ["allocations","[id]"], paramNames: ["id"], handlers: { GET: allocations___id.GET, PATCH: allocations___id.PATCH, DELETE: allocations___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
