/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/invoicing/*
 * Consolidates 22 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as ap__aging from '@/lib/api-handlers/invoicing/ap__aging';
import * as ap__payables from '@/lib/api-handlers/invoicing/ap__payables';
import * as ap__stats from '@/lib/api-handlers/invoicing/ap__stats';
import * as ap__upcoming from '@/lib/api-handlers/invoicing/ap__upcoming';
import * as ar__aging from '@/lib/api-handlers/invoicing/ar__aging';
import * as ar__dunning from '@/lib/api-handlers/invoicing/ar__dunning';
import * as ar__receivables from '@/lib/api-handlers/invoicing/ar__receivables';
import * as ar__stats from '@/lib/api-handlers/invoicing/ar__stats';
import * as invoices__by_status from '@/lib/api-handlers/invoicing/invoices__by_status';
import * as invoices__overdue from '@/lib/api-handlers/invoicing/invoices__overdue';
import * as invoices__revenue from '@/lib/api-handlers/invoicing/invoices__revenue';
import * as invoices__revenue_trend from '@/lib/api-handlers/invoicing/invoices__revenue_trend';
import * as invoices__stats from '@/lib/api-handlers/invoicing/invoices__stats';
import * as invoices from '@/lib/api-handlers/invoicing/invoices';
import * as stats from '@/lib/api-handlers/invoicing/stats';
import * as invoices___id__cancel from '@/lib/api-handlers/invoicing/invoices___id__cancel';
import * as invoices___id__line_items from '@/lib/api-handlers/invoicing/invoices___id__line_items';
import * as invoices___id__paid from '@/lib/api-handlers/invoicing/invoices___id__paid';
import * as invoices___id__send from '@/lib/api-handlers/invoicing/invoices___id__send';
import * as invoices___id__void from '@/lib/api-handlers/invoicing/invoices___id__void';
import * as invoices___id from '@/lib/api-handlers/invoicing/invoices___id';
import * as invoices___id__line_items___lineItemId from '@/lib/api-handlers/invoicing/invoices___id__line_items___lineItemId';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["ap","aging"], paramNames: [], handlers: { GET: ap__aging.GET } },
  { segments: ["ap","payables"], paramNames: [], handlers: { GET: ap__payables.GET } },
  { segments: ["ap","stats"], paramNames: [], handlers: { GET: ap__stats.GET } },
  { segments: ["ap","upcoming"], paramNames: [], handlers: { GET: ap__upcoming.GET } },
  { segments: ["ar","aging"], paramNames: [], handlers: { GET: ar__aging.GET } },
  { segments: ["ar","dunning"], paramNames: [], handlers: { GET: ar__dunning.GET } },
  { segments: ["ar","receivables"], paramNames: [], handlers: { GET: ar__receivables.GET } },
  { segments: ["ar","stats"], paramNames: [], handlers: { GET: ar__stats.GET } },
  { segments: ["invoices","by-status"], paramNames: [], handlers: { GET: invoices__by_status.GET } },
  { segments: ["invoices","overdue"], paramNames: [], handlers: { GET: invoices__overdue.GET } },
  { segments: ["invoices","revenue"], paramNames: [], handlers: { GET: invoices__revenue.GET } },
  { segments: ["invoices","revenue-trend"], paramNames: [], handlers: { GET: invoices__revenue_trend.GET } },
  { segments: ["invoices","stats"], paramNames: [], handlers: { GET: invoices__stats.GET } },
  { segments: ["invoices"], paramNames: [], handlers: { GET: invoices.GET, POST: invoices.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["invoices","[id]","cancel"], paramNames: ["id"], handlers: { POST: invoices___id__cancel.POST } },
  { segments: ["invoices","[id]","line-items"], paramNames: ["id"], handlers: { POST: invoices___id__line_items.POST } },
  { segments: ["invoices","[id]","paid"], paramNames: ["id"], handlers: { POST: invoices___id__paid.POST } },
  { segments: ["invoices","[id]","send"], paramNames: ["id"], handlers: { POST: invoices___id__send.POST } },
  { segments: ["invoices","[id]","void"], paramNames: ["id"], handlers: { POST: invoices___id__void.POST } },
  { segments: ["invoices","[id]"], paramNames: ["id"], handlers: { GET: invoices___id.GET, PATCH: invoices___id.PATCH, DELETE: invoices___id.DELETE } },
  { segments: ["invoices","[id]","line-items","[lineItemId]"], paramNames: ["id","lineItemId"], handlers: { DELETE: invoices___id__line_items___lineItemId.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
