/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/corporate-archives/*
 * Consolidates 28 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as access from '@/lib/api-handlers/corporate-archives/access';
import * as collections from '@/lib/api-handlers/corporate-archives/collections';
import * as digitization from '@/lib/api-handlers/corporate-archives/digitization';
import * as metrics from '@/lib/api-handlers/corporate-archives/metrics';
import * as records from '@/lib/api-handlers/corporate-archives/records';
import * as stats from '@/lib/api-handlers/corporate-archives/stats';
import * as access___id__approve from '@/lib/api-handlers/corporate-archives/access___id__approve';
import * as access___id__deny from '@/lib/api-handlers/corporate-archives/access___id__deny';
import * as access___id__expire from '@/lib/api-handlers/corporate-archives/access___id__expire';
import * as access___id__fulfill from '@/lib/api-handlers/corporate-archives/access___id__fulfill';
import * as access___id__revoke from '@/lib/api-handlers/corporate-archives/access___id__revoke';
import * as collections___id__close from '@/lib/api-handlers/corporate-archives/collections___id__close';
import * as collections___id__deprecate from '@/lib/api-handlers/corporate-archives/collections___id__deprecate';
import * as collections___id__process from '@/lib/api-handlers/corporate-archives/collections___id__process';
import * as collections___id__restrict from '@/lib/api-handlers/corporate-archives/collections___id__restrict';
import * as digitization___id__complete from '@/lib/api-handlers/corporate-archives/digitization___id__complete';
import * as digitization___id__fail from '@/lib/api-handlers/corporate-archives/digitization___id__fail';
import * as digitization___id__quality_check from '@/lib/api-handlers/corporate-archives/digitization___id__quality_check';
import * as digitization___id__re_digitize from '@/lib/api-handlers/corporate-archives/digitization___id__re_digitize';
import * as digitization___id__start from '@/lib/api-handlers/corporate-archives/digitization___id__start';
import * as records___id__archive from '@/lib/api-handlers/corporate-archives/records___id__archive';
import * as records___id__destroy from '@/lib/api-handlers/corporate-archives/records___id__destroy';
import * as records___id__restrict from '@/lib/api-handlers/corporate-archives/records___id__restrict';
import * as records___id__transfer from '@/lib/api-handlers/corporate-archives/records___id__transfer';
import * as access___id from '@/lib/api-handlers/corporate-archives/access___id';
import * as collections___id from '@/lib/api-handlers/corporate-archives/collections___id';
import * as digitization___id from '@/lib/api-handlers/corporate-archives/digitization___id';
import * as records___id from '@/lib/api-handlers/corporate-archives/records___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["access"], paramNames: [], handlers: { GET: access.GET, POST: access.POST } },
  { segments: ["collections"], paramNames: [], handlers: { GET: collections.GET, POST: collections.POST } },
  { segments: ["digitization"], paramNames: [], handlers: { GET: digitization.GET, POST: digitization.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["records"], paramNames: [], handlers: { GET: records.GET, POST: records.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["access","[id]","approve"], paramNames: ["id"], handlers: { POST: access___id__approve.POST } },
  { segments: ["access","[id]","deny"], paramNames: ["id"], handlers: { POST: access___id__deny.POST } },
  { segments: ["access","[id]","expire"], paramNames: ["id"], handlers: { POST: access___id__expire.POST } },
  { segments: ["access","[id]","fulfill"], paramNames: ["id"], handlers: { POST: access___id__fulfill.POST } },
  { segments: ["access","[id]","revoke"], paramNames: ["id"], handlers: { POST: access___id__revoke.POST } },
  { segments: ["collections","[id]","close"], paramNames: ["id"], handlers: { POST: collections___id__close.POST } },
  { segments: ["collections","[id]","deprecate"], paramNames: ["id"], handlers: { POST: collections___id__deprecate.POST } },
  { segments: ["collections","[id]","process"], paramNames: ["id"], handlers: { POST: collections___id__process.POST } },
  { segments: ["collections","[id]","restrict"], paramNames: ["id"], handlers: { POST: collections___id__restrict.POST } },
  { segments: ["digitization","[id]","complete"], paramNames: ["id"], handlers: { POST: digitization___id__complete.POST } },
  { segments: ["digitization","[id]","fail"], paramNames: ["id"], handlers: { POST: digitization___id__fail.POST } },
  { segments: ["digitization","[id]","quality-check"], paramNames: ["id"], handlers: { POST: digitization___id__quality_check.POST } },
  { segments: ["digitization","[id]","re-digitize"], paramNames: ["id"], handlers: { POST: digitization___id__re_digitize.POST } },
  { segments: ["digitization","[id]","start"], paramNames: ["id"], handlers: { POST: digitization___id__start.POST } },
  { segments: ["records","[id]","archive"], paramNames: ["id"], handlers: { POST: records___id__archive.POST } },
  { segments: ["records","[id]","destroy"], paramNames: ["id"], handlers: { POST: records___id__destroy.POST } },
  { segments: ["records","[id]","restrict"], paramNames: ["id"], handlers: { POST: records___id__restrict.POST } },
  { segments: ["records","[id]","transfer"], paramNames: ["id"], handlers: { POST: records___id__transfer.POST } },
  { segments: ["access","[id]"], paramNames: ["id"], handlers: { GET: access___id.GET, PATCH: access___id.PATCH, DELETE: access___id.DELETE } },
  { segments: ["collections","[id]"], paramNames: ["id"], handlers: { GET: collections___id.GET, PATCH: collections___id.PATCH, DELETE: collections___id.DELETE } },
  { segments: ["digitization","[id]"], paramNames: ["id"], handlers: { GET: digitization___id.GET, PATCH: digitization___id.PATCH, DELETE: digitization___id.DELETE } },
  { segments: ["records","[id]"], paramNames: ["id"], handlers: { GET: records___id.GET, PATCH: records___id.PATCH, DELETE: records___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
