/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/recruitment/*
 * Consolidates 20 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as candidates from '@/lib/api-handlers/recruitment/candidates';
import * as interviews from '@/lib/api-handlers/recruitment/interviews';
import * as jobs from '@/lib/api-handlers/recruitment/jobs';
import * as offers from '@/lib/api-handlers/recruitment/offers';
import * as pipeline from '@/lib/api-handlers/recruitment/pipeline';
import * as stats from '@/lib/api-handlers/recruitment/stats';
import * as candidates___id__rate from '@/lib/api-handlers/recruitment/candidates___id__rate';
import * as candidates___id__status from '@/lib/api-handlers/recruitment/candidates___id__status';
import * as interviews___id__cancel from '@/lib/api-handlers/recruitment/interviews___id__cancel';
import * as interviews___id__feedback from '@/lib/api-handlers/recruitment/interviews___id__feedback';
import * as jobs___id__close from '@/lib/api-handlers/recruitment/jobs___id__close';
import * as jobs___id__publish from '@/lib/api-handlers/recruitment/jobs___id__publish';
import * as offers___id__accept from '@/lib/api-handlers/recruitment/offers___id__accept';
import * as offers___id__reject from '@/lib/api-handlers/recruitment/offers___id__reject';
import * as offers___id__send from '@/lib/api-handlers/recruitment/offers___id__send';
import * as offers___id__withdraw from '@/lib/api-handlers/recruitment/offers___id__withdraw';
import * as candidates___id from '@/lib/api-handlers/recruitment/candidates___id';
import * as interviews___id from '@/lib/api-handlers/recruitment/interviews___id';
import * as jobs___id from '@/lib/api-handlers/recruitment/jobs___id';
import * as offers___id from '@/lib/api-handlers/recruitment/offers___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["candidates"], paramNames: [], handlers: { GET: candidates.GET, POST: candidates.POST } },
  { segments: ["interviews"], paramNames: [], handlers: { GET: interviews.GET, POST: interviews.POST } },
  { segments: ["jobs"], paramNames: [], handlers: { GET: jobs.GET, POST: jobs.POST } },
  { segments: ["offers"], paramNames: [], handlers: { GET: offers.GET, POST: offers.POST } },
  { segments: ["pipeline"], paramNames: [], handlers: { GET: pipeline.GET } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["candidates","[id]","rate"], paramNames: ["id"], handlers: { POST: candidates___id__rate.POST } },
  { segments: ["candidates","[id]","status"], paramNames: ["id"], handlers: { POST: candidates___id__status.POST } },
  { segments: ["interviews","[id]","cancel"], paramNames: ["id"], handlers: { POST: interviews___id__cancel.POST } },
  { segments: ["interviews","[id]","feedback"], paramNames: ["id"], handlers: { POST: interviews___id__feedback.POST } },
  { segments: ["jobs","[id]","close"], paramNames: ["id"], handlers: { POST: jobs___id__close.POST } },
  { segments: ["jobs","[id]","publish"], paramNames: ["id"], handlers: { POST: jobs___id__publish.POST } },
  { segments: ["offers","[id]","accept"], paramNames: ["id"], handlers: { POST: offers___id__accept.POST } },
  { segments: ["offers","[id]","reject"], paramNames: ["id"], handlers: { POST: offers___id__reject.POST } },
  { segments: ["offers","[id]","send"], paramNames: ["id"], handlers: { POST: offers___id__send.POST } },
  { segments: ["offers","[id]","withdraw"], paramNames: ["id"], handlers: { POST: offers___id__withdraw.POST } },
  { segments: ["candidates","[id]"], paramNames: ["id"], handlers: { GET: candidates___id.GET, PATCH: candidates___id.PATCH, DELETE: candidates___id.DELETE } },
  { segments: ["interviews","[id]"], paramNames: ["id"], handlers: { GET: interviews___id.GET, PATCH: interviews___id.PATCH, DELETE: interviews___id.DELETE } },
  { segments: ["jobs","[id]"], paramNames: ["id"], handlers: { GET: jobs___id.GET, PATCH: jobs___id.PATCH, DELETE: jobs___id.DELETE } },
  { segments: ["offers","[id]"], paramNames: ["id"], handlers: { GET: offers___id.GET, PATCH: offers___id.PATCH, DELETE: offers___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
