/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/product-lifecycle/*
 * Consolidates 20 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as eol from '@/lib/api-handlers/product-lifecycle/eol';
import * as metrics from '@/lib/api-handlers/product-lifecycle/metrics';
import * as phases from '@/lib/api-handlers/product-lifecycle/phases';
import * as products from '@/lib/api-handlers/product-lifecycle/products';
import * as stats from '@/lib/api-handlers/product-lifecycle/stats';
import * as versions from '@/lib/api-handlers/product-lifecycle/versions';
import * as eol___id__announce from '@/lib/api-handlers/product-lifecycle/eol___id__announce';
import * as eol___id__complete from '@/lib/api-handlers/product-lifecycle/eol___id__complete';
import * as eol___id__effect from '@/lib/api-handlers/product-lifecycle/eol___id__effect';
import * as phases___id__complete from '@/lib/api-handlers/product-lifecycle/phases___id__complete';
import * as phases___id__hold from '@/lib/api-handlers/product-lifecycle/phases___id__hold';
import * as phases___id__start from '@/lib/api-handlers/product-lifecycle/phases___id__start';
import * as products___id__launch from '@/lib/api-handlers/product-lifecycle/products___id__launch';
import * as products___id__retire from '@/lib/api-handlers/product-lifecycle/products___id__retire';
import * as versions___id__deprecate from '@/lib/api-handlers/product-lifecycle/versions___id__deprecate';
import * as versions___id__release from '@/lib/api-handlers/product-lifecycle/versions___id__release';
import * as eol___id from '@/lib/api-handlers/product-lifecycle/eol___id';
import * as phases___id from '@/lib/api-handlers/product-lifecycle/phases___id';
import * as products___id from '@/lib/api-handlers/product-lifecycle/products___id';
import * as versions___id from '@/lib/api-handlers/product-lifecycle/versions___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["eol"], paramNames: [], handlers: { GET: eol.GET, POST: eol.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["phases"], paramNames: [], handlers: { GET: phases.GET, POST: phases.POST } },
  { segments: ["products"], paramNames: [], handlers: { GET: products.GET, POST: products.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["versions"], paramNames: [], handlers: { GET: versions.GET, POST: versions.POST } },
  { segments: ["eol","[id]","announce"], paramNames: ["id"], handlers: { POST: eol___id__announce.POST } },
  { segments: ["eol","[id]","complete"], paramNames: ["id"], handlers: { POST: eol___id__complete.POST } },
  { segments: ["eol","[id]","effect"], paramNames: ["id"], handlers: { POST: eol___id__effect.POST } },
  { segments: ["phases","[id]","complete"], paramNames: ["id"], handlers: { POST: phases___id__complete.POST } },
  { segments: ["phases","[id]","hold"], paramNames: ["id"], handlers: { POST: phases___id__hold.POST } },
  { segments: ["phases","[id]","start"], paramNames: ["id"], handlers: { POST: phases___id__start.POST } },
  { segments: ["products","[id]","launch"], paramNames: ["id"], handlers: { POST: products___id__launch.POST } },
  { segments: ["products","[id]","retire"], paramNames: ["id"], handlers: { POST: products___id__retire.POST } },
  { segments: ["versions","[id]","deprecate"], paramNames: ["id"], handlers: { POST: versions___id__deprecate.POST } },
  { segments: ["versions","[id]","release"], paramNames: ["id"], handlers: { POST: versions___id__release.POST } },
  { segments: ["eol","[id]"], paramNames: ["id"], handlers: { GET: eol___id.GET, PATCH: eol___id.PATCH, DELETE: eol___id.DELETE } },
  { segments: ["phases","[id]"], paramNames: ["id"], handlers: { GET: phases___id.GET, PATCH: phases___id.PATCH, DELETE: phases___id.DELETE } },
  { segments: ["products","[id]"], paramNames: ["id"], handlers: { GET: products___id.GET, PATCH: products___id.PATCH, DELETE: products___id.DELETE } },
  { segments: ["versions","[id]"], paramNames: ["id"], handlers: { GET: versions___id.GET, PATCH: versions___id.PATCH, DELETE: versions___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
