/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/gift-management/*
 * Consolidates 19 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as inventory from '@/lib/api-handlers/gift-management/inventory';
import * as items from '@/lib/api-handlers/gift-management/items';
import * as metrics from '@/lib/api-handlers/gift-management/metrics';
import * as orders from '@/lib/api-handlers/gift-management/orders';
import * as recipients from '@/lib/api-handlers/gift-management/recipients';
import * as stats from '@/lib/api-handlers/gift-management/stats';
import * as inventory___id__overstock from '@/lib/api-handlers/gift-management/inventory___id__overstock';
import * as inventory___id__reserve from '@/lib/api-handlers/gift-management/inventory___id__reserve';
import * as orders___id__approve from '@/lib/api-handlers/gift-management/orders___id__approve';
import * as orders___id__cancel from '@/lib/api-handlers/gift-management/orders___id__cancel';
import * as orders___id__deliver from '@/lib/api-handlers/gift-management/orders___id__deliver';
import * as orders___id__place from '@/lib/api-handlers/gift-management/orders___id__place';
import * as orders___id__ship from '@/lib/api-handlers/gift-management/orders___id__ship';
import * as recipients___id__do_not_gift from '@/lib/api-handlers/gift-management/recipients___id__do_not_gift';
import * as recipients___id__vip from '@/lib/api-handlers/gift-management/recipients___id__vip';
import * as inventory___id from '@/lib/api-handlers/gift-management/inventory___id';
import * as items___id from '@/lib/api-handlers/gift-management/items___id';
import * as orders___id from '@/lib/api-handlers/gift-management/orders___id';
import * as recipients___id from '@/lib/api-handlers/gift-management/recipients___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["inventory"], paramNames: [], handlers: { GET: inventory.GET, POST: inventory.POST } },
  { segments: ["items"], paramNames: [], handlers: { GET: items.GET, POST: items.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["orders"], paramNames: [], handlers: { GET: orders.GET, POST: orders.POST } },
  { segments: ["recipients"], paramNames: [], handlers: { GET: recipients.GET, POST: recipients.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["inventory","[id]","overstock"], paramNames: ["id"], handlers: { POST: inventory___id__overstock.POST } },
  { segments: ["inventory","[id]","reserve"], paramNames: ["id"], handlers: { POST: inventory___id__reserve.POST } },
  { segments: ["orders","[id]","approve"], paramNames: ["id"], handlers: { POST: orders___id__approve.POST } },
  { segments: ["orders","[id]","cancel"], paramNames: ["id"], handlers: { POST: orders___id__cancel.POST } },
  { segments: ["orders","[id]","deliver"], paramNames: ["id"], handlers: { POST: orders___id__deliver.POST } },
  { segments: ["orders","[id]","place"], paramNames: ["id"], handlers: { POST: orders___id__place.POST } },
  { segments: ["orders","[id]","ship"], paramNames: ["id"], handlers: { POST: orders___id__ship.POST } },
  { segments: ["recipients","[id]","do-not-gift"], paramNames: ["id"], handlers: { POST: recipients___id__do_not_gift.POST } },
  { segments: ["recipients","[id]","vip"], paramNames: ["id"], handlers: { POST: recipients___id__vip.POST } },
  { segments: ["inventory","[id]"], paramNames: ["id"], handlers: { GET: inventory___id.GET, PATCH: inventory___id.PATCH, DELETE: inventory___id.DELETE } },
  { segments: ["items","[id]"], paramNames: ["id"], handlers: { GET: items___id.GET, PATCH: items___id.PATCH, DELETE: items___id.DELETE } },
  { segments: ["orders","[id]"], paramNames: ["id"], handlers: { GET: orders___id.GET, PATCH: orders___id.PATCH, DELETE: orders___id.DELETE } },
  { segments: ["recipients","[id]"], paramNames: ["id"], handlers: { GET: recipients___id.GET, PATCH: recipients___id.PATCH, DELETE: recipients___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
