/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/safety-incident/*
 * Consolidates 28 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as corrective_actions from '@/lib/api-handlers/safety-incident/corrective_actions';
import * as incidents from '@/lib/api-handlers/safety-incident/incidents';
import * as investigations from '@/lib/api-handlers/safety-incident/investigations';
import * as metrics from '@/lib/api-handlers/safety-incident/metrics';
import * as rcas from '@/lib/api-handlers/safety-incident/rcas';
import * as stats from '@/lib/api-handlers/safety-incident/stats';
import * as index from '@/lib/api-handlers/safety-incident/index';
import * as corrective_actions___id__cancel from '@/lib/api-handlers/safety-incident/corrective_actions___id__cancel';
import * as corrective_actions___id__complete from '@/lib/api-handlers/safety-incident/corrective_actions___id__complete';
import * as corrective_actions___id__overdue from '@/lib/api-handlers/safety-incident/corrective_actions___id__overdue';
import * as corrective_actions___id__start from '@/lib/api-handlers/safety-incident/corrective_actions___id__start';
import * as corrective_actions___id__verify from '@/lib/api-handlers/safety-incident/corrective_actions___id__verify';
import * as incidents___id__close from '@/lib/api-handlers/safety-incident/incidents___id__close';
import * as incidents___id__investigate from '@/lib/api-handlers/safety-incident/incidents___id__investigate';
import * as incidents___id__reopen from '@/lib/api-handlers/safety-incident/incidents___id__reopen';
import * as incidents___id__resolve from '@/lib/api-handlers/safety-incident/incidents___id__resolve';
import * as investigations___id__cancel from '@/lib/api-handlers/safety-incident/investigations___id__cancel';
import * as investigations___id__complete from '@/lib/api-handlers/safety-incident/investigations___id__complete';
import * as investigations___id__start from '@/lib/api-handlers/safety-incident/investigations___id__start';
import * as rcas___id__archive from '@/lib/api-handlers/safety-incident/rcas___id__archive';
import * as rcas___id__complete from '@/lib/api-handlers/safety-incident/rcas___id__complete';
import * as rcas___id__review from '@/lib/api-handlers/safety-incident/rcas___id__review';
import * as rcas___id__start from '@/lib/api-handlers/safety-incident/rcas___id__start';
import * as corrective_actions___id from '@/lib/api-handlers/safety-incident/corrective_actions___id';
import * as incidents___id from '@/lib/api-handlers/safety-incident/incidents___id';
import * as investigations___id from '@/lib/api-handlers/safety-incident/investigations___id';
import * as rcas___id from '@/lib/api-handlers/safety-incident/rcas___id';
import * as _id from '@/lib/api-handlers/safety-incident/_id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["corrective-actions"], paramNames: [], handlers: { GET: corrective_actions.GET, POST: corrective_actions.POST } },
  { segments: ["incidents"], paramNames: [], handlers: { GET: incidents.GET, POST: incidents.POST } },
  { segments: ["investigations"], paramNames: [], handlers: { GET: investigations.GET, POST: investigations.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["rcas"], paramNames: [], handlers: { GET: rcas.GET, POST: rcas.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: [], paramNames: [], handlers: { GET: index.GET, POST: index.POST } },
  { segments: ["corrective-actions","[id]","cancel"], paramNames: ["id"], handlers: { POST: corrective_actions___id__cancel.POST } },
  { segments: ["corrective-actions","[id]","complete"], paramNames: ["id"], handlers: { POST: corrective_actions___id__complete.POST } },
  { segments: ["corrective-actions","[id]","overdue"], paramNames: ["id"], handlers: { POST: corrective_actions___id__overdue.POST } },
  { segments: ["corrective-actions","[id]","start"], paramNames: ["id"], handlers: { POST: corrective_actions___id__start.POST } },
  { segments: ["corrective-actions","[id]","verify"], paramNames: ["id"], handlers: { POST: corrective_actions___id__verify.POST } },
  { segments: ["incidents","[id]","close"], paramNames: ["id"], handlers: { POST: incidents___id__close.POST } },
  { segments: ["incidents","[id]","investigate"], paramNames: ["id"], handlers: { POST: incidents___id__investigate.POST } },
  { segments: ["incidents","[id]","reopen"], paramNames: ["id"], handlers: { POST: incidents___id__reopen.POST } },
  { segments: ["incidents","[id]","resolve"], paramNames: ["id"], handlers: { POST: incidents___id__resolve.POST } },
  { segments: ["investigations","[id]","cancel"], paramNames: ["id"], handlers: { POST: investigations___id__cancel.POST } },
  { segments: ["investigations","[id]","complete"], paramNames: ["id"], handlers: { POST: investigations___id__complete.POST } },
  { segments: ["investigations","[id]","start"], paramNames: ["id"], handlers: { POST: investigations___id__start.POST } },
  { segments: ["rcas","[id]","archive"], paramNames: ["id"], handlers: { POST: rcas___id__archive.POST } },
  { segments: ["rcas","[id]","complete"], paramNames: ["id"], handlers: { POST: rcas___id__complete.POST } },
  { segments: ["rcas","[id]","review"], paramNames: ["id"], handlers: { POST: rcas___id__review.POST } },
  { segments: ["rcas","[id]","start"], paramNames: ["id"], handlers: { POST: rcas___id__start.POST } },
  { segments: ["corrective-actions","[id]"], paramNames: ["id"], handlers: { GET: corrective_actions___id.GET, PATCH: corrective_actions___id.PATCH, DELETE: corrective_actions___id.DELETE } },
  { segments: ["incidents","[id]"], paramNames: ["id"], handlers: { GET: incidents___id.GET, PATCH: incidents___id.PATCH, DELETE: incidents___id.DELETE } },
  { segments: ["investigations","[id]"], paramNames: ["id"], handlers: { GET: investigations___id.GET, PATCH: investigations___id.PATCH, DELETE: investigations___id.DELETE } },
  { segments: ["rcas","[id]"], paramNames: ["id"], handlers: { GET: rcas___id.GET, PATCH: rcas___id.PATCH, DELETE: rcas___id.DELETE } },
  { segments: ["[id]"], paramNames: ["id"], handlers: { GET: _id.GET, PATCH: _id.PATCH, DELETE: _id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
