/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/field-service/*
 * Consolidates 18 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as assignments from '@/lib/api-handlers/field-service/assignments';
import * as equipment from '@/lib/api-handlers/field-service/equipment';
import * as metrics from '@/lib/api-handlers/field-service/metrics';
import * as orders from '@/lib/api-handlers/field-service/orders';
import * as stats from '@/lib/api-handlers/field-service/stats';
import * as technicians from '@/lib/api-handlers/field-service/technicians';
import * as assignments___id__accept from '@/lib/api-handlers/field-service/assignments___id__accept';
import * as assignments___id__complete from '@/lib/api-handlers/field-service/assignments___id__complete';
import * as assignments___id__decline from '@/lib/api-handlers/field-service/assignments___id__decline';
import * as assignments___id__start from '@/lib/api-handlers/field-service/assignments___id__start';
import * as orders___id__assign from '@/lib/api-handlers/field-service/orders___id__assign';
import * as orders___id__complete from '@/lib/api-handlers/field-service/orders___id__complete';
import * as orders___id__schedule from '@/lib/api-handlers/field-service/orders___id__schedule';
import * as orders___id__start from '@/lib/api-handlers/field-service/orders___id__start';
import * as assignments___id from '@/lib/api-handlers/field-service/assignments___id';
import * as equipment___id from '@/lib/api-handlers/field-service/equipment___id';
import * as orders___id from '@/lib/api-handlers/field-service/orders___id';
import * as technicians___id from '@/lib/api-handlers/field-service/technicians___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["assignments"], paramNames: [], handlers: { GET: assignments.GET, POST: assignments.POST } },
  { segments: ["equipment"], paramNames: [], handlers: { GET: equipment.GET, POST: equipment.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["orders"], paramNames: [], handlers: { GET: orders.GET, POST: orders.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["technicians"], paramNames: [], handlers: { GET: technicians.GET, POST: technicians.POST } },
  { segments: ["assignments","[id]","accept"], paramNames: ["id"], handlers: { POST: assignments___id__accept.POST } },
  { segments: ["assignments","[id]","complete"], paramNames: ["id"], handlers: { POST: assignments___id__complete.POST } },
  { segments: ["assignments","[id]","decline"], paramNames: ["id"], handlers: { POST: assignments___id__decline.POST } },
  { segments: ["assignments","[id]","start"], paramNames: ["id"], handlers: { POST: assignments___id__start.POST } },
  { segments: ["orders","[id]","assign"], paramNames: ["id"], handlers: { POST: orders___id__assign.POST } },
  { segments: ["orders","[id]","complete"], paramNames: ["id"], handlers: { POST: orders___id__complete.POST } },
  { segments: ["orders","[id]","schedule"], paramNames: ["id"], handlers: { POST: orders___id__schedule.POST } },
  { segments: ["orders","[id]","start"], paramNames: ["id"], handlers: { POST: orders___id__start.POST } },
  { segments: ["assignments","[id]"], paramNames: ["id"], handlers: { GET: assignments___id.GET, PATCH: assignments___id.PATCH, DELETE: assignments___id.DELETE } },
  { segments: ["equipment","[id]"], paramNames: ["id"], handlers: { GET: equipment___id.GET, PATCH: equipment___id.PATCH, DELETE: equipment___id.DELETE } },
  { segments: ["orders","[id]"], paramNames: ["id"], handlers: { GET: orders___id.GET, PATCH: orders___id.PATCH, DELETE: orders___id.DELETE } },
  { segments: ["technicians","[id]"], paramNames: ["id"], handlers: { GET: technicians___id.GET, PATCH: technicians___id.PATCH, DELETE: technicians___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
