/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/v1/*
 * Consolidates 9 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as workspaces from '@/lib/api-handlers/v1/workspaces';
import * as index from '@/lib/api-handlers/v1/index';
import * as projects___id__tasks from '@/lib/api-handlers/v1/projects___id__tasks';
import * as workspaces___id__documents from '@/lib/api-handlers/v1/workspaces___id__documents';
import * as workspaces___id__projects from '@/lib/api-handlers/v1/workspaces___id__projects';
import * as documents___id from '@/lib/api-handlers/v1/documents___id';
import * as projects___id from '@/lib/api-handlers/v1/projects___id';
import * as tasks___id from '@/lib/api-handlers/v1/tasks___id';
import * as workspaces___id from '@/lib/api-handlers/v1/workspaces___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["workspaces"], paramNames: [], handlers: { GET: workspaces.GET } },
  { segments: [], paramNames: [], handlers: { GET: index.GET } },
  { segments: ["projects","[id]","tasks"], paramNames: ["id"], handlers: { GET: projects___id__tasks.GET, POST: projects___id__tasks.POST } },
  { segments: ["workspaces","[id]","documents"], paramNames: ["id"], handlers: { GET: workspaces___id__documents.GET, POST: workspaces___id__documents.POST } },
  { segments: ["workspaces","[id]","projects"], paramNames: ["id"], handlers: { GET: workspaces___id__projects.GET, POST: workspaces___id__projects.POST } },
  { segments: ["documents","[id]"], paramNames: ["id"], handlers: { GET: documents___id.GET, PATCH: documents___id.PATCH, DELETE: documents___id.DELETE } },
  { segments: ["projects","[id]"], paramNames: ["id"], handlers: { GET: projects___id.GET, PATCH: projects___id.PATCH, DELETE: projects___id.DELETE } },
  { segments: ["tasks","[id]"], paramNames: ["id"], handlers: { GET: tasks___id.GET, PATCH: tasks___id.PATCH, DELETE: tasks___id.DELETE } },
  { segments: ["workspaces","[id]"], paramNames: ["id"], handlers: { GET: workspaces___id.GET } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
