/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/onboarding/*
 * Consolidates 7 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as checklist from '@/lib/api-handlers/onboarding/checklist';
import * as complete_step from '@/lib/api-handlers/onboarding/complete_step';
import * as progress from '@/lib/api-handlers/onboarding/progress';
import * as reset from '@/lib/api-handlers/onboarding/reset';
import * as seed_sample from '@/lib/api-handlers/onboarding/seed_sample';
import * as state from '@/lib/api-handlers/onboarding/state';
import * as index from '@/lib/api-handlers/onboarding/index';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["checklist"], paramNames: [], handlers: { GET: checklist.GET } },
  { segments: ["complete-step"], paramNames: [], handlers: { POST: complete_step.POST } },
  { segments: ["progress"], paramNames: [], handlers: { GET: progress.GET } },
  { segments: ["reset"], paramNames: [], handlers: { POST: reset.POST } },
  { segments: ["seed-sample"], paramNames: [], handlers: { POST: seed_sample.POST } },
  { segments: ["state"], paramNames: [], handlers: { GET: state.GET } },
  { segments: [], paramNames: [], handlers: { POST: index.POST } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
