/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/health-safety/*
 * Consolidates 16 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as hazards from '@/lib/api-handlers/health-safety/hazards';
import * as incidents from '@/lib/api-handlers/health-safety/incidents';
import * as inspections from '@/lib/api-handlers/health-safety/inspections';
import * as metrics from '@/lib/api-handlers/health-safety/metrics';
import * as observations from '@/lib/api-handlers/health-safety/observations';
import * as stats from '@/lib/api-handlers/health-safety/stats';
import * as trainings from '@/lib/api-handlers/health-safety/trainings';
import * as hazards___id__mitigate from '@/lib/api-handlers/health-safety/hazards___id__mitigate';
import * as incidents___id__close from '@/lib/api-handlers/health-safety/incidents___id__close';
import * as incidents___id__investigate from '@/lib/api-handlers/health-safety/incidents___id__investigate';
import * as inspections___id__complete from '@/lib/api-handlers/health-safety/inspections___id__complete';
import * as hazards___id from '@/lib/api-handlers/health-safety/hazards___id';
import * as incidents___id from '@/lib/api-handlers/health-safety/incidents___id';
import * as inspections___id from '@/lib/api-handlers/health-safety/inspections___id';
import * as observations___id from '@/lib/api-handlers/health-safety/observations___id';
import * as trainings___id from '@/lib/api-handlers/health-safety/trainings___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["hazards"], paramNames: [], handlers: { GET: hazards.GET, POST: hazards.POST } },
  { segments: ["incidents"], paramNames: [], handlers: { GET: incidents.GET, POST: incidents.POST } },
  { segments: ["inspections"], paramNames: [], handlers: { GET: inspections.GET, POST: inspections.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["observations"], paramNames: [], handlers: { GET: observations.GET, POST: observations.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["trainings"], paramNames: [], handlers: { GET: trainings.GET, POST: trainings.POST } },
  { segments: ["hazards","[id]","mitigate"], paramNames: ["id"], handlers: { POST: hazards___id__mitigate.POST } },
  { segments: ["incidents","[id]","close"], paramNames: ["id"], handlers: { POST: incidents___id__close.POST } },
  { segments: ["incidents","[id]","investigate"], paramNames: ["id"], handlers: { POST: incidents___id__investigate.POST } },
  { segments: ["inspections","[id]","complete"], paramNames: ["id"], handlers: { POST: inspections___id__complete.POST } },
  { segments: ["hazards","[id]"], paramNames: ["id"], handlers: { GET: hazards___id.GET, PATCH: hazards___id.PATCH } },
  { segments: ["incidents","[id]"], paramNames: ["id"], handlers: { GET: incidents___id.GET, PATCH: incidents___id.PATCH } },
  { segments: ["inspections","[id]"], paramNames: ["id"], handlers: { GET: inspections___id.GET, PATCH: inspections___id.PATCH } },
  { segments: ["observations","[id]"], paramNames: ["id"], handlers: { GET: observations___id.GET, PATCH: observations___id.PATCH } },
  { segments: ["trainings","[id]"], paramNames: ["id"], handlers: { GET: trainings___id.GET, PATCH: trainings___id.PATCH, DELETE: trainings___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
