/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/ma/*
 * Consolidates 16 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as deals from '@/lib/api-handlers/ma/deals';
import * as due_diligence from '@/lib/api-handlers/ma/due_diligence';
import * as integrations from '@/lib/api-handlers/ma/integrations';
import * as metrics from '@/lib/api-handlers/ma/metrics';
import * as stats from '@/lib/api-handlers/ma/stats';
import * as targets from '@/lib/api-handlers/ma/targets';
import * as valuations from '@/lib/api-handlers/ma/valuations';
import * as deals___id__advance from '@/lib/api-handlers/ma/deals___id__advance';
import * as deals___id__terminate from '@/lib/api-handlers/ma/deals___id__terminate';
import * as due_diligence___id__complete from '@/lib/api-handlers/ma/due_diligence___id__complete';
import * as integrations___id__complete from '@/lib/api-handlers/ma/integrations___id__complete';
import * as deals___id from '@/lib/api-handlers/ma/deals___id';
import * as due_diligence___id from '@/lib/api-handlers/ma/due_diligence___id';
import * as integrations___id from '@/lib/api-handlers/ma/integrations___id';
import * as targets___id from '@/lib/api-handlers/ma/targets___id';
import * as valuations___id from '@/lib/api-handlers/ma/valuations___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["deals"], paramNames: [], handlers: { GET: deals.GET, POST: deals.POST } },
  { segments: ["due-diligence"], paramNames: [], handlers: { GET: due_diligence.GET, POST: due_diligence.POST } },
  { segments: ["integrations"], paramNames: [], handlers: { GET: integrations.GET, POST: integrations.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["targets"], paramNames: [], handlers: { GET: targets.GET, POST: targets.POST } },
  { segments: ["valuations"], paramNames: [], handlers: { GET: valuations.GET, POST: valuations.POST } },
  { segments: ["deals","[id]","advance"], paramNames: ["id"], handlers: { POST: deals___id__advance.POST } },
  { segments: ["deals","[id]","terminate"], paramNames: ["id"], handlers: { POST: deals___id__terminate.POST } },
  { segments: ["due-diligence","[id]","complete"], paramNames: ["id"], handlers: { POST: due_diligence___id__complete.POST } },
  { segments: ["integrations","[id]","complete"], paramNames: ["id"], handlers: { POST: integrations___id__complete.POST } },
  { segments: ["deals","[id]"], paramNames: ["id"], handlers: { GET: deals___id.GET, PATCH: deals___id.PATCH } },
  { segments: ["due-diligence","[id]"], paramNames: ["id"], handlers: { GET: due_diligence___id.GET, PATCH: due_diligence___id.PATCH } },
  { segments: ["integrations","[id]"], paramNames: ["id"], handlers: { GET: integrations___id.GET, PATCH: integrations___id.PATCH } },
  { segments: ["targets","[id]"], paramNames: ["id"], handlers: { GET: targets___id.GET, PATCH: targets___id.PATCH, DELETE: targets___id.DELETE } },
  { segments: ["valuations","[id]"], paramNames: ["id"], handlers: { GET: valuations___id.GET, PATCH: valuations___id.PATCH, DELETE: valuations___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path?: string[] }> },
) {
  const { path = [] } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
