/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/lease-management/*
 * Consolidates 19 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as contracts from '@/lib/api-handlers/lease-management/contracts';
import * as metrics from '@/lib/api-handlers/lease-management/metrics';
import * as payments from '@/lib/api-handlers/lease-management/payments';
import * as properties from '@/lib/api-handlers/lease-management/properties';
import * as stats from '@/lib/api-handlers/lease-management/stats';
import * as tenants from '@/lib/api-handlers/lease-management/tenants';
import * as contracts___id__activate from '@/lib/api-handlers/lease-management/contracts___id__activate';
import * as contracts___id__expire from '@/lib/api-handlers/lease-management/contracts___id__expire';
import * as contracts___id__renew from '@/lib/api-handlers/lease-management/contracts___id__renew';
import * as contracts___id__terminate from '@/lib/api-handlers/lease-management/contracts___id__terminate';
import * as payments___id__overdue from '@/lib/api-handlers/lease-management/payments___id__overdue';
import * as payments___id__paid from '@/lib/api-handlers/lease-management/payments___id__paid';
import * as payments___id__refund from '@/lib/api-handlers/lease-management/payments___id__refund';
import * as tenants___id__activate from '@/lib/api-handlers/lease-management/tenants___id__activate';
import * as tenants___id__deactivate from '@/lib/api-handlers/lease-management/tenants___id__deactivate';
import * as contracts___id from '@/lib/api-handlers/lease-management/contracts___id';
import * as payments___id from '@/lib/api-handlers/lease-management/payments___id';
import * as properties___id from '@/lib/api-handlers/lease-management/properties___id';
import * as tenants___id from '@/lib/api-handlers/lease-management/tenants___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["contracts"], paramNames: [], handlers: { GET: contracts.GET, POST: contracts.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["payments"], paramNames: [], handlers: { GET: payments.GET, POST: payments.POST } },
  { segments: ["properties"], paramNames: [], handlers: { GET: properties.GET, POST: properties.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["tenants"], paramNames: [], handlers: { GET: tenants.GET, POST: tenants.POST } },
  { segments: ["contracts","[id]","activate"], paramNames: ["id"], handlers: { POST: contracts___id__activate.POST } },
  { segments: ["contracts","[id]","expire"], paramNames: ["id"], handlers: { POST: contracts___id__expire.POST } },
  { segments: ["contracts","[id]","renew"], paramNames: ["id"], handlers: { POST: contracts___id__renew.POST } },
  { segments: ["contracts","[id]","terminate"], paramNames: ["id"], handlers: { POST: contracts___id__terminate.POST } },
  { segments: ["payments","[id]","overdue"], paramNames: ["id"], handlers: { POST: payments___id__overdue.POST } },
  { segments: ["payments","[id]","paid"], paramNames: ["id"], handlers: { POST: payments___id__paid.POST } },
  { segments: ["payments","[id]","refund"], paramNames: ["id"], handlers: { POST: payments___id__refund.POST } },
  { segments: ["tenants","[id]","activate"], paramNames: ["id"], handlers: { POST: tenants___id__activate.POST } },
  { segments: ["tenants","[id]","deactivate"], paramNames: ["id"], handlers: { POST: tenants___id__deactivate.POST } },
  { segments: ["contracts","[id]"], paramNames: ["id"], handlers: { GET: contracts___id.GET, PATCH: contracts___id.PATCH, DELETE: contracts___id.DELETE } },
  { segments: ["payments","[id]"], paramNames: ["id"], handlers: { GET: payments___id.GET, PATCH: payments___id.PATCH, DELETE: payments___id.DELETE } },
  { segments: ["properties","[id]"], paramNames: ["id"], handlers: { GET: properties___id.GET, PATCH: properties___id.PATCH, DELETE: properties___id.DELETE } },
  { segments: ["tenants","[id]"], paramNames: ["id"], handlers: { GET: tenants___id.GET, PATCH: tenants___id.PATCH, DELETE: tenants___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
