/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/knowledge-transfer/*
 * Consolidates 19 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as articles from '@/lib/api-handlers/knowledge-transfer/articles';
import * as mentorships from '@/lib/api-handlers/knowledge-transfer/mentorships';
import * as metrics from '@/lib/api-handlers/knowledge-transfer/metrics';
import * as plans from '@/lib/api-handlers/knowledge-transfer/plans';
import * as sessions from '@/lib/api-handlers/knowledge-transfer/sessions';
import * as stats from '@/lib/api-handlers/knowledge-transfer/stats';
import * as articles___id__archive from '@/lib/api-handlers/knowledge-transfer/articles___id__archive';
import * as articles___id__publish from '@/lib/api-handlers/knowledge-transfer/articles___id__publish';
import * as mentorships___id__complete from '@/lib/api-handlers/knowledge-transfer/mentorships___id__complete';
import * as mentorships___id__hold from '@/lib/api-handlers/knowledge-transfer/mentorships___id__hold';
import * as plans___id__activate from '@/lib/api-handlers/knowledge-transfer/plans___id__activate';
import * as plans___id__complete from '@/lib/api-handlers/knowledge-transfer/plans___id__complete';
import * as sessions___id__complete from '@/lib/api-handlers/knowledge-transfer/sessions___id__complete';
import * as sessions___id__postpone from '@/lib/api-handlers/knowledge-transfer/sessions___id__postpone';
import * as sessions___id__start from '@/lib/api-handlers/knowledge-transfer/sessions___id__start';
import * as articles___id from '@/lib/api-handlers/knowledge-transfer/articles___id';
import * as mentorships___id from '@/lib/api-handlers/knowledge-transfer/mentorships___id';
import * as plans___id from '@/lib/api-handlers/knowledge-transfer/plans___id';
import * as sessions___id from '@/lib/api-handlers/knowledge-transfer/sessions___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["articles"], paramNames: [], handlers: { GET: articles.GET, POST: articles.POST } },
  { segments: ["mentorships"], paramNames: [], handlers: { GET: mentorships.GET, POST: mentorships.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["plans"], paramNames: [], handlers: { GET: plans.GET, POST: plans.POST } },
  { segments: ["sessions"], paramNames: [], handlers: { GET: sessions.GET, POST: sessions.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["articles","[id]","archive"], paramNames: ["id"], handlers: { POST: articles___id__archive.POST } },
  { segments: ["articles","[id]","publish"], paramNames: ["id"], handlers: { POST: articles___id__publish.POST } },
  { segments: ["mentorships","[id]","complete"], paramNames: ["id"], handlers: { POST: mentorships___id__complete.POST } },
  { segments: ["mentorships","[id]","hold"], paramNames: ["id"], handlers: { POST: mentorships___id__hold.POST } },
  { segments: ["plans","[id]","activate"], paramNames: ["id"], handlers: { POST: plans___id__activate.POST } },
  { segments: ["plans","[id]","complete"], paramNames: ["id"], handlers: { POST: plans___id__complete.POST } },
  { segments: ["sessions","[id]","complete"], paramNames: ["id"], handlers: { POST: sessions___id__complete.POST } },
  { segments: ["sessions","[id]","postpone"], paramNames: ["id"], handlers: { POST: sessions___id__postpone.POST } },
  { segments: ["sessions","[id]","start"], paramNames: ["id"], handlers: { POST: sessions___id__start.POST } },
  { segments: ["articles","[id]"], paramNames: ["id"], handlers: { GET: articles___id.GET, PATCH: articles___id.PATCH, DELETE: articles___id.DELETE } },
  { segments: ["mentorships","[id]"], paramNames: ["id"], handlers: { GET: mentorships___id.GET, PATCH: mentorships___id.PATCH, DELETE: mentorships___id.DELETE } },
  { segments: ["plans","[id]"], paramNames: ["id"], handlers: { GET: plans___id.GET, PATCH: plans___id.PATCH, DELETE: plans___id.DELETE } },
  { segments: ["sessions","[id]"], paramNames: ["id"], handlers: { GET: sessions___id.GET, PATCH: sessions___id.PATCH, DELETE: sessions___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path?: string[] }> },
) {
  const { path = [] } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
