/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/sprints/*
 * Consolidates 10 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as active from '@/lib/api-handlers/sprints/active';
import * as stats from '@/lib/api-handlers/sprints/stats';
import * as upcoming from '@/lib/api-handlers/sprints/upcoming';
import * as velocity from '@/lib/api-handlers/sprints/velocity';
import * as index from '@/lib/api-handlers/sprints/index';
import * as _id__burndown from '@/lib/api-handlers/sprints/_id__burndown';
import * as _id__complete from '@/lib/api-handlers/sprints/_id__complete';
import * as _id__issues from '@/lib/api-handlers/sprints/_id__issues';
import * as _id__start from '@/lib/api-handlers/sprints/_id__start';
import * as _id from '@/lib/api-handlers/sprints/_id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["active"], paramNames: [], handlers: { GET: active.GET } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["upcoming"], paramNames: [], handlers: { GET: upcoming.GET } },
  { segments: ["velocity"], paramNames: [], handlers: { GET: velocity.GET } },
  { segments: [], paramNames: [], handlers: { GET: index.GET, POST: index.POST } },
  { segments: ["[id]","burndown"], paramNames: ["id"], handlers: { GET: _id__burndown.GET } },
  { segments: ["[id]","complete"], paramNames: ["id"], handlers: { POST: _id__complete.POST } },
  { segments: ["[id]","issues"], paramNames: ["id"], handlers: { GET: _id__issues.GET, POST: _id__issues.POST, DELETE: _id__issues.DELETE } },
  { segments: ["[id]","start"], paramNames: ["id"], handlers: { POST: _id__start.POST } },
  { segments: ["[id]"], paramNames: ["id"], handlers: { GET: _id.GET, PATCH: _id.PATCH, DELETE: _id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
