/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/grants/*
 * Consolidates 18 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as applications from '@/lib/api-handlers/grants/applications';
import * as awards from '@/lib/api-handlers/grants/awards';
import * as disbursements from '@/lib/api-handlers/grants/disbursements';
import * as metrics from '@/lib/api-handlers/grants/metrics';
import * as opportunities from '@/lib/api-handlers/grants/opportunities';
import * as reports from '@/lib/api-handlers/grants/reports';
import * as stats from '@/lib/api-handlers/grants/stats';
import * as applications___id__submit from '@/lib/api-handlers/grants/applications___id__submit';
import * as applications___id__withdraw from '@/lib/api-handlers/grants/applications___id__withdraw';
import * as awards___id__accept from '@/lib/api-handlers/grants/awards___id__accept';
import * as awards___id__close from '@/lib/api-handlers/grants/awards___id__close';
import * as disbursements___id__approve from '@/lib/api-handlers/grants/disbursements___id__approve';
import * as reports___id__submit from '@/lib/api-handlers/grants/reports___id__submit';
import * as applications___id from '@/lib/api-handlers/grants/applications___id';
import * as awards___id from '@/lib/api-handlers/grants/awards___id';
import * as disbursements___id from '@/lib/api-handlers/grants/disbursements___id';
import * as opportunities___id from '@/lib/api-handlers/grants/opportunities___id';
import * as reports___id from '@/lib/api-handlers/grants/reports___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["applications"], paramNames: [], handlers: { GET: applications.GET, POST: applications.POST } },
  { segments: ["awards"], paramNames: [], handlers: { GET: awards.GET, POST: awards.POST } },
  { segments: ["disbursements"], paramNames: [], handlers: { GET: disbursements.GET, POST: disbursements.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["opportunities"], paramNames: [], handlers: { GET: opportunities.GET, POST: opportunities.POST } },
  { segments: ["reports"], paramNames: [], handlers: { GET: reports.GET, POST: reports.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["applications","[id]","submit"], paramNames: ["id"], handlers: { POST: applications___id__submit.POST } },
  { segments: ["applications","[id]","withdraw"], paramNames: ["id"], handlers: { POST: applications___id__withdraw.POST } },
  { segments: ["awards","[id]","accept"], paramNames: ["id"], handlers: { POST: awards___id__accept.POST } },
  { segments: ["awards","[id]","close"], paramNames: ["id"], handlers: { POST: awards___id__close.POST } },
  { segments: ["disbursements","[id]","approve"], paramNames: ["id"], handlers: { POST: disbursements___id__approve.POST } },
  { segments: ["reports","[id]","submit"], paramNames: ["id"], handlers: { POST: reports___id__submit.POST } },
  { segments: ["applications","[id]"], paramNames: ["id"], handlers: { GET: applications___id.GET, PATCH: applications___id.PATCH } },
  { segments: ["awards","[id]"], paramNames: ["id"], handlers: { GET: awards___id.GET, PATCH: awards___id.PATCH } },
  { segments: ["disbursements","[id]"], paramNames: ["id"], handlers: { GET: disbursements___id.GET, PATCH: disbursements___id.PATCH } },
  { segments: ["opportunities","[id]"], paramNames: ["id"], handlers: { GET: opportunities___id.GET, PATCH: opportunities___id.PATCH, DELETE: opportunities___id.DELETE } },
  { segments: ["reports","[id]"], paramNames: ["id"], handlers: { GET: reports___id.GET, PATCH: reports___id.PATCH } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path?: string[] }> },
) {
  const { path = [] } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
