/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/quality-assurance/*
 * Consolidates 23 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as audits from '@/lib/api-handlers/quality-assurance/audits';
import * as capas from '@/lib/api-handlers/quality-assurance/capas';
import * as defects from '@/lib/api-handlers/quality-assurance/defects';
import * as inspections from '@/lib/api-handlers/quality-assurance/inspections';
import * as metrics from '@/lib/api-handlers/quality-assurance/metrics';
import * as stats from '@/lib/api-handlers/quality-assurance/stats';
import * as audits___id__complete from '@/lib/api-handlers/quality-assurance/audits___id__complete';
import * as audits___id__schedule from '@/lib/api-handlers/quality-assurance/audits___id__schedule';
import * as audits___id__start from '@/lib/api-handlers/quality-assurance/audits___id__start';
import * as capas___id__close from '@/lib/api-handlers/quality-assurance/capas___id__close';
import * as capas___id__implement from '@/lib/api-handlers/quality-assurance/capas___id__implement';
import * as capas___id__start from '@/lib/api-handlers/quality-assurance/capas___id__start';
import * as capas___id__verify from '@/lib/api-handlers/quality-assurance/capas___id__verify';
import * as defects___id__close from '@/lib/api-handlers/quality-assurance/defects___id__close';
import * as defects___id__investigate from '@/lib/api-handlers/quality-assurance/defects___id__investigate';
import * as defects___id__resolve from '@/lib/api-handlers/quality-assurance/defects___id__resolve';
import * as inspections___id__fail from '@/lib/api-handlers/quality-assurance/inspections___id__fail';
import * as inspections___id__pass from '@/lib/api-handlers/quality-assurance/inspections___id__pass';
import * as inspections___id__start from '@/lib/api-handlers/quality-assurance/inspections___id__start';
import * as audits___id from '@/lib/api-handlers/quality-assurance/audits___id';
import * as capas___id from '@/lib/api-handlers/quality-assurance/capas___id';
import * as defects___id from '@/lib/api-handlers/quality-assurance/defects___id';
import * as inspections___id from '@/lib/api-handlers/quality-assurance/inspections___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["audits"], paramNames: [], handlers: { GET: audits.GET, POST: audits.POST } },
  { segments: ["capas"], paramNames: [], handlers: { GET: capas.GET, POST: capas.POST } },
  { segments: ["defects"], paramNames: [], handlers: { GET: defects.GET, POST: defects.POST } },
  { segments: ["inspections"], paramNames: [], handlers: { GET: inspections.GET, POST: inspections.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["audits","[id]","complete"], paramNames: ["id"], handlers: { POST: audits___id__complete.POST } },
  { segments: ["audits","[id]","schedule"], paramNames: ["id"], handlers: { POST: audits___id__schedule.POST } },
  { segments: ["audits","[id]","start"], paramNames: ["id"], handlers: { POST: audits___id__start.POST } },
  { segments: ["capas","[id]","close"], paramNames: ["id"], handlers: { POST: capas___id__close.POST } },
  { segments: ["capas","[id]","implement"], paramNames: ["id"], handlers: { POST: capas___id__implement.POST } },
  { segments: ["capas","[id]","start"], paramNames: ["id"], handlers: { POST: capas___id__start.POST } },
  { segments: ["capas","[id]","verify"], paramNames: ["id"], handlers: { POST: capas___id__verify.POST } },
  { segments: ["defects","[id]","close"], paramNames: ["id"], handlers: { POST: defects___id__close.POST } },
  { segments: ["defects","[id]","investigate"], paramNames: ["id"], handlers: { POST: defects___id__investigate.POST } },
  { segments: ["defects","[id]","resolve"], paramNames: ["id"], handlers: { POST: defects___id__resolve.POST } },
  { segments: ["inspections","[id]","fail"], paramNames: ["id"], handlers: { POST: inspections___id__fail.POST } },
  { segments: ["inspections","[id]","pass"], paramNames: ["id"], handlers: { POST: inspections___id__pass.POST } },
  { segments: ["inspections","[id]","start"], paramNames: ["id"], handlers: { POST: inspections___id__start.POST } },
  { segments: ["audits","[id]"], paramNames: ["id"], handlers: { GET: audits___id.GET, PATCH: audits___id.PATCH, DELETE: audits___id.DELETE } },
  { segments: ["capas","[id]"], paramNames: ["id"], handlers: { GET: capas___id.GET, PATCH: capas___id.PATCH, DELETE: capas___id.DELETE } },
  { segments: ["defects","[id]"], paramNames: ["id"], handlers: { GET: defects___id.GET, PATCH: defects___id.PATCH, DELETE: defects___id.DELETE } },
  { segments: ["inspections","[id]"], paramNames: ["id"], handlers: { GET: inspections___id.GET, PATCH: inspections___id.PATCH, DELETE: inspections___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
