/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/treasury/*
 * Consolidates 12 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as bank_accounts from '@/lib/api-handlers/treasury/bank_accounts';
import * as cash_flow_summary from '@/lib/api-handlers/treasury/cash_flow_summary';
import * as cash_positions from '@/lib/api-handlers/treasury/cash_positions';
import * as forecasts from '@/lib/api-handlers/treasury/forecasts';
import * as liquidity from '@/lib/api-handlers/treasury/liquidity';
import * as payment_approvals from '@/lib/api-handlers/treasury/payment_approvals';
import * as stats from '@/lib/api-handlers/treasury/stats';
import * as payment_approvals___id__approve from '@/lib/api-handlers/treasury/payment_approvals___id__approve';
import * as payment_approvals___id__reject from '@/lib/api-handlers/treasury/payment_approvals___id__reject';
import * as bank_accounts___id from '@/lib/api-handlers/treasury/bank_accounts___id';
import * as forecasts___id from '@/lib/api-handlers/treasury/forecasts___id';
import * as payment_approvals___id from '@/lib/api-handlers/treasury/payment_approvals___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["bank-accounts"], paramNames: [], handlers: { GET: bank_accounts.GET, POST: bank_accounts.POST } },
  { segments: ["cash-flow-summary"], paramNames: [], handlers: { GET: cash_flow_summary.GET } },
  { segments: ["cash-positions"], paramNames: [], handlers: { GET: cash_positions.GET, POST: cash_positions.POST } },
  { segments: ["forecasts"], paramNames: [], handlers: { GET: forecasts.GET, POST: forecasts.POST } },
  { segments: ["liquidity"], paramNames: [], handlers: { GET: liquidity.GET } },
  { segments: ["payment-approvals"], paramNames: [], handlers: { GET: payment_approvals.GET, POST: payment_approvals.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["payment-approvals","[id]","approve"], paramNames: ["id"], handlers: { POST: payment_approvals___id__approve.POST } },
  { segments: ["payment-approvals","[id]","reject"], paramNames: ["id"], handlers: { POST: payment_approvals___id__reject.POST } },
  { segments: ["bank-accounts","[id]"], paramNames: ["id"], handlers: { GET: bank_accounts___id.GET, PATCH: bank_accounts___id.PATCH, DELETE: bank_accounts___id.DELETE } },
  { segments: ["forecasts","[id]"], paramNames: ["id"], handlers: { GET: forecasts___id.GET, DELETE: forecasts___id.DELETE } },
  { segments: ["payment-approvals","[id]"], paramNames: ["id"], handlers: { GET: payment_approvals___id.GET, PATCH: payment_approvals___id.PATCH } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
