/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/hr/*
 * Consolidates 25 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as payroll__generate from '@/lib/api-handlers/hr/payroll__generate';
import * as payroll__stats from '@/lib/api-handlers/hr/payroll__stats';
import * as payroll__summary from '@/lib/api-handlers/hr/payroll__summary';
import * as reviews__stats from '@/lib/api-handlers/hr/reviews__stats';
import * as time_off__balance from '@/lib/api-handlers/hr/time_off__balance';
import * as time_off__stats from '@/lib/api-handlers/hr/time_off__stats';
import * as departments from '@/lib/api-handlers/hr/departments';
import * as employees from '@/lib/api-handlers/hr/employees';
import * as org_chart from '@/lib/api-handlers/hr/org_chart';
import * as payroll from '@/lib/api-handlers/hr/payroll';
import * as reviews from '@/lib/api-handlers/hr/reviews';
import * as stats from '@/lib/api-handlers/hr/stats';
import * as time_off from '@/lib/api-handlers/hr/time_off';
import * as employees___id__reports from '@/lib/api-handlers/hr/employees___id__reports';
import * as payroll___id__paid from '@/lib/api-handlers/hr/payroll___id__paid';
import * as payroll___id__process from '@/lib/api-handlers/hr/payroll___id__process';
import * as reviews___id__complete from '@/lib/api-handlers/hr/reviews___id__complete';
import * as reviews___id__submit from '@/lib/api-handlers/hr/reviews___id__submit';
import * as time_off___id__approve from '@/lib/api-handlers/hr/time_off___id__approve';
import * as time_off___id__cancel from '@/lib/api-handlers/hr/time_off___id__cancel';
import * as time_off___id__deny from '@/lib/api-handlers/hr/time_off___id__deny';
import * as employees___id from '@/lib/api-handlers/hr/employees___id';
import * as payroll___id from '@/lib/api-handlers/hr/payroll___id';
import * as reviews___id from '@/lib/api-handlers/hr/reviews___id';
import * as time_off___id from '@/lib/api-handlers/hr/time_off___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["payroll","generate"], paramNames: [], handlers: { POST: payroll__generate.POST } },
  { segments: ["payroll","stats"], paramNames: [], handlers: { GET: payroll__stats.GET } },
  { segments: ["payroll","summary"], paramNames: [], handlers: { GET: payroll__summary.GET } },
  { segments: ["reviews","stats"], paramNames: [], handlers: { GET: reviews__stats.GET } },
  { segments: ["time-off","balance"], paramNames: [], handlers: { GET: time_off__balance.GET } },
  { segments: ["time-off","stats"], paramNames: [], handlers: { GET: time_off__stats.GET } },
  { segments: ["departments"], paramNames: [], handlers: { GET: departments.GET } },
  { segments: ["employees"], paramNames: [], handlers: { GET: employees.GET, POST: employees.POST } },
  { segments: ["org-chart"], paramNames: [], handlers: { GET: org_chart.GET } },
  { segments: ["payroll"], paramNames: [], handlers: { GET: payroll.GET, POST: payroll.POST } },
  { segments: ["reviews"], paramNames: [], handlers: { GET: reviews.GET, POST: reviews.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["time-off"], paramNames: [], handlers: { GET: time_off.GET, POST: time_off.POST } },
  { segments: ["employees","[id]","reports"], paramNames: ["id"], handlers: { GET: employees___id__reports.GET } },
  { segments: ["payroll","[id]","paid"], paramNames: ["id"], handlers: { POST: payroll___id__paid.POST } },
  { segments: ["payroll","[id]","process"], paramNames: ["id"], handlers: { POST: payroll___id__process.POST } },
  { segments: ["reviews","[id]","complete"], paramNames: ["id"], handlers: { POST: reviews___id__complete.POST } },
  { segments: ["reviews","[id]","submit"], paramNames: ["id"], handlers: { POST: reviews___id__submit.POST } },
  { segments: ["time-off","[id]","approve"], paramNames: ["id"], handlers: { POST: time_off___id__approve.POST } },
  { segments: ["time-off","[id]","cancel"], paramNames: ["id"], handlers: { POST: time_off___id__cancel.POST } },
  { segments: ["time-off","[id]","deny"], paramNames: ["id"], handlers: { POST: time_off___id__deny.POST } },
  { segments: ["employees","[id]"], paramNames: ["id"], handlers: { GET: employees___id.GET, PATCH: employees___id.PATCH, DELETE: employees___id.DELETE } },
  { segments: ["payroll","[id]"], paramNames: ["id"], handlers: { GET: payroll___id.GET, PATCH: payroll___id.PATCH, DELETE: payroll___id.DELETE } },
  { segments: ["reviews","[id]"], paramNames: ["id"], handlers: { GET: reviews___id.GET, PATCH: reviews___id.PATCH, DELETE: reviews___id.DELETE } },
  { segments: ["time-off","[id]"], paramNames: ["id"], handlers: { GET: time_off___id.GET, PATCH: time_off___id.PATCH } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
