/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/distribution/*
 * Consolidates 17 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as centers from '@/lib/api-handlers/distribution/centers';
import * as channels from '@/lib/api-handlers/distribution/channels';
import * as fulfillment from '@/lib/api-handlers/distribution/fulfillment';
import * as metrics from '@/lib/api-handlers/distribution/metrics';
import * as networks from '@/lib/api-handlers/distribution/networks';
import * as stats from '@/lib/api-handlers/distribution/stats';
import * as channels___id__activate from '@/lib/api-handlers/distribution/channels___id__activate';
import * as channels___id__pause from '@/lib/api-handlers/distribution/channels___id__pause';
import * as fulfillment___id__allocate from '@/lib/api-handlers/distribution/fulfillment___id__allocate';
import * as fulfillment___id__deliver from '@/lib/api-handlers/distribution/fulfillment___id__deliver';
import * as fulfillment___id__pack from '@/lib/api-handlers/distribution/fulfillment___id__pack';
import * as fulfillment___id__pick from '@/lib/api-handlers/distribution/fulfillment___id__pick';
import * as fulfillment___id__ship from '@/lib/api-handlers/distribution/fulfillment___id__ship';
import * as centers___id from '@/lib/api-handlers/distribution/centers___id';
import * as channels___id from '@/lib/api-handlers/distribution/channels___id';
import * as fulfillment___id from '@/lib/api-handlers/distribution/fulfillment___id';
import * as networks___id from '@/lib/api-handlers/distribution/networks___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["centers"], paramNames: [], handlers: { GET: centers.GET, POST: centers.POST } },
  { segments: ["channels"], paramNames: [], handlers: { GET: channels.GET, POST: channels.POST } },
  { segments: ["fulfillment"], paramNames: [], handlers: { GET: fulfillment.GET, POST: fulfillment.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["networks"], paramNames: [], handlers: { GET: networks.GET, POST: networks.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["channels","[id]","activate"], paramNames: ["id"], handlers: { POST: channels___id__activate.POST } },
  { segments: ["channels","[id]","pause"], paramNames: ["id"], handlers: { POST: channels___id__pause.POST } },
  { segments: ["fulfillment","[id]","allocate"], paramNames: ["id"], handlers: { POST: fulfillment___id__allocate.POST } },
  { segments: ["fulfillment","[id]","deliver"], paramNames: ["id"], handlers: { POST: fulfillment___id__deliver.POST } },
  { segments: ["fulfillment","[id]","pack"], paramNames: ["id"], handlers: { POST: fulfillment___id__pack.POST } },
  { segments: ["fulfillment","[id]","pick"], paramNames: ["id"], handlers: { POST: fulfillment___id__pick.POST } },
  { segments: ["fulfillment","[id]","ship"], paramNames: ["id"], handlers: { POST: fulfillment___id__ship.POST } },
  { segments: ["centers","[id]"], paramNames: ["id"], handlers: { GET: centers___id.GET, PATCH: centers___id.PATCH, DELETE: centers___id.DELETE } },
  { segments: ["channels","[id]"], paramNames: ["id"], handlers: { GET: channels___id.GET, PATCH: channels___id.PATCH, DELETE: channels___id.DELETE } },
  { segments: ["fulfillment","[id]"], paramNames: ["id"], handlers: { GET: fulfillment___id.GET, PATCH: fulfillment___id.PATCH, DELETE: fulfillment___id.DELETE } },
  { segments: ["networks","[id]"], paramNames: ["id"], handlers: { GET: networks___id.GET, PATCH: networks___id.PATCH, DELETE: networks___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path?: string[] }> },
) {
  const { path = [] } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
