/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/relocation/*
 * Consolidates 24 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as cases from '@/lib/api-handlers/relocation/cases';
import * as expenses from '@/lib/api-handlers/relocation/expenses';
import * as metrics from '@/lib/api-handlers/relocation/metrics';
import * as moves from '@/lib/api-handlers/relocation/moves';
import * as stats from '@/lib/api-handlers/relocation/stats';
import * as vendors from '@/lib/api-handlers/relocation/vendors';
import * as cases___id__complete from '@/lib/api-handlers/relocation/cases___id__complete';
import * as cases___id__hold from '@/lib/api-handlers/relocation/cases___id__hold';
import * as cases___id__plan from '@/lib/api-handlers/relocation/cases___id__plan';
import * as cases___id__start from '@/lib/api-handlers/relocation/cases___id__start';
import * as expenses___id__approve from '@/lib/api-handlers/relocation/expenses___id__approve';
import * as expenses___id__dispute from '@/lib/api-handlers/relocation/expenses___id__dispute';
import * as expenses___id__reimburse from '@/lib/api-handlers/relocation/expenses___id__reimburse';
import * as expenses___id__reject from '@/lib/api-handlers/relocation/expenses___id__reject';
import * as moves___id__delay from '@/lib/api-handlers/relocation/moves___id__delay';
import * as moves___id__deliver from '@/lib/api-handlers/relocation/moves___id__deliver';
import * as moves___id__dispatch from '@/lib/api-handlers/relocation/moves___id__dispatch';
import * as moves___id__reschedule from '@/lib/api-handlers/relocation/moves___id__reschedule';
import * as vendors___id__blacklist from '@/lib/api-handlers/relocation/vendors___id__blacklist';
import * as vendors___id__prefer from '@/lib/api-handlers/relocation/vendors___id__prefer';
import * as cases___id from '@/lib/api-handlers/relocation/cases___id';
import * as expenses___id from '@/lib/api-handlers/relocation/expenses___id';
import * as moves___id from '@/lib/api-handlers/relocation/moves___id';
import * as vendors___id from '@/lib/api-handlers/relocation/vendors___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["cases"], paramNames: [], handlers: { GET: cases.GET, POST: cases.POST } },
  { segments: ["expenses"], paramNames: [], handlers: { GET: expenses.GET, POST: expenses.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["moves"], paramNames: [], handlers: { GET: moves.GET, POST: moves.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["vendors"], paramNames: [], handlers: { GET: vendors.GET, POST: vendors.POST } },
  { segments: ["cases","[id]","complete"], paramNames: ["id"], handlers: { POST: cases___id__complete.POST } },
  { segments: ["cases","[id]","hold"], paramNames: ["id"], handlers: { POST: cases___id__hold.POST } },
  { segments: ["cases","[id]","plan"], paramNames: ["id"], handlers: { POST: cases___id__plan.POST } },
  { segments: ["cases","[id]","start"], paramNames: ["id"], handlers: { POST: cases___id__start.POST } },
  { segments: ["expenses","[id]","approve"], paramNames: ["id"], handlers: { POST: expenses___id__approve.POST } },
  { segments: ["expenses","[id]","dispute"], paramNames: ["id"], handlers: { POST: expenses___id__dispute.POST } },
  { segments: ["expenses","[id]","reimburse"], paramNames: ["id"], handlers: { POST: expenses___id__reimburse.POST } },
  { segments: ["expenses","[id]","reject"], paramNames: ["id"], handlers: { POST: expenses___id__reject.POST } },
  { segments: ["moves","[id]","delay"], paramNames: ["id"], handlers: { POST: moves___id__delay.POST } },
  { segments: ["moves","[id]","deliver"], paramNames: ["id"], handlers: { POST: moves___id__deliver.POST } },
  { segments: ["moves","[id]","dispatch"], paramNames: ["id"], handlers: { POST: moves___id__dispatch.POST } },
  { segments: ["moves","[id]","reschedule"], paramNames: ["id"], handlers: { POST: moves___id__reschedule.POST } },
  { segments: ["vendors","[id]","blacklist"], paramNames: ["id"], handlers: { POST: vendors___id__blacklist.POST } },
  { segments: ["vendors","[id]","prefer"], paramNames: ["id"], handlers: { POST: vendors___id__prefer.POST } },
  { segments: ["cases","[id]"], paramNames: ["id"], handlers: { GET: cases___id.GET, PATCH: cases___id.PATCH, DELETE: cases___id.DELETE } },
  { segments: ["expenses","[id]"], paramNames: ["id"], handlers: { GET: expenses___id.GET, PATCH: expenses___id.PATCH, DELETE: expenses___id.DELETE } },
  { segments: ["moves","[id]"], paramNames: ["id"], handlers: { GET: moves___id.GET, PATCH: moves___id.PATCH, DELETE: moves___id.DELETE } },
  { segments: ["vendors","[id]"], paramNames: ["id"], handlers: { GET: vendors___id.GET, PATCH: vendors___id.PATCH, DELETE: vendors___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
