/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/water-management/*
 * Consolidates 29 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as conservation from '@/lib/api-handlers/water-management/conservation';
import * as meters from '@/lib/api-handlers/water-management/meters';
import * as metrics from '@/lib/api-handlers/water-management/metrics';
import * as quality_tests from '@/lib/api-handlers/water-management/quality_tests';
import * as readings from '@/lib/api-handlers/water-management/readings';
import * as stats from '@/lib/api-handlers/water-management/stats';
import * as index from '@/lib/api-handlers/water-management/index';
import * as conservation___id__archive from '@/lib/api-handlers/water-management/conservation___id__archive';
import * as conservation___id__complete from '@/lib/api-handlers/water-management/conservation___id__complete';
import * as conservation___id__launch from '@/lib/api-handlers/water-management/conservation___id__launch';
import * as conservation___id__suspend from '@/lib/api-handlers/water-management/conservation___id__suspend';
import * as meters___id__activate from '@/lib/api-handlers/water-management/meters___id__activate';
import * as meters___id__calibrate from '@/lib/api-handlers/water-management/meters___id__calibrate';
import * as meters___id__decommission from '@/lib/api-handlers/water-management/meters___id__decommission';
import * as meters___id__maintain from '@/lib/api-handlers/water-management/meters___id__maintain';
import * as quality_tests___id__complete from '@/lib/api-handlers/water-management/quality_tests___id__complete';
import * as quality_tests___id__fail from '@/lib/api-handlers/water-management/quality_tests___id__fail';
import * as quality_tests___id__retest from '@/lib/api-handlers/water-management/quality_tests___id__retest';
import * as quality_tests___id__schedule from '@/lib/api-handlers/water-management/quality_tests___id__schedule';
import * as quality_tests___id__start from '@/lib/api-handlers/water-management/quality_tests___id__start';
import * as readings___id__archive from '@/lib/api-handlers/water-management/readings___id__archive';
import * as readings___id__flag from '@/lib/api-handlers/water-management/readings___id__flag';
import * as readings___id__submit from '@/lib/api-handlers/water-management/readings___id__submit';
import * as readings___id__verify from '@/lib/api-handlers/water-management/readings___id__verify';
import * as conservation___id from '@/lib/api-handlers/water-management/conservation___id';
import * as meters___id from '@/lib/api-handlers/water-management/meters___id';
import * as quality_tests___id from '@/lib/api-handlers/water-management/quality_tests___id';
import * as readings___id from '@/lib/api-handlers/water-management/readings___id';
import * as _id from '@/lib/api-handlers/water-management/_id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["conservation"], paramNames: [], handlers: { GET: conservation.GET, POST: conservation.POST } },
  { segments: ["meters"], paramNames: [], handlers: { GET: meters.GET, POST: meters.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["quality-tests"], paramNames: [], handlers: { GET: quality_tests.GET, POST: quality_tests.POST } },
  { segments: ["readings"], paramNames: [], handlers: { GET: readings.GET, POST: readings.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: [], paramNames: [], handlers: { GET: index.GET, POST: index.POST } },
  { segments: ["conservation","[id]","archive"], paramNames: ["id"], handlers: { POST: conservation___id__archive.POST } },
  { segments: ["conservation","[id]","complete"], paramNames: ["id"], handlers: { POST: conservation___id__complete.POST } },
  { segments: ["conservation","[id]","launch"], paramNames: ["id"], handlers: { POST: conservation___id__launch.POST } },
  { segments: ["conservation","[id]","suspend"], paramNames: ["id"], handlers: { POST: conservation___id__suspend.POST } },
  { segments: ["meters","[id]","activate"], paramNames: ["id"], handlers: { POST: meters___id__activate.POST } },
  { segments: ["meters","[id]","calibrate"], paramNames: ["id"], handlers: { POST: meters___id__calibrate.POST } },
  { segments: ["meters","[id]","decommission"], paramNames: ["id"], handlers: { POST: meters___id__decommission.POST } },
  { segments: ["meters","[id]","maintain"], paramNames: ["id"], handlers: { POST: meters___id__maintain.POST } },
  { segments: ["quality-tests","[id]","complete"], paramNames: ["id"], handlers: { POST: quality_tests___id__complete.POST } },
  { segments: ["quality-tests","[id]","fail"], paramNames: ["id"], handlers: { POST: quality_tests___id__fail.POST } },
  { segments: ["quality-tests","[id]","retest"], paramNames: ["id"], handlers: { POST: quality_tests___id__retest.POST } },
  { segments: ["quality-tests","[id]","schedule"], paramNames: ["id"], handlers: { POST: quality_tests___id__schedule.POST } },
  { segments: ["quality-tests","[id]","start"], paramNames: ["id"], handlers: { POST: quality_tests___id__start.POST } },
  { segments: ["readings","[id]","archive"], paramNames: ["id"], handlers: { POST: readings___id__archive.POST } },
  { segments: ["readings","[id]","flag"], paramNames: ["id"], handlers: { POST: readings___id__flag.POST } },
  { segments: ["readings","[id]","submit"], paramNames: ["id"], handlers: { POST: readings___id__submit.POST } },
  { segments: ["readings","[id]","verify"], paramNames: ["id"], handlers: { POST: readings___id__verify.POST } },
  { segments: ["conservation","[id]"], paramNames: ["id"], handlers: { GET: conservation___id.GET, PATCH: conservation___id.PATCH, DELETE: conservation___id.DELETE } },
  { segments: ["meters","[id]"], paramNames: ["id"], handlers: { GET: meters___id.GET, PATCH: meters___id.PATCH, DELETE: meters___id.DELETE } },
  { segments: ["quality-tests","[id]"], paramNames: ["id"], handlers: { GET: quality_tests___id.GET, PATCH: quality_tests___id.PATCH, DELETE: quality_tests___id.DELETE } },
  { segments: ["readings","[id]"], paramNames: ["id"], handlers: { GET: readings___id.GET, PATCH: readings___id.PATCH, DELETE: readings___id.DELETE } },
  { segments: ["[id]"], paramNames: ["id"], handlers: { GET: _id.GET, PATCH: _id.PATCH, DELETE: _id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
