/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/vendors/*
 * Consolidates 24 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as compliance__expiring from '@/lib/api-handlers/vendors/compliance__expiring';
import * as compliance__non_compliant from '@/lib/api-handlers/vendors/compliance__non_compliant';
import * as compliance__stats from '@/lib/api-handlers/vendors/compliance__stats';
import * as contracts__expiring from '@/lib/api-handlers/vendors/contracts__expiring';
import * as contracts__renewals from '@/lib/api-handlers/vendors/contracts__renewals';
import * as contracts__stats from '@/lib/api-handlers/vendors/contracts__stats';
import * as performance__stats from '@/lib/api-handlers/vendors/performance__stats';
import * as performance__top from '@/lib/api-handlers/vendors/performance__top';
import * as spend__by_category from '@/lib/api-handlers/vendors/spend__by_category';
import * as spend__by_vendor from '@/lib/api-handlers/vendors/spend__by_vendor';
import * as spend__stats from '@/lib/api-handlers/vendors/spend__stats';
import * as spend__trend from '@/lib/api-handlers/vendors/spend__trend';
import * as categories from '@/lib/api-handlers/vendors/categories';
import * as compliance from '@/lib/api-handlers/vendors/compliance';
import * as contracts from '@/lib/api-handlers/vendors/contracts';
import * as performance from '@/lib/api-handlers/vendors/performance';
import * as spend from '@/lib/api-handlers/vendors/spend';
import * as stats from '@/lib/api-handlers/vendors/stats';
import * as index from '@/lib/api-handlers/vendors/index';
import * as compliance___id from '@/lib/api-handlers/vendors/compliance___id';
import * as contracts___id from '@/lib/api-handlers/vendors/contracts___id';
import * as performance___id from '@/lib/api-handlers/vendors/performance___id';
import * as spend___id from '@/lib/api-handlers/vendors/spend___id';
import * as _id from '@/lib/api-handlers/vendors/_id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["compliance","expiring"], paramNames: [], handlers: { GET: compliance__expiring.GET } },
  { segments: ["compliance","non-compliant"], paramNames: [], handlers: { GET: compliance__non_compliant.GET } },
  { segments: ["compliance","stats"], paramNames: [], handlers: { GET: compliance__stats.GET } },
  { segments: ["contracts","expiring"], paramNames: [], handlers: { GET: contracts__expiring.GET } },
  { segments: ["contracts","renewals"], paramNames: [], handlers: { GET: contracts__renewals.GET } },
  { segments: ["contracts","stats"], paramNames: [], handlers: { GET: contracts__stats.GET } },
  { segments: ["performance","stats"], paramNames: [], handlers: { GET: performance__stats.GET } },
  { segments: ["performance","top"], paramNames: [], handlers: { GET: performance__top.GET } },
  { segments: ["spend","by-category"], paramNames: [], handlers: { GET: spend__by_category.GET } },
  { segments: ["spend","by-vendor"], paramNames: [], handlers: { GET: spend__by_vendor.GET } },
  { segments: ["spend","stats"], paramNames: [], handlers: { GET: spend__stats.GET } },
  { segments: ["spend","trend"], paramNames: [], handlers: { GET: spend__trend.GET } },
  { segments: ["categories"], paramNames: [], handlers: { GET: categories.GET } },
  { segments: ["compliance"], paramNames: [], handlers: { GET: compliance.GET, POST: compliance.POST } },
  { segments: ["contracts"], paramNames: [], handlers: { GET: contracts.GET, POST: contracts.POST } },
  { segments: ["performance"], paramNames: [], handlers: { GET: performance.GET, POST: performance.POST } },
  { segments: ["spend"], paramNames: [], handlers: { GET: spend.GET, POST: spend.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: [], paramNames: [], handlers: { GET: index.GET, POST: index.POST } },
  { segments: ["compliance","[id]"], paramNames: ["id"], handlers: { GET: compliance___id.GET, PATCH: compliance___id.PATCH, DELETE: compliance___id.DELETE } },
  { segments: ["contracts","[id]"], paramNames: ["id"], handlers: { GET: contracts___id.GET, PATCH: contracts___id.PATCH, DELETE: contracts___id.DELETE } },
  { segments: ["performance","[id]"], paramNames: ["id"], handlers: { GET: performance___id.GET } },
  { segments: ["spend","[id]"], paramNames: ["id"], handlers: { GET: spend___id.GET } },
  { segments: ["[id]"], paramNames: ["id"], handlers: { GET: _id.GET, PATCH: _id.PATCH, DELETE: _id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
