/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/board/*
 * Consolidates 17 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as board_packs from '@/lib/api-handlers/board/board_packs';
import * as committees from '@/lib/api-handlers/board/committees';
import * as meetings from '@/lib/api-handlers/board/meetings';
import * as members from '@/lib/api-handlers/board/members';
import * as metrics from '@/lib/api-handlers/board/metrics';
import * as resolutions from '@/lib/api-handlers/board/resolutions';
import * as stats from '@/lib/api-handlers/board/stats';
import * as board_packs___id__distribute from '@/lib/api-handlers/board/board_packs___id__distribute';
import * as meetings___id__cancel from '@/lib/api-handlers/board/meetings___id__cancel';
import * as meetings___id__minutes from '@/lib/api-handlers/board/meetings___id__minutes';
import * as resolutions___id__finalize from '@/lib/api-handlers/board/resolutions___id__finalize';
import * as resolutions___id__vote from '@/lib/api-handlers/board/resolutions___id__vote';
import * as board_packs___id from '@/lib/api-handlers/board/board_packs___id';
import * as committees___id from '@/lib/api-handlers/board/committees___id';
import * as meetings___id from '@/lib/api-handlers/board/meetings___id';
import * as members___id from '@/lib/api-handlers/board/members___id';
import * as resolutions___id from '@/lib/api-handlers/board/resolutions___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["board-packs"], paramNames: [], handlers: { GET: board_packs.GET, POST: board_packs.POST } },
  { segments: ["committees"], paramNames: [], handlers: { GET: committees.GET, POST: committees.POST } },
  { segments: ["meetings"], paramNames: [], handlers: { GET: meetings.GET, POST: meetings.POST } },
  { segments: ["members"], paramNames: [], handlers: { GET: members.GET, POST: members.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["resolutions"], paramNames: [], handlers: { GET: resolutions.GET, POST: resolutions.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["board-packs","[id]","distribute"], paramNames: ["id"], handlers: { POST: board_packs___id__distribute.POST } },
  { segments: ["meetings","[id]","cancel"], paramNames: ["id"], handlers: { POST: meetings___id__cancel.POST } },
  { segments: ["meetings","[id]","minutes"], paramNames: ["id"], handlers: { POST: meetings___id__minutes.POST } },
  { segments: ["resolutions","[id]","finalize"], paramNames: ["id"], handlers: { POST: resolutions___id__finalize.POST } },
  { segments: ["resolutions","[id]","vote"], paramNames: ["id"], handlers: { POST: resolutions___id__vote.POST } },
  { segments: ["board-packs","[id]"], paramNames: ["id"], handlers: { GET: board_packs___id.GET, PATCH: board_packs___id.PATCH } },
  { segments: ["committees","[id]"], paramNames: ["id"], handlers: { GET: committees___id.GET, PATCH: committees___id.PATCH, DELETE: committees___id.DELETE } },
  { segments: ["meetings","[id]"], paramNames: ["id"], handlers: { GET: meetings___id.GET, PATCH: meetings___id.PATCH } },
  { segments: ["members","[id]"], paramNames: ["id"], handlers: { GET: members___id.GET, PATCH: members___id.PATCH, DELETE: members___id.DELETE } },
  { segments: ["resolutions","[id]"], paramNames: ["id"], handlers: { GET: resolutions___id.GET, PATCH: resolutions___id.PATCH } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
