/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/waste-management/*
 * Consolidates 27 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as disposals from '@/lib/api-handlers/waste-management/disposals';
import * as metrics from '@/lib/api-handlers/waste-management/metrics';
import * as programs from '@/lib/api-handlers/waste-management/programs';
import * as stats from '@/lib/api-handlers/waste-management/stats';
import * as streams from '@/lib/api-handlers/waste-management/streams';
import * as vendors from '@/lib/api-handlers/waste-management/vendors';
import * as index from '@/lib/api-handlers/waste-management/index';
import * as disposals___id__cancel from '@/lib/api-handlers/waste-management/disposals___id__cancel';
import * as disposals___id__execute from '@/lib/api-handlers/waste-management/disposals___id__execute';
import * as disposals___id__schedule from '@/lib/api-handlers/waste-management/disposals___id__schedule';
import * as disposals___id__verify from '@/lib/api-handlers/waste-management/disposals___id__verify';
import * as programs___id__archive from '@/lib/api-handlers/waste-management/programs___id__archive';
import * as programs___id__complete from '@/lib/api-handlers/waste-management/programs___id__complete';
import * as programs___id__launch from '@/lib/api-handlers/waste-management/programs___id__launch';
import * as programs___id__suspend from '@/lib/api-handlers/waste-management/programs___id__suspend';
import * as streams___id__activate from '@/lib/api-handlers/waste-management/streams___id__activate';
import * as streams___id__deactivate from '@/lib/api-handlers/waste-management/streams___id__deactivate';
import * as streams___id__suspend from '@/lib/api-handlers/waste-management/streams___id__suspend';
import * as vendors___id__activate from '@/lib/api-handlers/waste-management/vendors___id__activate';
import * as vendors___id__review from '@/lib/api-handlers/waste-management/vendors___id__review';
import * as vendors___id__suspend from '@/lib/api-handlers/waste-management/vendors___id__suspend';
import * as vendors___id__terminate from '@/lib/api-handlers/waste-management/vendors___id__terminate';
import * as disposals___id from '@/lib/api-handlers/waste-management/disposals___id';
import * as programs___id from '@/lib/api-handlers/waste-management/programs___id';
import * as streams___id from '@/lib/api-handlers/waste-management/streams___id';
import * as vendors___id from '@/lib/api-handlers/waste-management/vendors___id';
import * as _id from '@/lib/api-handlers/waste-management/_id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["disposals"], paramNames: [], handlers: { GET: disposals.GET, POST: disposals.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["programs"], paramNames: [], handlers: { GET: programs.GET, POST: programs.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["streams"], paramNames: [], handlers: { GET: streams.GET, POST: streams.POST } },
  { segments: ["vendors"], paramNames: [], handlers: { GET: vendors.GET, POST: vendors.POST } },
  { segments: [], paramNames: [], handlers: { GET: index.GET, POST: index.POST } },
  { segments: ["disposals","[id]","cancel"], paramNames: ["id"], handlers: { POST: disposals___id__cancel.POST } },
  { segments: ["disposals","[id]","execute"], paramNames: ["id"], handlers: { POST: disposals___id__execute.POST } },
  { segments: ["disposals","[id]","schedule"], paramNames: ["id"], handlers: { POST: disposals___id__schedule.POST } },
  { segments: ["disposals","[id]","verify"], paramNames: ["id"], handlers: { POST: disposals___id__verify.POST } },
  { segments: ["programs","[id]","archive"], paramNames: ["id"], handlers: { POST: programs___id__archive.POST } },
  { segments: ["programs","[id]","complete"], paramNames: ["id"], handlers: { POST: programs___id__complete.POST } },
  { segments: ["programs","[id]","launch"], paramNames: ["id"], handlers: { POST: programs___id__launch.POST } },
  { segments: ["programs","[id]","suspend"], paramNames: ["id"], handlers: { POST: programs___id__suspend.POST } },
  { segments: ["streams","[id]","activate"], paramNames: ["id"], handlers: { POST: streams___id__activate.POST } },
  { segments: ["streams","[id]","deactivate"], paramNames: ["id"], handlers: { POST: streams___id__deactivate.POST } },
  { segments: ["streams","[id]","suspend"], paramNames: ["id"], handlers: { POST: streams___id__suspend.POST } },
  { segments: ["vendors","[id]","activate"], paramNames: ["id"], handlers: { POST: vendors___id__activate.POST } },
  { segments: ["vendors","[id]","review"], paramNames: ["id"], handlers: { POST: vendors___id__review.POST } },
  { segments: ["vendors","[id]","suspend"], paramNames: ["id"], handlers: { POST: vendors___id__suspend.POST } },
  { segments: ["vendors","[id]","terminate"], paramNames: ["id"], handlers: { POST: vendors___id__terminate.POST } },
  { segments: ["disposals","[id]"], paramNames: ["id"], handlers: { GET: disposals___id.GET, PATCH: disposals___id.PATCH, DELETE: disposals___id.DELETE } },
  { segments: ["programs","[id]"], paramNames: ["id"], handlers: { GET: programs___id.GET, PATCH: programs___id.PATCH, DELETE: programs___id.DELETE } },
  { segments: ["streams","[id]"], paramNames: ["id"], handlers: { GET: streams___id.GET, PATCH: streams___id.PATCH, DELETE: streams___id.DELETE } },
  { segments: ["vendors","[id]"], paramNames: ["id"], handlers: { GET: vendors___id.GET, PATCH: vendors___id.PATCH, DELETE: vendors___id.DELETE } },
  { segments: ["[id]"], paramNames: ["id"], handlers: { GET: _id.GET, PATCH: _id.PATCH, DELETE: _id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
