/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/automations/*
 * Consolidates 8 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as dispatch from '@/lib/api-handlers/automations/dispatch';
import * as dispatch_stats from '@/lib/api-handlers/automations/dispatch_stats';
import * as failed from '@/lib/api-handlers/automations/failed';
import * as recent_dispatches from '@/lib/api-handlers/automations/recent_dispatches';
import * as stats from '@/lib/api-handlers/automations/stats';
import * as index from '@/lib/api-handlers/automations/index';
import * as _id__runs from '@/lib/api-handlers/automations/_id__runs';
import * as _id from '@/lib/api-handlers/automations/_id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["dispatch"], paramNames: [], handlers: { POST: dispatch.POST } },
  { segments: ["dispatch-stats"], paramNames: [], handlers: { GET: dispatch_stats.GET } },
  { segments: ["failed"], paramNames: [], handlers: { GET: failed.GET } },
  { segments: ["recent-dispatches"], paramNames: [], handlers: { GET: recent_dispatches.GET } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: [], paramNames: [], handlers: { GET: index.GET, POST: index.POST } },
  { segments: ["[id]","runs"], paramNames: ["id"], handlers: { GET: _id__runs.GET } },
  { segments: ["[id]"], paramNames: ["id"], handlers: { GET: _id.GET, PATCH: _id.PATCH, DELETE: _id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
