/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/plan-management/*
 * Consolidates 29 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as claims from '@/lib/api-handlers/plan-management/claims';
import * as enrollments from '@/lib/api-handlers/plan-management/enrollments';
import * as metrics from '@/lib/api-handlers/plan-management/metrics';
import * as plans from '@/lib/api-handlers/plan-management/plans';
import * as providers from '@/lib/api-handlers/plan-management/providers';
import * as stats from '@/lib/api-handlers/plan-management/stats';
import * as claims___id__appeal from '@/lib/api-handlers/plan-management/claims___id__appeal';
import * as claims___id__approve from '@/lib/api-handlers/plan-management/claims___id__approve';
import * as claims___id__deny from '@/lib/api-handlers/plan-management/claims___id__deny';
import * as claims___id__partially_pay from '@/lib/api-handlers/plan-management/claims___id__partially_pay';
import * as claims___id__pay from '@/lib/api-handlers/plan-management/claims___id__pay';
import * as claims___id__review from '@/lib/api-handlers/plan-management/claims___id__review';
import * as enrollments___id__activate from '@/lib/api-handlers/plan-management/enrollments___id__activate';
import * as enrollments___id__suspend from '@/lib/api-handlers/plan-management/enrollments___id__suspend';
import * as enrollments___id__terminate from '@/lib/api-handlers/plan-management/enrollments___id__terminate';
import * as enrollments___id__waive from '@/lib/api-handlers/plan-management/enrollments___id__waive';
import * as plans___id__activate from '@/lib/api-handlers/plan-management/plans___id__activate';
import * as plans___id__close_enrollment from '@/lib/api-handlers/plan-management/plans___id__close_enrollment';
import * as plans___id__open_enrollment from '@/lib/api-handlers/plan-management/plans___id__open_enrollment';
import * as plans___id__renew from '@/lib/api-handlers/plan-management/plans___id__renew';
import * as plans___id__suspend from '@/lib/api-handlers/plan-management/plans___id__suspend';
import * as plans___id__terminate from '@/lib/api-handlers/plan-management/plans___id__terminate';
import * as providers___id__prefer from '@/lib/api-handlers/plan-management/providers___id__prefer';
import * as providers___id__review from '@/lib/api-handlers/plan-management/providers___id__review';
import * as providers___id__terminate from '@/lib/api-handlers/plan-management/providers___id__terminate';
import * as claims___id from '@/lib/api-handlers/plan-management/claims___id';
import * as enrollments___id from '@/lib/api-handlers/plan-management/enrollments___id';
import * as plans___id from '@/lib/api-handlers/plan-management/plans___id';
import * as providers___id from '@/lib/api-handlers/plan-management/providers___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["claims"], paramNames: [], handlers: { GET: claims.GET, POST: claims.POST } },
  { segments: ["enrollments"], paramNames: [], handlers: { GET: enrollments.GET, POST: enrollments.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["plans"], paramNames: [], handlers: { GET: plans.GET, POST: plans.POST } },
  { segments: ["providers"], paramNames: [], handlers: { GET: providers.GET, POST: providers.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["claims","[id]","appeal"], paramNames: ["id"], handlers: { POST: claims___id__appeal.POST } },
  { segments: ["claims","[id]","approve"], paramNames: ["id"], handlers: { POST: claims___id__approve.POST } },
  { segments: ["claims","[id]","deny"], paramNames: ["id"], handlers: { POST: claims___id__deny.POST } },
  { segments: ["claims","[id]","partially-pay"], paramNames: ["id"], handlers: { POST: claims___id__partially_pay.POST } },
  { segments: ["claims","[id]","pay"], paramNames: ["id"], handlers: { POST: claims___id__pay.POST } },
  { segments: ["claims","[id]","review"], paramNames: ["id"], handlers: { POST: claims___id__review.POST } },
  { segments: ["enrollments","[id]","activate"], paramNames: ["id"], handlers: { POST: enrollments___id__activate.POST } },
  { segments: ["enrollments","[id]","suspend"], paramNames: ["id"], handlers: { POST: enrollments___id__suspend.POST } },
  { segments: ["enrollments","[id]","terminate"], paramNames: ["id"], handlers: { POST: enrollments___id__terminate.POST } },
  { segments: ["enrollments","[id]","waive"], paramNames: ["id"], handlers: { POST: enrollments___id__waive.POST } },
  { segments: ["plans","[id]","activate"], paramNames: ["id"], handlers: { POST: plans___id__activate.POST } },
  { segments: ["plans","[id]","close-enrollment"], paramNames: ["id"], handlers: { POST: plans___id__close_enrollment.POST } },
  { segments: ["plans","[id]","open-enrollment"], paramNames: ["id"], handlers: { POST: plans___id__open_enrollment.POST } },
  { segments: ["plans","[id]","renew"], paramNames: ["id"], handlers: { POST: plans___id__renew.POST } },
  { segments: ["plans","[id]","suspend"], paramNames: ["id"], handlers: { POST: plans___id__suspend.POST } },
  { segments: ["plans","[id]","terminate"], paramNames: ["id"], handlers: { POST: plans___id__terminate.POST } },
  { segments: ["providers","[id]","prefer"], paramNames: ["id"], handlers: { POST: providers___id__prefer.POST } },
  { segments: ["providers","[id]","review"], paramNames: ["id"], handlers: { POST: providers___id__review.POST } },
  { segments: ["providers","[id]","terminate"], paramNames: ["id"], handlers: { POST: providers___id__terminate.POST } },
  { segments: ["claims","[id]"], paramNames: ["id"], handlers: { GET: claims___id.GET, PATCH: claims___id.PATCH, DELETE: claims___id.DELETE } },
  { segments: ["enrollments","[id]"], paramNames: ["id"], handlers: { GET: enrollments___id.GET, PATCH: enrollments___id.PATCH, DELETE: enrollments___id.DELETE } },
  { segments: ["plans","[id]"], paramNames: ["id"], handlers: { GET: plans___id.GET, PATCH: plans___id.PATCH, DELETE: plans___id.DELETE } },
  { segments: ["providers","[id]"], paramNames: ["id"], handlers: { GET: providers___id.GET, PATCH: providers___id.PATCH, DELETE: providers___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
