/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/governance/*
 * Consolidates 9 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as checks__run from '@/lib/api-handlers/governance/checks__run';
import * as checks__summary from '@/lib/api-handlers/governance/checks__summary';
import * as retention__check from '@/lib/api-handlers/governance/retention__check';
import * as checks from '@/lib/api-handlers/governance/checks';
import * as dashboard from '@/lib/api-handlers/governance/dashboard';
import * as policies from '@/lib/api-handlers/governance/policies';
import * as retention from '@/lib/api-handlers/governance/retention';
import * as policies___id from '@/lib/api-handlers/governance/policies___id';
import * as retention___id from '@/lib/api-handlers/governance/retention___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["checks","run"], paramNames: [], handlers: { POST: checks__run.POST } },
  { segments: ["checks","summary"], paramNames: [], handlers: { GET: checks__summary.GET } },
  { segments: ["retention","check"], paramNames: [], handlers: { GET: retention__check.GET } },
  { segments: ["checks"], paramNames: [], handlers: { GET: checks.GET, POST: checks.POST } },
  { segments: ["dashboard"], paramNames: [], handlers: { GET: dashboard.GET } },
  { segments: ["policies"], paramNames: [], handlers: { GET: policies.GET, POST: policies.POST } },
  { segments: ["retention"], paramNames: [], handlers: { GET: retention.GET, POST: retention.POST } },
  { segments: ["policies","[id]"], paramNames: ["id"], handlers: { GET: policies___id.GET, PATCH: policies___id.PATCH, DELETE: policies___id.DELETE } },
  { segments: ["retention","[id]"], paramNames: ["id"], handlers: { PATCH: retention___id.PATCH, DELETE: retention___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
