/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/recommendations/*
 * Consolidates 28 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as actions from '@/lib/api-handlers/recommendations/actions';
import * as feedback from '@/lib/api-handlers/recommendations/feedback';
import * as metrics from '@/lib/api-handlers/recommendations/metrics';
import * as models from '@/lib/api-handlers/recommendations/models';
import * as recommendations from '@/lib/api-handlers/recommendations/recommendations';
import * as stats from '@/lib/api-handlers/recommendations/stats';
import * as actions___id__cancel from '@/lib/api-handlers/recommendations/actions___id__cancel';
import * as actions___id__complete from '@/lib/api-handlers/recommendations/actions___id__complete';
import * as actions___id__fail from '@/lib/api-handlers/recommendations/actions___id__fail';
import * as actions___id__start from '@/lib/api-handlers/recommendations/actions___id__start';
import * as feedback___id__archive from '@/lib/api-handlers/recommendations/feedback___id__archive';
import * as feedback___id__incorporate from '@/lib/api-handlers/recommendations/feedback___id__incorporate';
import * as feedback___id__record from '@/lib/api-handlers/recommendations/feedback___id__record';
import * as feedback___id__review from '@/lib/api-handlers/recommendations/feedback___id__review';
import * as models___id__activate from '@/lib/api-handlers/recommendations/models___id__activate';
import * as models___id__archive from '@/lib/api-handlers/recommendations/models___id__archive';
import * as models___id__deprecate from '@/lib/api-handlers/recommendations/models___id__deprecate';
import * as models___id__evaluate from '@/lib/api-handlers/recommendations/models___id__evaluate';
import * as recommendations___id__accept from '@/lib/api-handlers/recommendations/recommendations___id__accept';
import * as recommendations___id__act from '@/lib/api-handlers/recommendations/recommendations___id__act';
import * as recommendations___id__archive from '@/lib/api-handlers/recommendations/recommendations___id__archive';
import * as recommendations___id__dismiss from '@/lib/api-handlers/recommendations/recommendations___id__dismiss';
import * as recommendations___id__present from '@/lib/api-handlers/recommendations/recommendations___id__present';
import * as recommendations___id__reject from '@/lib/api-handlers/recommendations/recommendations___id__reject';
import * as actions___id from '@/lib/api-handlers/recommendations/actions___id';
import * as feedback___id from '@/lib/api-handlers/recommendations/feedback___id';
import * as models___id from '@/lib/api-handlers/recommendations/models___id';
import * as recommendations___id from '@/lib/api-handlers/recommendations/recommendations___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["actions"], paramNames: [], handlers: { GET: actions.GET, POST: actions.POST } },
  { segments: ["feedback"], paramNames: [], handlers: { GET: feedback.GET, POST: feedback.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["models"], paramNames: [], handlers: { GET: models.GET, POST: models.POST } },
  { segments: ["recommendations"], paramNames: [], handlers: { GET: recommendations.GET, POST: recommendations.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["actions","[id]","cancel"], paramNames: ["id"], handlers: { POST: actions___id__cancel.POST } },
  { segments: ["actions","[id]","complete"], paramNames: ["id"], handlers: { POST: actions___id__complete.POST } },
  { segments: ["actions","[id]","fail"], paramNames: ["id"], handlers: { POST: actions___id__fail.POST } },
  { segments: ["actions","[id]","start"], paramNames: ["id"], handlers: { POST: actions___id__start.POST } },
  { segments: ["feedback","[id]","archive"], paramNames: ["id"], handlers: { POST: feedback___id__archive.POST } },
  { segments: ["feedback","[id]","incorporate"], paramNames: ["id"], handlers: { POST: feedback___id__incorporate.POST } },
  { segments: ["feedback","[id]","record"], paramNames: ["id"], handlers: { POST: feedback___id__record.POST } },
  { segments: ["feedback","[id]","review"], paramNames: ["id"], handlers: { POST: feedback___id__review.POST } },
  { segments: ["models","[id]","activate"], paramNames: ["id"], handlers: { POST: models___id__activate.POST } },
  { segments: ["models","[id]","archive"], paramNames: ["id"], handlers: { POST: models___id__archive.POST } },
  { segments: ["models","[id]","deprecate"], paramNames: ["id"], handlers: { POST: models___id__deprecate.POST } },
  { segments: ["models","[id]","evaluate"], paramNames: ["id"], handlers: { POST: models___id__evaluate.POST } },
  { segments: ["recommendations","[id]","accept"], paramNames: ["id"], handlers: { POST: recommendations___id__accept.POST } },
  { segments: ["recommendations","[id]","act"], paramNames: ["id"], handlers: { POST: recommendations___id__act.POST } },
  { segments: ["recommendations","[id]","archive"], paramNames: ["id"], handlers: { POST: recommendations___id__archive.POST } },
  { segments: ["recommendations","[id]","dismiss"], paramNames: ["id"], handlers: { POST: recommendations___id__dismiss.POST } },
  { segments: ["recommendations","[id]","present"], paramNames: ["id"], handlers: { POST: recommendations___id__present.POST } },
  { segments: ["recommendations","[id]","reject"], paramNames: ["id"], handlers: { POST: recommendations___id__reject.POST } },
  { segments: ["actions","[id]"], paramNames: ["id"], handlers: { GET: actions___id.GET, PATCH: actions___id.PATCH, DELETE: actions___id.DELETE } },
  { segments: ["feedback","[id]"], paramNames: ["id"], handlers: { GET: feedback___id.GET, PATCH: feedback___id.PATCH, DELETE: feedback___id.DELETE } },
  { segments: ["models","[id]"], paramNames: ["id"], handlers: { GET: models___id.GET, PATCH: models___id.PATCH, DELETE: models___id.DELETE } },
  { segments: ["recommendations","[id]"], paramNames: ["id"], handlers: { GET: recommendations___id.GET, PATCH: recommendations___id.PATCH, DELETE: recommendations___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
