/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/crisis/*
 * Consolidates 17 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as contacts from '@/lib/api-handlers/crisis/contacts';
import * as drills from '@/lib/api-handlers/crisis/drills';
import * as incidents from '@/lib/api-handlers/crisis/incidents';
import * as metrics from '@/lib/api-handlers/crisis/metrics';
import * as plans from '@/lib/api-handlers/crisis/plans';
import * as stats from '@/lib/api-handlers/crisis/stats';
import * as drills___id__cancel from '@/lib/api-handlers/crisis/drills___id__cancel';
import * as drills___id__complete from '@/lib/api-handlers/crisis/drills___id__complete';
import * as incidents___id__close from '@/lib/api-handlers/crisis/incidents___id__close';
import * as incidents___id__contain from '@/lib/api-handlers/crisis/incidents___id__contain';
import * as incidents___id__resolve from '@/lib/api-handlers/crisis/incidents___id__resolve';
import * as plans___id__approve from '@/lib/api-handlers/crisis/plans___id__approve';
import * as plans___id__review from '@/lib/api-handlers/crisis/plans___id__review';
import * as contacts___id from '@/lib/api-handlers/crisis/contacts___id';
import * as drills___id from '@/lib/api-handlers/crisis/drills___id';
import * as incidents___id from '@/lib/api-handlers/crisis/incidents___id';
import * as plans___id from '@/lib/api-handlers/crisis/plans___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["contacts"], paramNames: [], handlers: { GET: contacts.GET, POST: contacts.POST } },
  { segments: ["drills"], paramNames: [], handlers: { GET: drills.GET, POST: drills.POST } },
  { segments: ["incidents"], paramNames: [], handlers: { GET: incidents.GET, POST: incidents.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["plans"], paramNames: [], handlers: { GET: plans.GET, POST: plans.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["drills","[id]","cancel"], paramNames: ["id"], handlers: { POST: drills___id__cancel.POST } },
  { segments: ["drills","[id]","complete"], paramNames: ["id"], handlers: { POST: drills___id__complete.POST } },
  { segments: ["incidents","[id]","close"], paramNames: ["id"], handlers: { POST: incidents___id__close.POST } },
  { segments: ["incidents","[id]","contain"], paramNames: ["id"], handlers: { POST: incidents___id__contain.POST } },
  { segments: ["incidents","[id]","resolve"], paramNames: ["id"], handlers: { POST: incidents___id__resolve.POST } },
  { segments: ["plans","[id]","approve"], paramNames: ["id"], handlers: { POST: plans___id__approve.POST } },
  { segments: ["plans","[id]","review"], paramNames: ["id"], handlers: { POST: plans___id__review.POST } },
  { segments: ["contacts","[id]"], paramNames: ["id"], handlers: { GET: contacts___id.GET, PATCH: contacts___id.PATCH, DELETE: contacts___id.DELETE } },
  { segments: ["drills","[id]"], paramNames: ["id"], handlers: { GET: drills___id.GET, PATCH: drills___id.PATCH } },
  { segments: ["incidents","[id]"], paramNames: ["id"], handlers: { GET: incidents___id.GET, PATCH: incidents___id.PATCH } },
  { segments: ["plans","[id]"], paramNames: ["id"], handlers: { GET: plans___id.GET, PATCH: plans___id.PATCH, DELETE: plans___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
