/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/supply-chain/*
 * Consolidates 12 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as logistics from '@/lib/api-handlers/supply-chain/logistics';
import * as metrics from '@/lib/api-handlers/supply-chain/metrics';
import * as shipments from '@/lib/api-handlers/supply-chain/shipments';
import * as stats from '@/lib/api-handlers/supply-chain/stats';
import * as supplier_risks from '@/lib/api-handlers/supply-chain/supplier_risks';
import * as suppliers from '@/lib/api-handlers/supply-chain/suppliers';
import * as shipments___id__track from '@/lib/api-handlers/supply-chain/shipments___id__track';
import * as supplier_risks___id__mitigate from '@/lib/api-handlers/supply-chain/supplier_risks___id__mitigate';
import * as logistics___id from '@/lib/api-handlers/supply-chain/logistics___id';
import * as shipments___id from '@/lib/api-handlers/supply-chain/shipments___id';
import * as supplier_risks___id from '@/lib/api-handlers/supply-chain/supplier_risks___id';
import * as suppliers___id from '@/lib/api-handlers/supply-chain/suppliers___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["logistics"], paramNames: [], handlers: { GET: logistics.GET, POST: logistics.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["shipments"], paramNames: [], handlers: { GET: shipments.GET, POST: shipments.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["supplier-risks"], paramNames: [], handlers: { GET: supplier_risks.GET, POST: supplier_risks.POST } },
  { segments: ["suppliers"], paramNames: [], handlers: { GET: suppliers.GET, POST: suppliers.POST } },
  { segments: ["shipments","[id]","track"], paramNames: ["id"], handlers: { POST: shipments___id__track.POST } },
  { segments: ["supplier-risks","[id]","mitigate"], paramNames: ["id"], handlers: { POST: supplier_risks___id__mitigate.POST } },
  { segments: ["logistics","[id]"], paramNames: ["id"], handlers: { GET: logistics___id.GET, PATCH: logistics___id.PATCH } },
  { segments: ["shipments","[id]"], paramNames: ["id"], handlers: { GET: shipments___id.GET, PATCH: shipments___id.PATCH } },
  { segments: ["supplier-risks","[id]"], paramNames: ["id"], handlers: { GET: supplier_risks___id.GET, PATCH: supplier_risks___id.PATCH } },
  { segments: ["suppliers","[id]"], paramNames: ["id"], handlers: { GET: suppliers___id.GET, PATCH: suppliers___id.PATCH, DELETE: suppliers___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path?: string[] }> },
) {
  const { path = [] } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
