/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/job-architecture/*
 * Consolidates 12 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as families from '@/lib/api-handlers/job-architecture/families';
import * as levels from '@/lib/api-handlers/job-architecture/levels';
import * as metrics from '@/lib/api-handlers/job-architecture/metrics';
import * as paths from '@/lib/api-handlers/job-architecture/paths';
import * as roles from '@/lib/api-handlers/job-architecture/roles';
import * as stats from '@/lib/api-handlers/job-architecture/stats';
import * as roles___id__activate from '@/lib/api-handlers/job-architecture/roles___id__activate';
import * as roles___id__archive from '@/lib/api-handlers/job-architecture/roles___id__archive';
import * as families___id from '@/lib/api-handlers/job-architecture/families___id';
import * as levels___id from '@/lib/api-handlers/job-architecture/levels___id';
import * as paths___id from '@/lib/api-handlers/job-architecture/paths___id';
import * as roles___id from '@/lib/api-handlers/job-architecture/roles___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["families"], paramNames: [], handlers: { GET: families.GET, POST: families.POST } },
  { segments: ["levels"], paramNames: [], handlers: { GET: levels.GET, POST: levels.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["paths"], paramNames: [], handlers: { GET: paths.GET, POST: paths.POST } },
  { segments: ["roles"], paramNames: [], handlers: { GET: roles.GET, POST: roles.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["roles","[id]","activate"], paramNames: ["id"], handlers: { POST: roles___id__activate.POST } },
  { segments: ["roles","[id]","archive"], paramNames: ["id"], handlers: { POST: roles___id__archive.POST } },
  { segments: ["families","[id]"], paramNames: ["id"], handlers: { GET: families___id.GET, PATCH: families___id.PATCH, DELETE: families___id.DELETE } },
  { segments: ["levels","[id]"], paramNames: ["id"], handlers: { GET: levels___id.GET, PATCH: levels___id.PATCH, DELETE: levels___id.DELETE } },
  { segments: ["paths","[id]"], paramNames: ["id"], handlers: { GET: paths___id.GET, PATCH: paths___id.PATCH, DELETE: paths___id.DELETE } },
  { segments: ["roles","[id]"], paramNames: ["id"], handlers: { GET: roles___id.GET, PATCH: roles___id.PATCH, DELETE: roles___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
