import dynamic from 'next/dynamic';
import { notFound } from 'next/navigation';
import { getCreativeFeature } from '@/lib/creative/registry';
import type { ComponentType } from 'react';

const PAGE_LOADERS: Record<string, () => Promise<{ default: ComponentType }>> = {
  'ad-ab-test-name-generator': () => import('@/components/creative-pages/ad-ab-test-name-generator'),
  'ad-audience-pain-point-mapper': () => import('@/components/creative-pages/ad-audience-pain-point-mapper'),
  'ad-audience-psychographic-profiler': () => import('@/components/creative-pages/ad-audience-psychographic-profiler'),
  'ad-audience-resonance-predictor': () => import('@/components/creative-pages/ad-audience-resonance-predictor'),
  'ad-audience-segment-builder': () => import('@/components/creative-pages/ad-audience-segment-builder'),
  'ad-budget-allocator': () => import('@/components/creative-pages/ad-budget-allocator'),
  'ad-caption-generator': () => import('@/components/creative-pages/ad-caption-generator'),
  'ad-color-palette-generator': () => import('@/components/creative-pages/ad-color-palette-generator'),
  'ad-competitive-intelligence': () => import('@/components/creative-pages/ad-competitive-intelligence'),
  'ad-concept-merger': () => import('@/components/creative-pages/ad-concept-merger'),
  'ad-copy-generator': () => import('@/components/creative-pages/ad-copy-generator'),
  'ad-creative-ab-test-simulator': () => import('@/components/creative-pages/ad-creative-ab-test-simulator'),
  'ad-creative-aida-framework-designer': () => import('@/components/creative-pages/ad-creative-aida-framework-designer'),
  'ad-creative-anchoring-effect-designer': () => import('@/components/creative-pages/ad-creative-anchoring-effect-designer'),
  'ad-creative-authority-positioning-designer': () => import('@/components/creative-pages/ad-creative-authority-positioning-designer'),
  'ad-creative-bab-framework-designer': () => import('@/components/creative-pages/ad-creative-bab-framework-designer'),
  'ad-creative-belief-shift-designer': () => import('@/components/creative-pages/ad-creative-belief-shift-designer'),
  'ad-creative-burnout-detector': () => import('@/components/creative-pages/ad-creative-burnout-detector'),
  'ad-creative-callback-memory-designer': () => import('@/components/creative-pages/ad-creative-callback-memory-designer'),
  'ad-creative-choice-simplifier-designer': () => import('@/components/creative-pages/ad-creative-choice-simplifier-designer'),
  'ad-creative-contrast-amplifier': () => import('@/components/creative-pages/ad-creative-contrast-amplifier'),
  'ad-creative-curiosity-loop-designer': () => import('@/components/creative-pages/ad-creative-curiosity-loop-designer'),
  'ad-creative-decoy-effect-designer': () => import('@/components/creative-pages/ad-creative-decoy-effect-designer'),
  'ad-creative-demonstration-framework-designer': () => import('@/components/creative-pages/ad-creative-demonstration-framework-designer'),
  'ad-creative-emotion-sequencer': () => import('@/components/creative-pages/ad-creative-emotion-sequencer'),
  'ad-creative-emotional-anchor-designer': () => import('@/components/creative-pages/ad-creative-emotional-anchor-designer'),
  'ad-creative-emotional-pivot-designer': () => import('@/components/creative-pages/ad-creative-emotional-pivot-designer'),
  'ad-creative-fear-appeal-designer': () => import('@/components/creative-pages/ad-creative-fear-appeal-designer'),
  'ad-creative-future-pacing-designer': () => import('@/components/creative-pages/ad-creative-future-pacing-designer'),
  'ad-creative-hook-story-offer-designer': () => import('@/components/creative-pages/ad-creative-hook-story-offer-designer'),
  'ad-creative-hook-timing-optimizer': () => import('@/components/creative-pages/ad-creative-hook-timing-optimizer'),
  'ad-creative-humor-appeal-designer': () => import('@/components/creative-pages/ad-creative-humor-appeal-designer'),
  'ad-creative-implementation-intention-designer': () => import('@/components/creative-pages/ad-creative-implementation-intention-designer'),
  'ad-creative-lifecycle-manager': () => import('@/components/creative-pages/ad-creative-lifecycle-manager'),
  'ad-creative-memory-anchor-builder': () => import('@/components/creative-pages/ad-creative-memory-anchor-builder'),
  'ad-creative-mental-accounting-designer': () => import('@/components/creative-pages/ad-creative-mental-accounting-designer'),
  'ad-creative-objection-neutralizer-designer': () => import('@/components/creative-pages/ad-creative-objection-neutralizer-designer'),
  'ad-creative-pacing-variability-designer': () => import('@/components/creative-pages/ad-creative-pacing-variability-designer'),
  'ad-creative-pain-of-paying-designer': () => import('@/components/creative-pages/ad-creative-pain-of-paying-designer'),
  'ad-creative-pas-framework-designer': () => import('@/components/creative-pages/ad-creative-pas-framework-designer'),
  'ad-creative-pride-appeal-designer': () => import('@/components/creative-pages/ad-creative-pride-appeal-designer'),
  'ad-creative-rhythm-pacing-optimizer': () => import('@/components/creative-pages/ad-creative-rhythm-pacing-optimizer'),
  'ad-creative-risk-reversal-designer': () => import('@/components/creative-pages/ad-creative-risk-reversal-designer'),
  'ad-creative-rotator': () => import('@/components/creative-pages/ad-creative-rotator'),
  'ad-creative-scarcity-frame-designer': () => import('@/components/creative-pages/ad-creative-scarcity-frame-designer'),
  'ad-creative-sensory-contrast-designer': () => import('@/components/creative-pages/ad-creative-sensory-contrast-designer'),
  'ad-creative-sensory-enhancer': () => import('@/components/creative-pages/ad-creative-sensory-enhancer'),
  'ad-creative-sequencer': () => import('@/components/creative-pages/ad-creative-sequencer'),
  'ad-creative-social-momentum-designer': () => import('@/components/creative-pages/ad-creative-social-momentum-designer'),
  'ad-creative-social-proof-architect': () => import('@/components/creative-pages/ad-creative-social-proof-architect'),
  'ad-creative-sound-design-strategist': () => import('@/components/creative-pages/ad-creative-sound-design-strategist'),
  'ad-creative-story-arc-designer': () => import('@/components/creative-pages/ad-creative-story-arc-designer'),
  'ad-creative-tension-release-designer': () => import('@/components/creative-pages/ad-creative-tension-release-designer'),
  'ad-creative-testimonial-architecture-designer': () => import('@/components/creative-pages/ad-creative-testimonial-architecture-designer'),
  'ad-creative-trust-accelerator-designer': () => import('@/components/creative-pages/ad-creative-trust-accelerator-designer'),
  'ad-creative-unique-mechanism-designer': () => import('@/components/creative-pages/ad-creative-unique-mechanism-designer'),
  'ad-creative-viewer-reward-designer': () => import('@/components/creative-pages/ad-creative-viewer-reward-designer'),
  'ad-cta-optimizer': () => import('@/components/creative-pages/ad-cta-optimizer'),
  'ad-emotion-analyzer': () => import('@/components/creative-pages/ad-emotion-analyzer'),
  'ad-font-pairing-generator': () => import('@/components/creative-pages/ad-font-pairing-generator'),
  'ad-format-optimizer': () => import('@/components/creative-pages/ad-format-optimizer'),
  'ad-hashtag-generator': () => import('@/components/creative-pages/ad-hashtag-generator'),
  'ad-headline-generator': () => import('@/components/creative-pages/ad-headline-generator'),
  'ad-localization-adapter': () => import('@/components/creative-pages/ad-localization-adapter'),
  'ad-music-mood-matcher': () => import('@/components/creative-pages/ad-music-mood-matcher'),
  'ad-performance-predictor': () => import('@/components/creative-pages/ad-performance-predictor'),
  'ad-persona-matcher': () => import('@/components/creative-pages/ad-persona-matcher'),
  'ad-placement-strategist': () => import('@/components/creative-pages/ad-placement-strategist'),
  'ad-script-writer': () => import('@/components/creative-pages/ad-script-writer'),
  'ad-sentiment-tuner': () => import('@/components/creative-pages/ad-sentiment-tuner'),
  'ad-story-generator': () => import('@/components/creative-pages/ad-story-generator'),
  'ad-thumbnail-generator': () => import('@/components/creative-pages/ad-thumbnail-generator'),
  'ad-timing-optimizer': () => import('@/components/creative-pages/ad-timing-optimizer'),
  'ad-voiceover-script-generator': () => import('@/components/creative-pages/ad-voiceover-script-generator'),
  'angle-finder': () => import('@/components/creative-pages/angle-finder'),
  'audience-persona-generator': () => import('@/components/creative-pages/audience-persona-generator'),
  'brand-guardrails': () => import('@/components/creative-pages/brand-guardrails'),
  'brand-story-architect': () => import('@/components/creative-pages/brand-story-architect'),
  'brand-voice-analyzer': () => import('@/components/creative-pages/brand-voice-analyzer'),
  'brand-voice-consistency-checker': () => import('@/components/creative-pages/brand-voice-consistency-checker'),
  'brief-analyzer': () => import('@/components/creative-pages/brief-analyzer'),
  'brief-template-builder': () => import('@/components/creative-pages/brief-template-builder'),
  'competitor-watch': () => import('@/components/creative-pages/competitor-watch'),
  'concept-expander': () => import('@/components/creative-pages/concept-expander'),
  'creative-ad-anticipation-builder': () => import('@/components/creative-pages/creative-ad-anticipation-builder'),
  'creative-ad-belonging-appeal-designer': () => import('@/components/creative-pages/creative-ad-belonging-appeal-designer'),
  'creative-ad-climax-architect': () => import('@/components/creative-pages/creative-ad-climax-architect'),
  'creative-ad-comparison-framework-designer': () => import('@/components/creative-pages/creative-ad-comparison-framework-designer'),
  'creative-ad-concept-synthesizer': () => import('@/components/creative-pages/creative-ad-concept-synthesizer'),
  'creative-ad-curiosity-gap-designer': () => import('@/components/creative-pages/creative-ad-curiosity-gap-designer'),
  'creative-ad-desire-amplifier-designer': () => import('@/components/creative-pages/creative-ad-desire-amplifier-designer'),
  'creative-ad-empathy-bridge-designer': () => import('@/components/creative-pages/creative-ad-empathy-bridge-designer'),
  'creative-ad-endowment-effect-designer': () => import('@/components/creative-pages/creative-ad-endowment-effect-designer'),
  'creative-ad-fab-framework-designer': () => import('@/components/creative-pages/creative-ad-fab-framework-designer'),
  'creative-ad-foreshadowing-designer': () => import('@/components/creative-pages/creative-ad-foreshadowing-designer'),
  'creative-ad-format-innovator': () => import('@/components/creative-pages/creative-ad-format-innovator'),
  'creative-ad-framing-effect-designer': () => import('@/components/creative-pages/creative-ad-framing-effect-designer'),
  'creative-ad-identity-alignment-designer': () => import('@/components/creative-pages/creative-ad-identity-alignment-designer'),
  'creative-ad-liking-affinity-designer': () => import('@/components/creative-pages/creative-ad-liking-affinity-designer'),
  'creative-ad-loss-aversion-framing-designer': () => import('@/components/creative-pages/creative-ad-loss-aversion-framing-designer'),
  'creative-ad-metaphor-generator': () => import('@/components/creative-pages/creative-ad-metaphor-generator'),
  'creative-ad-micro-commitment-designer': () => import('@/components/creative-pages/creative-ad-micro-commitment-designer'),
  'creative-ad-micro-moment-designer': () => import('@/components/creative-pages/creative-ad-micro-moment-designer'),
  'creative-ad-narrative-twist-designer': () => import('@/components/creative-pages/creative-ad-narrative-twist-designer'),
  'creative-ad-nostalgia-trigger-designer': () => import('@/components/creative-pages/creative-ad-nostalgia-trigger-designer'),
  'creative-ad-offer-architecture-designer': () => import('@/components/creative-pages/creative-ad-offer-architecture-designer'),
  'creative-ad-pattern-interrupt-designer': () => import('@/components/creative-pages/creative-ad-pattern-interrupt-designer'),
  'creative-ad-persuasion-strategist': () => import('@/components/creative-pages/creative-ad-persuasion-strategist'),
  'creative-ad-price-framing-designer': () => import('@/components/creative-pages/creative-ad-price-framing-designer'),
  'creative-ad-reciprocity-trigger-designer': () => import('@/components/creative-pages/creative-ad-reciprocity-trigger-designer'),
  'creative-ad-resolution-designer': () => import('@/components/creative-pages/creative-ad-resolution-designer'),
  'creative-ad-stakes-escalation-designer': () => import('@/components/creative-pages/creative-ad-stakes-escalation-designer'),
  'creative-ad-surprise-element-designer': () => import('@/components/creative-pages/creative-ad-surprise-element-designer'),
  'creative-ad-tension-release-strategist': () => import('@/components/creative-pages/creative-ad-tension-release-strategist'),
  'creative-ad-tone-calibrator': () => import('@/components/creative-pages/creative-ad-tone-calibrator'),
  'creative-ad-transformation-arc-designer': () => import('@/components/creative-pages/creative-ad-transformation-arc-designer'),
  'creative-ad-urgency-catalyst-designer': () => import('@/components/creative-pages/creative-ad-urgency-catalyst-designer'),
  'creative-ad-value-ladder-designer': () => import('@/components/creative-pages/creative-ad-value-ladder-designer'),
  'creative-ad-visual-hierarchy-strategist': () => import('@/components/creative-pages/creative-ad-visual-hierarchy-strategist'),
  'creative-brief-generator': () => import('@/components/creative-pages/creative-brief-generator'),
  'creative-concept-expander-pro': () => import('@/components/creative-pages/creative-concept-expander-pro'),
  'creative-concept-validator': () => import('@/components/creative-pages/creative-concept-validator'),
  'creative-fatigue-detector': () => import('@/components/creative-pages/creative-fatigue-detector'),
  'creative-format-converter': () => import('@/components/creative-pages/creative-format-converter'),
  'creative-format-recommender': () => import('@/components/creative-pages/creative-format-recommender'),
  'creative-hook-matrix-generator': () => import('@/components/creative-pages/creative-hook-matrix-generator'),
  'creative-hook-revamp-generator': () => import('@/components/creative-pages/creative-hook-revamp-generator'),
  'creative-messaging-framework-builder': () => import('@/components/creative-pages/creative-messaging-framework-builder'),
  'creative-performance-forecaster': () => import('@/components/creative-pages/creative-performance-forecaster'),
  'creative-quality-scorer': () => import('@/components/creative-pages/creative-quality-scorer'),
  'creative-scene-generator': () => import('@/components/creative-pages/creative-scene-generator'),
  'creative-sentiment-journey-mapper': () => import('@/components/creative-pages/creative-sentiment-journey-mapper'),
  'creative-trend-adapter': () => import('@/components/creative-pages/creative-trend-adapter'),
  'creative-visual-hierarchy-analyzer': () => import('@/components/creative-pages/creative-visual-hierarchy-analyzer'),
  'hook-library': () => import('@/components/creative-pages/hook-library'),
  'hook-tester': () => import('@/components/creative-pages/hook-tester'),
  'mood-board-generator': () => import('@/components/creative-pages/mood-board-generator'),
  'multi-concept': () => import('@/components/creative-pages/multi-concept'),
  'performance-loop': () => import('@/components/creative-pages/performance-loop'),
  'product-brief': () => import('@/components/creative-pages/product-brief'),
  'reference-remix': () => import('@/components/creative-pages/reference-remix'),
  'trend-spotter': () => import('@/components/creative-pages/trend-spotter'),
  'variant-matrix-generator': () => import('@/components/creative-pages/variant-matrix-generator'),
};

export function generateStaticParams() {
  return Object.keys(PAGE_LOADERS).map((feature) => ({ feature }));
}

export const dynamicParams = false;

export default async function CreativeFeaturePage({
  params,
}: {
  params: Promise<{ feature: string }>;
}) {
  const { feature } = await params;
  if (!getCreativeFeature(feature)) notFound();
  const loader = PAGE_LOADERS[feature];
  if (!loader) notFound();
  const Component = dynamic(loader);
  return <Component />;
}
