/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/emergency-response/*
 * Consolidates 29 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as contacts from '@/lib/api-handlers/emergency-response/contacts';
import * as drills from '@/lib/api-handlers/emergency-response/drills';
import * as metrics from '@/lib/api-handlers/emergency-response/metrics';
import * as plans from '@/lib/api-handlers/emergency-response/plans';
import * as routes from '@/lib/api-handlers/emergency-response/routes';
import * as stats from '@/lib/api-handlers/emergency-response/stats';
import * as index from '@/lib/api-handlers/emergency-response/index';
import * as contacts___id__activate from '@/lib/api-handlers/emergency-response/contacts___id__activate';
import * as contacts___id__deactivate from '@/lib/api-handlers/emergency-response/contacts___id__deactivate';
import * as contacts___id__mark_backup from '@/lib/api-handlers/emergency-response/contacts___id__mark_backup';
import * as contacts___id__mark_unreachable from '@/lib/api-handlers/emergency-response/contacts___id__mark_unreachable';
import * as drills___id__cancel from '@/lib/api-handlers/emergency-response/drills___id__cancel';
import * as drills___id__complete from '@/lib/api-handlers/emergency-response/drills___id__complete';
import * as drills___id__fail from '@/lib/api-handlers/emergency-response/drills___id__fail';
import * as drills___id__schedule from '@/lib/api-handlers/emergency-response/drills___id__schedule';
import * as drills___id__start from '@/lib/api-handlers/emergency-response/drills___id__start';
import * as plans___id__activate from '@/lib/api-handlers/emergency-response/plans___id__activate';
import * as plans___id__archive from '@/lib/api-handlers/emergency-response/plans___id__archive';
import * as plans___id__deprecate from '@/lib/api-handlers/emergency-response/plans___id__deprecate';
import * as plans___id__test from '@/lib/api-handlers/emergency-response/plans___id__test';
import * as routes___id__activate from '@/lib/api-handlers/emergency-response/routes___id__activate';
import * as routes___id__block from '@/lib/api-handlers/emergency-response/routes___id__block';
import * as routes___id__deprecate from '@/lib/api-handlers/emergency-response/routes___id__deprecate';
import * as routes___id__maintain from '@/lib/api-handlers/emergency-response/routes___id__maintain';
import * as contacts___id from '@/lib/api-handlers/emergency-response/contacts___id';
import * as drills___id from '@/lib/api-handlers/emergency-response/drills___id';
import * as plans___id from '@/lib/api-handlers/emergency-response/plans___id';
import * as routes___id from '@/lib/api-handlers/emergency-response/routes___id';
import * as _id from '@/lib/api-handlers/emergency-response/_id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["contacts"], paramNames: [], handlers: { GET: contacts.GET, POST: contacts.POST } },
  { segments: ["drills"], paramNames: [], handlers: { GET: drills.GET, POST: drills.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["plans"], paramNames: [], handlers: { GET: plans.GET, POST: plans.POST } },
  { segments: ["routes"], paramNames: [], handlers: { GET: routes.GET, POST: routes.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: [], paramNames: [], handlers: { GET: index.GET, POST: index.POST } },
  { segments: ["contacts","[id]","activate"], paramNames: ["id"], handlers: { POST: contacts___id__activate.POST } },
  { segments: ["contacts","[id]","deactivate"], paramNames: ["id"], handlers: { POST: contacts___id__deactivate.POST } },
  { segments: ["contacts","[id]","mark-backup"], paramNames: ["id"], handlers: { POST: contacts___id__mark_backup.POST } },
  { segments: ["contacts","[id]","mark-unreachable"], paramNames: ["id"], handlers: { POST: contacts___id__mark_unreachable.POST } },
  { segments: ["drills","[id]","cancel"], paramNames: ["id"], handlers: { POST: drills___id__cancel.POST } },
  { segments: ["drills","[id]","complete"], paramNames: ["id"], handlers: { POST: drills___id__complete.POST } },
  { segments: ["drills","[id]","fail"], paramNames: ["id"], handlers: { POST: drills___id__fail.POST } },
  { segments: ["drills","[id]","schedule"], paramNames: ["id"], handlers: { POST: drills___id__schedule.POST } },
  { segments: ["drills","[id]","start"], paramNames: ["id"], handlers: { POST: drills___id__start.POST } },
  { segments: ["plans","[id]","activate"], paramNames: ["id"], handlers: { POST: plans___id__activate.POST } },
  { segments: ["plans","[id]","archive"], paramNames: ["id"], handlers: { POST: plans___id__archive.POST } },
  { segments: ["plans","[id]","deprecate"], paramNames: ["id"], handlers: { POST: plans___id__deprecate.POST } },
  { segments: ["plans","[id]","test"], paramNames: ["id"], handlers: { POST: plans___id__test.POST } },
  { segments: ["routes","[id]","activate"], paramNames: ["id"], handlers: { POST: routes___id__activate.POST } },
  { segments: ["routes","[id]","block"], paramNames: ["id"], handlers: { POST: routes___id__block.POST } },
  { segments: ["routes","[id]","deprecate"], paramNames: ["id"], handlers: { POST: routes___id__deprecate.POST } },
  { segments: ["routes","[id]","maintain"], paramNames: ["id"], handlers: { POST: routes___id__maintain.POST } },
  { segments: ["contacts","[id]"], paramNames: ["id"], handlers: { GET: contacts___id.GET, PATCH: contacts___id.PATCH, DELETE: contacts___id.DELETE } },
  { segments: ["drills","[id]"], paramNames: ["id"], handlers: { GET: drills___id.GET, PATCH: drills___id.PATCH, DELETE: drills___id.DELETE } },
  { segments: ["plans","[id]"], paramNames: ["id"], handlers: { GET: plans___id.GET, PATCH: plans___id.PATCH, DELETE: plans___id.DELETE } },
  { segments: ["routes","[id]"], paramNames: ["id"], handlers: { GET: routes___id.GET, PATCH: routes___id.PATCH, DELETE: routes___id.DELETE } },
  { segments: ["[id]"], paramNames: ["id"], handlers: { GET: _id.GET, PATCH: _id.PATCH, DELETE: _id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
