import type { Metadata } from 'next';
import { LegalPage, makeMetadata } from '@/components/LegalPage';

export const metadata: Metadata = makeMetadata('AI Usage Policy — Lazynext', 'Policy for AI-generated content and AI agent usage on Lazynext.');

const year = new Date().getFullYear();

export default function AiPolicyPage() {
  return (
    <LegalPage
      title="AI Usage Policy"
      lastUpdated={`Last updated: ${year}`}
      description="This policy governs the use of AI features on the Lazynext platform, including content generation, AI agents, and automated workflows."
      sections={[
        {
          title: '1. Scope',
          body: 'This AI Usage Policy applies to all AI-powered features of Lazynext, including creative content generation, AI agents, automation workflows, and any other features that use artificial intelligence or machine learning models. AI generation is powered by Atlas Cloud and other provider models.',
        },
        {
          title: '2. User Responsibility',
          body: 'You are solely responsible for the prompts you submit, the content generated by AI features, and the actions taken by AI agents you create. You must review AI-generated content before publishing or distributing it. AI-generated content may contain inaccuracies, biases, or unintended outputs.',
        },
        {
          title: '3. Prohibited AI Uses',
          list: [
            'Generating deepfakes or synthetic media that impersonate real people without their consent.',
            'Generating content that violates our Acceptable Use Policy.',
            'Creating content designed to deceive, defraud, or manipulate individuals.',
            'Using AI agents to access, modify, or delete data beyond their authorized scope.',
            'Using AI features to generate content that infringes on intellectual property rights.',
            'Using AI to generate content that promotes illegal activities.',
            'Deploying AI agents that operate without appropriate human oversight for high-risk decisions.',
          ],
        },
        {
          title: '4. AI Agents and Automations',
          body: 'AI agents and automations you create on Lazynext operate under your account and workspace credentials. You are responsible for configuring appropriate instructions, tool access, and scope limitations. Agents that cause harm through unauthorized actions are your responsibility. We recommend human-in-the-loop review for automations that affect production systems, financial transactions, or external communications.',
        },
        {
          title: '5. Data Processing',
          body: 'When you use AI features, your inputs (prompts, images, documents) are sent to AI providers (Atlas Cloud and others) for processing. These providers may retain data temporarily for safety and quality purposes. We do not use your private workspace content to train AI models. See our Privacy Policy and subprocessor list for details.',
        },
        {
          title: '6. Transparency and Disclosure',
          body: 'You should disclose when content is AI-generated where required by law, platform policies, or ethical norms. Some jurisdictions require labeling of synthetic media. You are responsible for complying with applicable disclosure requirements.',
        },
        {
          title: '7. Model Limitations',
          body: 'AI models have limitations and may produce biased, inaccurate, or harmful outputs. We do not guarantee the quality, accuracy, or appropriateness of AI-generated content. You should implement appropriate review and filtering processes for your use case.',
        },
        {
          title: '8. Provider Policies',
          body: 'AI generation on Lazynext is powered by Atlas Cloud and other providers. Your use of AI features is also subject to the usage policies of these providers. We may restrict or modify AI features based on provider policy changes.',
        },
        {
          title: '9. Changes',
          body: 'We may update this AI Usage Policy as AI technology and regulations evolve. Continued use of AI features after changes constitutes acceptance of the revised policy.',
        },
        {
          title: '10. Contact',
          body: 'For questions about this AI Usage Policy, contact us at ai-policy@lazynext.com.',
        },
      ]}
    />
  );
}
