/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/accounting/*
 * Consolidates 13 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as chart_of_accounts from '@/lib/api-handlers/accounting/chart_of_accounts';
import * as close_period from '@/lib/api-handlers/accounting/close_period';
import * as financial_statements from '@/lib/api-handlers/accounting/financial_statements';
import * as general_ledger from '@/lib/api-handlers/accounting/general_ledger';
import * as journal_entries from '@/lib/api-handlers/accounting/journal_entries';
import * as stats from '@/lib/api-handlers/accounting/stats';
import * as trial_balance from '@/lib/api-handlers/accounting/trial_balance';
import * as index from '@/lib/api-handlers/accounting/index';
import * as accounts__balance___id from '@/lib/api-handlers/accounting/accounts__balance___id';
import * as journal_entries___id__post from '@/lib/api-handlers/accounting/journal_entries___id__post';
import * as journal_entries___id__reverse from '@/lib/api-handlers/accounting/journal_entries___id__reverse';
import * as journal_entries___id from '@/lib/api-handlers/accounting/journal_entries___id';
import * as _id from '@/lib/api-handlers/accounting/_id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["chart-of-accounts"], paramNames: [], handlers: { GET: chart_of_accounts.GET } },
  { segments: ["close-period"], paramNames: [], handlers: { POST: close_period.POST } },
  { segments: ["financial-statements"], paramNames: [], handlers: { GET: financial_statements.GET } },
  { segments: ["general-ledger"], paramNames: [], handlers: { GET: general_ledger.GET } },
  { segments: ["journal-entries"], paramNames: [], handlers: { GET: journal_entries.GET, POST: journal_entries.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["trial-balance"], paramNames: [], handlers: { GET: trial_balance.GET } },
  { segments: [], paramNames: [], handlers: { GET: index.GET, POST: index.POST } },
  { segments: ["accounts","balance","[id]"], paramNames: ["id"], handlers: { GET: accounts__balance___id.GET } },
  { segments: ["journal-entries","[id]","post"], paramNames: ["id"], handlers: { POST: journal_entries___id__post.POST } },
  { segments: ["journal-entries","[id]","reverse"], paramNames: ["id"], handlers: { POST: journal_entries___id__reverse.POST } },
  { segments: ["journal-entries","[id]"], paramNames: ["id"], handlers: { GET: journal_entries___id.GET } },
  { segments: ["[id]"], paramNames: ["id"], handlers: { GET: _id.GET, PATCH: _id.PATCH, DELETE: _id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
