/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/regulatory/*
 * Consolidates 21 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as changes from '@/lib/api-handlers/regulatory/changes';
import * as filings from '@/lib/api-handlers/regulatory/filings';
import * as metrics from '@/lib/api-handlers/regulatory/metrics';
import * as monitoring from '@/lib/api-handlers/regulatory/monitoring';
import * as requirements from '@/lib/api-handlers/regulatory/requirements';
import * as stats from '@/lib/api-handlers/regulatory/stats';
import * as submissions from '@/lib/api-handlers/regulatory/submissions';
import * as changes___id__assess from '@/lib/api-handlers/regulatory/changes___id__assess';
import * as changes___id__implement from '@/lib/api-handlers/regulatory/changes___id__implement';
import * as filings___id__accept from '@/lib/api-handlers/regulatory/filings___id__accept';
import * as filings___id__reject from '@/lib/api-handlers/regulatory/filings___id__reject';
import * as filings___id__submit from '@/lib/api-handlers/regulatory/filings___id__submit';
import * as monitoring___id__finding from '@/lib/api-handlers/regulatory/monitoring___id__finding';
import * as requirements___id__assess from '@/lib/api-handlers/regulatory/requirements___id__assess';
import * as submissions___id__response from '@/lib/api-handlers/regulatory/submissions___id__response';
import * as submissions___id__submit from '@/lib/api-handlers/regulatory/submissions___id__submit';
import * as changes___id from '@/lib/api-handlers/regulatory/changes___id';
import * as filings___id from '@/lib/api-handlers/regulatory/filings___id';
import * as monitoring___id from '@/lib/api-handlers/regulatory/monitoring___id';
import * as requirements___id from '@/lib/api-handlers/regulatory/requirements___id';
import * as submissions___id from '@/lib/api-handlers/regulatory/submissions___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["changes"], paramNames: [], handlers: { GET: changes.GET, POST: changes.POST } },
  { segments: ["filings"], paramNames: [], handlers: { GET: filings.GET, POST: filings.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["monitoring"], paramNames: [], handlers: { GET: monitoring.GET, POST: monitoring.POST } },
  { segments: ["requirements"], paramNames: [], handlers: { GET: requirements.GET, POST: requirements.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["submissions"], paramNames: [], handlers: { GET: submissions.GET, POST: submissions.POST } },
  { segments: ["changes","[id]","assess"], paramNames: ["id"], handlers: { POST: changes___id__assess.POST } },
  { segments: ["changes","[id]","implement"], paramNames: ["id"], handlers: { POST: changes___id__implement.POST } },
  { segments: ["filings","[id]","accept"], paramNames: ["id"], handlers: { POST: filings___id__accept.POST } },
  { segments: ["filings","[id]","reject"], paramNames: ["id"], handlers: { POST: filings___id__reject.POST } },
  { segments: ["filings","[id]","submit"], paramNames: ["id"], handlers: { POST: filings___id__submit.POST } },
  { segments: ["monitoring","[id]","finding"], paramNames: ["id"], handlers: { POST: monitoring___id__finding.POST } },
  { segments: ["requirements","[id]","assess"], paramNames: ["id"], handlers: { POST: requirements___id__assess.POST } },
  { segments: ["submissions","[id]","response"], paramNames: ["id"], handlers: { POST: submissions___id__response.POST } },
  { segments: ["submissions","[id]","submit"], paramNames: ["id"], handlers: { POST: submissions___id__submit.POST } },
  { segments: ["changes","[id]"], paramNames: ["id"], handlers: { GET: changes___id.GET, PATCH: changes___id.PATCH } },
  { segments: ["filings","[id]"], paramNames: ["id"], handlers: { GET: filings___id.GET, PATCH: filings___id.PATCH } },
  { segments: ["monitoring","[id]"], paramNames: ["id"], handlers: { GET: monitoring___id.GET, PATCH: monitoring___id.PATCH, DELETE: monitoring___id.DELETE } },
  { segments: ["requirements","[id]"], paramNames: ["id"], handlers: { GET: requirements___id.GET, PATCH: requirements___id.PATCH, DELETE: requirements___id.DELETE } },
  { segments: ["submissions","[id]"], paramNames: ["id"], handlers: { GET: submissions___id.GET, PATCH: submissions___id.PATCH } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
