/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/platform/*
 * Consolidates 15 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as sdk__endpoints from '@/lib/api-handlers/platform/sdk__endpoints';
import * as sdk__generate from '@/lib/api-handlers/platform/sdk__generate';
import * as usage__errors from '@/lib/api-handlers/platform/usage__errors';
import * as usage__slow from '@/lib/api-handlers/platform/usage__slow';
import * as docs from '@/lib/api-handlers/platform/docs';
import * as keys from '@/lib/api-handlers/platform/keys';
import * as usage from '@/lib/api-handlers/platform/usage';
import * as webhooks from '@/lib/api-handlers/platform/webhooks';
import * as keys___id__revoke from '@/lib/api-handlers/platform/keys___id__revoke';
import * as keys___id__usage from '@/lib/api-handlers/platform/keys___id__usage';
import * as webhooks___id__pause from '@/lib/api-handlers/platform/webhooks___id__pause';
import * as webhooks___id__resume from '@/lib/api-handlers/platform/webhooks___id__resume';
import * as webhooks___id__test from '@/lib/api-handlers/platform/webhooks___id__test';
import * as keys___id from '@/lib/api-handlers/platform/keys___id';
import * as webhooks___id from '@/lib/api-handlers/platform/webhooks___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["sdk","endpoints"], paramNames: [], handlers: { GET: sdk__endpoints.GET } },
  { segments: ["sdk","generate"], paramNames: [], handlers: { POST: sdk__generate.POST } },
  { segments: ["usage","errors"], paramNames: [], handlers: { GET: usage__errors.GET } },
  { segments: ["usage","slow"], paramNames: [], handlers: { GET: usage__slow.GET } },
  { segments: ["docs"], paramNames: [], handlers: { GET: docs.GET } },
  { segments: ["keys"], paramNames: [], handlers: { GET: keys.GET, POST: keys.POST } },
  { segments: ["usage"], paramNames: [], handlers: { GET: usage.GET } },
  { segments: ["webhooks"], paramNames: [], handlers: { GET: webhooks.GET, POST: webhooks.POST } },
  { segments: ["keys","[id]","revoke"], paramNames: ["id"], handlers: { POST: keys___id__revoke.POST } },
  { segments: ["keys","[id]","usage"], paramNames: ["id"], handlers: { GET: keys___id__usage.GET } },
  { segments: ["webhooks","[id]","pause"], paramNames: ["id"], handlers: { POST: webhooks___id__pause.POST } },
  { segments: ["webhooks","[id]","resume"], paramNames: ["id"], handlers: { POST: webhooks___id__resume.POST } },
  { segments: ["webhooks","[id]","test"], paramNames: ["id"], handlers: { POST: webhooks___id__test.POST } },
  { segments: ["keys","[id]"], paramNames: ["id"], handlers: { GET: keys___id.GET, PATCH: keys___id.PATCH, DELETE: keys___id.DELETE } },
  { segments: ["webhooks","[id]"], paramNames: ["id"], handlers: { GET: webhooks___id.GET, PATCH: webhooks___id.PATCH, DELETE: webhooks___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
