/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/pricing/*
 * Consolidates 14 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as discounts from '@/lib/api-handlers/pricing/discounts';
import * as experiments from '@/lib/api-handlers/pricing/experiments';
import * as metrics from '@/lib/api-handlers/pricing/metrics';
import * as models from '@/lib/api-handlers/pricing/models';
import * as revenue_streams from '@/lib/api-handlers/pricing/revenue_streams';
import * as stats from '@/lib/api-handlers/pricing/stats';
import * as tiers from '@/lib/api-handlers/pricing/tiers';
import * as experiments___id__end from '@/lib/api-handlers/pricing/experiments___id__end';
import * as experiments___id__start from '@/lib/api-handlers/pricing/experiments___id__start';
import * as discounts___id from '@/lib/api-handlers/pricing/discounts___id';
import * as experiments___id from '@/lib/api-handlers/pricing/experiments___id';
import * as models___id from '@/lib/api-handlers/pricing/models___id';
import * as revenue_streams___id from '@/lib/api-handlers/pricing/revenue_streams___id';
import * as tiers___id from '@/lib/api-handlers/pricing/tiers___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["discounts"], paramNames: [], handlers: { GET: discounts.GET, POST: discounts.POST } },
  { segments: ["experiments"], paramNames: [], handlers: { GET: experiments.GET, POST: experiments.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["models"], paramNames: [], handlers: { GET: models.GET, POST: models.POST } },
  { segments: ["revenue-streams"], paramNames: [], handlers: { GET: revenue_streams.GET, POST: revenue_streams.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["tiers"], paramNames: [], handlers: { GET: tiers.GET, POST: tiers.POST } },
  { segments: ["experiments","[id]","end"], paramNames: ["id"], handlers: { POST: experiments___id__end.POST } },
  { segments: ["experiments","[id]","start"], paramNames: ["id"], handlers: { POST: experiments___id__start.POST } },
  { segments: ["discounts","[id]"], paramNames: ["id"], handlers: { GET: discounts___id.GET, PATCH: discounts___id.PATCH, DELETE: discounts___id.DELETE } },
  { segments: ["experiments","[id]"], paramNames: ["id"], handlers: { GET: experiments___id.GET, PATCH: experiments___id.PATCH } },
  { segments: ["models","[id]"], paramNames: ["id"], handlers: { GET: models___id.GET, PATCH: models___id.PATCH, DELETE: models___id.DELETE } },
  { segments: ["revenue-streams","[id]"], paramNames: ["id"], handlers: { GET: revenue_streams___id.GET, PATCH: revenue_streams___id.PATCH, DELETE: revenue_streams___id.DELETE } },
  { segments: ["tiers","[id]"], paramNames: ["id"], handlers: { GET: tiers___id.GET, PATCH: tiers___id.PATCH, DELETE: tiers___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
