/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/ip/*
 * Consolidates 18 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as assets__expiring from '@/lib/api-handlers/ip/assets__expiring';
import * as assets from '@/lib/api-handlers/ip/assets';
import * as disputes from '@/lib/api-handlers/ip/disputes';
import * as licenses from '@/lib/api-handlers/ip/licenses';
import * as metrics from '@/lib/api-handlers/ip/metrics';
import * as stats from '@/lib/api-handlers/ip/stats';
import * as trade_secrets from '@/lib/api-handlers/ip/trade_secrets';
import * as trademarks from '@/lib/api-handlers/ip/trademarks';
import * as disputes___id__appeal from '@/lib/api-handlers/ip/disputes___id__appeal';
import * as disputes___id__resolve from '@/lib/api-handlers/ip/disputes___id__resolve';
import * as licenses___id__renew from '@/lib/api-handlers/ip/licenses___id__renew';
import * as licenses___id__terminate from '@/lib/api-handlers/ip/licenses___id__terminate';
import * as trade_secrets___id__review from '@/lib/api-handlers/ip/trade_secrets___id__review';
import * as assets___id from '@/lib/api-handlers/ip/assets___id';
import * as disputes___id from '@/lib/api-handlers/ip/disputes___id';
import * as licenses___id from '@/lib/api-handlers/ip/licenses___id';
import * as trade_secrets___id from '@/lib/api-handlers/ip/trade_secrets___id';
import * as trademarks___id from '@/lib/api-handlers/ip/trademarks___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["assets","expiring"], paramNames: [], handlers: { GET: assets__expiring.GET } },
  { segments: ["assets"], paramNames: [], handlers: { GET: assets.GET, POST: assets.POST } },
  { segments: ["disputes"], paramNames: [], handlers: { GET: disputes.GET, POST: disputes.POST } },
  { segments: ["licenses"], paramNames: [], handlers: { GET: licenses.GET, POST: licenses.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["trade-secrets"], paramNames: [], handlers: { GET: trade_secrets.GET, POST: trade_secrets.POST } },
  { segments: ["trademarks"], paramNames: [], handlers: { GET: trademarks.GET, POST: trademarks.POST } },
  { segments: ["disputes","[id]","appeal"], paramNames: ["id"], handlers: { POST: disputes___id__appeal.POST } },
  { segments: ["disputes","[id]","resolve"], paramNames: ["id"], handlers: { POST: disputes___id__resolve.POST } },
  { segments: ["licenses","[id]","renew"], paramNames: ["id"], handlers: { POST: licenses___id__renew.POST } },
  { segments: ["licenses","[id]","terminate"], paramNames: ["id"], handlers: { POST: licenses___id__terminate.POST } },
  { segments: ["trade-secrets","[id]","review"], paramNames: ["id"], handlers: { POST: trade_secrets___id__review.POST } },
  { segments: ["assets","[id]"], paramNames: ["id"], handlers: { GET: assets___id.GET, PATCH: assets___id.PATCH, DELETE: assets___id.DELETE } },
  { segments: ["disputes","[id]"], paramNames: ["id"], handlers: { GET: disputes___id.GET, PATCH: disputes___id.PATCH } },
  { segments: ["licenses","[id]"], paramNames: ["id"], handlers: { GET: licenses___id.GET, PATCH: licenses___id.PATCH } },
  { segments: ["trade-secrets","[id]"], paramNames: ["id"], handlers: { GET: trade_secrets___id.GET, PATCH: trade_secrets___id.PATCH, DELETE: trade_secrets___id.DELETE } },
  { segments: ["trademarks","[id]"], paramNames: ["id"], handlers: { GET: trademarks___id.GET, PATCH: trademarks___id.PATCH, DELETE: trademarks___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
