/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/facilities/*
 * Consolidates 15 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as leases__expiring from '@/lib/api-handlers/facilities/leases__expiring';
import * as costs from '@/lib/api-handlers/facilities/costs';
import * as leases from '@/lib/api-handlers/facilities/leases';
import * as maintenance from '@/lib/api-handlers/facilities/maintenance';
import * as occupancy from '@/lib/api-handlers/facilities/occupancy';
import * as spaces from '@/lib/api-handlers/facilities/spaces';
import * as stats from '@/lib/api-handlers/facilities/stats';
import * as index from '@/lib/api-handlers/facilities/index';
import * as leases___id__terminate from '@/lib/api-handlers/facilities/leases___id__terminate';
import * as maintenance___id__assign from '@/lib/api-handlers/facilities/maintenance___id__assign';
import * as maintenance___id__complete from '@/lib/api-handlers/facilities/maintenance___id__complete';
import * as leases___id from '@/lib/api-handlers/facilities/leases___id';
import * as maintenance___id from '@/lib/api-handlers/facilities/maintenance___id';
import * as spaces___id from '@/lib/api-handlers/facilities/spaces___id';
import * as _id from '@/lib/api-handlers/facilities/_id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["leases","expiring"], paramNames: [], handlers: { GET: leases__expiring.GET } },
  { segments: ["costs"], paramNames: [], handlers: { GET: costs.GET } },
  { segments: ["leases"], paramNames: [], handlers: { GET: leases.GET, POST: leases.POST } },
  { segments: ["maintenance"], paramNames: [], handlers: { GET: maintenance.GET, POST: maintenance.POST } },
  { segments: ["occupancy"], paramNames: [], handlers: { GET: occupancy.GET } },
  { segments: ["spaces"], paramNames: [], handlers: { GET: spaces.GET, POST: spaces.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: [], paramNames: [], handlers: { GET: index.GET, POST: index.POST } },
  { segments: ["leases","[id]","terminate"], paramNames: ["id"], handlers: { POST: leases___id__terminate.POST } },
  { segments: ["maintenance","[id]","assign"], paramNames: ["id"], handlers: { POST: maintenance___id__assign.POST } },
  { segments: ["maintenance","[id]","complete"], paramNames: ["id"], handlers: { POST: maintenance___id__complete.POST } },
  { segments: ["leases","[id]"], paramNames: ["id"], handlers: { GET: leases___id.GET, PATCH: leases___id.PATCH } },
  { segments: ["maintenance","[id]"], paramNames: ["id"], handlers: { GET: maintenance___id.GET, PATCH: maintenance___id.PATCH } },
  { segments: ["spaces","[id]"], paramNames: ["id"], handlers: { PATCH: spaces___id.PATCH, DELETE: spaces___id.DELETE } },
  { segments: ["[id]"], paramNames: ["id"], handlers: { GET: _id.GET, PATCH: _id.PATCH, DELETE: _id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
