// Type declarations for lazynext-wasm (WASM package)
// Generated by wasm-pack build. In CI, the WASM package is downloaded
// from the Rust Core build job. These declarations provide type safety
// when the WASM binary isn't available during typecheck.

declare module "lazynext-wasm" {
  export class CrdtEngine {
    constructor(peerId: string);
    applyOperation(op: Record<string, unknown>): boolean;
    undo(): boolean;
    redo(): boolean;
    getOperationLog(): unknown[];
    getOperationsSince(seq: number): unknown[];
    mergeClock(clock: unknown): void;
    getClock(): unknown;
    happensBefore(other: unknown): boolean;
    isConcurrentWith(other: unknown): boolean;
    markDeleted(id: string): void;
    isDeleted(id: string): boolean;
    gcTombstones(): void;
    len(): number;
    tombstoneCount(): number;
    getPeerId(): string;
    setEntity(id: string, data: unknown): void;
    linkClipToEntity(clipId: string, entityId: string): void;
    getEntityGraph(): unknown;
  }

  export function initializeGpu(): boolean;
  export function getCompositorCanvas(): HTMLCanvasElement;
  export function applyEffectPasses(opts: {
    source: OffscreenCanvas;
    width: number;
    height: number;
    passes: Array<{
      shader: string;
      uniforms: Array<{ name: string; value: number[] }>;
    }>;
  }): OffscreenCanvas;

  export function applyMaskFeatherWasm(opts: {
    mask: OffscreenCanvas;
    width: number;
    height: number;
    feather: number;
  }): OffscreenCanvas;

  export function resolveTrackPlacement(opts: Record<string, unknown>): unknown;
  export function applyPlacement(opts: Record<string, unknown>): unknown;

  // MediaTime types
  export interface MediaTime {
    asTicks(): number;
    toSecondsF64(): number;
  }

  export interface FrameRate {
    ticksPerFrame(): number | null;
    asF64(): number;
  }

  // NLE State
  export class NLEState {
    constructor(sessionId: string, projectName: string, framerate: number);
    addTrack(id: string, kind: string): void;
    getProjectData(): unknown;
    loadProjectData(data: unknown): void;
    play(): void;
    pause(): void;
    setFrame(frame: number): void;
    getFrame(): number;
    getIsPlaying(): boolean;
    updateClip(trackIdx: number, clipId: string, data: unknown): void;
    splitClip(trackIdx: number, clipId: string, splitFrame: number): void;
    trimClip(trackIdx: number, clipId: string, start: number, end: number): void;
  }

  export function mediaTimeFromSeconds(opts: { seconds: number }): MediaTime | null;
  export function mediaTimeToSeconds(opts: { time: MediaTime }): number;
  export function mediaTimeFromFrame(opts: { frame: number; rate: FrameRate }): MediaTime | null;
  export function mediaTimeToFrame(opts: { time: MediaTime; rate: FrameRate }): number | null;
  export function roundToFrame(opts: { time: MediaTime; rate: FrameRate }): MediaTime | null;
  export function floorToFrame(opts: { time: MediaTime; rate: FrameRate }): MediaTime | null;
  export function isFrameAligned(opts: { time: MediaTime; rate: FrameRate }): boolean | null;
  export function mediaTimeAdd(a: MediaTime, b: MediaTime): MediaTime;
  export function mediaTimeSub(a: MediaTime, b: MediaTime): MediaTime;
  export function mediaTimeMin(a: MediaTime, b: MediaTime): MediaTime;
  export function mediaTimeMax(a: MediaTime, b: MediaTime): MediaTime;
  export function mediaTimeClamp(t: MediaTime, min: MediaTime, max: MediaTime): MediaTime;

  export function evaluateScalarChannel(opts: Record<string, unknown>): number;
  export function prepareExportManifest(opts: Record<string, unknown>): string;
  export function buildAafManifest(opts: Record<string, unknown>): string;
  export function buildDcpCpl(opts: Record<string, unknown>): string;

  // Compositor
  export function initCompositor(width: number, height: number): boolean;
  export function resizeCompositor(width: number, height: number): void;
  export function getCompositorCanvas(): HTMLCanvasElement | null;
  export function uploadTexture(id: string, texture: unknown): void;
  export function releaseTexture(id: string): void;
  export function renderFrame(descriptor: unknown): unknown;
  export function renderProjectFrame(config: unknown): unknown;

  // Audio
  export function processAudioBuffer(buffer: Float32Array): Float32Array;
  export function applyParametricEq(opts: Record<string, unknown>): Float32Array;
  export function applyCompressor(opts: Record<string, unknown>): Float32Array;

  // Neural
  export function initNeuralEngine(): void;
  export function detectFaces(frame: Uint8Array, width: number, height: number): unknown;
}
