/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/engineering-management/*
 * Consolidates 12 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as health from '@/lib/api-handlers/engineering-management/health';
import * as metrics from '@/lib/api-handlers/engineering-management/metrics';
import * as metrics_summary from '@/lib/api-handlers/engineering-management/metrics_summary';
import * as quality from '@/lib/api-handlers/engineering-management/quality';
import * as sprints from '@/lib/api-handlers/engineering-management/sprints';
import * as stats from '@/lib/api-handlers/engineering-management/stats';
import * as sprints___id__complete from '@/lib/api-handlers/engineering-management/sprints___id__complete';
import * as sprints___id__start from '@/lib/api-handlers/engineering-management/sprints___id__start';
import * as health___id from '@/lib/api-handlers/engineering-management/health___id';
import * as metrics___id from '@/lib/api-handlers/engineering-management/metrics___id';
import * as quality___id from '@/lib/api-handlers/engineering-management/quality___id';
import * as sprints___id from '@/lib/api-handlers/engineering-management/sprints___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["health"], paramNames: [], handlers: { GET: health.GET, POST: health.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET, POST: metrics.POST } },
  { segments: ["metrics-summary"], paramNames: [], handlers: { GET: metrics_summary.GET } },
  { segments: ["quality"], paramNames: [], handlers: { GET: quality.GET, POST: quality.POST } },
  { segments: ["sprints"], paramNames: [], handlers: { GET: sprints.GET, POST: sprints.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["sprints","[id]","complete"], paramNames: ["id"], handlers: { POST: sprints___id__complete.POST } },
  { segments: ["sprints","[id]","start"], paramNames: ["id"], handlers: { POST: sprints___id__start.POST } },
  { segments: ["health","[id]"], paramNames: ["id"], handlers: { GET: health___id.GET, PATCH: health___id.PATCH, DELETE: health___id.DELETE } },
  { segments: ["metrics","[id]"], paramNames: ["id"], handlers: { GET: metrics___id.GET, PATCH: metrics___id.PATCH, DELETE: metrics___id.DELETE } },
  { segments: ["quality","[id]"], paramNames: ["id"], handlers: { GET: quality___id.GET, PATCH: quality___id.PATCH, DELETE: quality___id.DELETE } },
  { segments: ["sprints","[id]"], paramNames: ["id"], handlers: { GET: sprints___id.GET, PATCH: sprints___id.PATCH, DELETE: sprints___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path?: string[] }> },
) {
  const { path = [] } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
