import { randomUUID } from 'crypto'

/**
 * Shared response-header builder for the public REST API.
 *
 * Every `/api/v1/*` route should emit a consistent contract:
 *  - `X-Request-Id`     — uuid, propagated to Sentry, quotable in support
 *  - `X-API-Version`    — `v1` for the current surface
 *  - `X-RateLimit-*`    — when a rate-limit decision was made on this request
 *  - `Retry-After`      — only on 429 responses
 *  - `Sunset` /         — only on responses for endpoints scheduled for
 *    `Deprecation` /      removal. Stripe-style: ≥6-month window.
 *    `Link`
 *
 * Intentionally pure: no IO, no DB, no globals. Routes import this
 * and call it inline. Tested in `tests/unit/api-headers.test.ts`.
 *
 * Background and contract:
 *   - `Sunset` follows IETF RFC 8594 (HTTP-date timestamp, removal date)
 *   - `Deprecation` follows draft-ietf-httpapi-deprecation-header
 *     (RFC-3339 / unix timestamp prefixed with `@`)
 *   - `Link` carries `rel="deprecation"` to the changelog page
 */

export type ApiVersion = 'v1' | 'v2'

export interface RateLimitInfo {
  /** Maximum requests allowed in the current window. */
  limit: number
  /** Requests remaining in the current window. */
  remaining: number
  /** Unix-seconds when the window resets. */
  resetAtSec: number
}

export interface DeprecationInfo {
  /** When the endpoint will stop responding. Must be ≥6 months in the future per project policy. */
  sunsetDate: Date
  /** When the endpoint became deprecated (informational; not a 4xx trigger). */
  deprecationDate: Date
  /** URL of the migration / changelog entry the consumer should read. */
  link: string
}

export interface BuildResponseHeadersInput {
  /**
   * Stable identifier for this request. Generated by `newRequestId()`
   * if you don't have one already. Threading the same id from auth
   * resolution → handler → response is the goal so logs and the
   * `X-Request-Id` header agree.
   */
  requestId: string
  /** Defaults to `'v1'` — the only currently-shipping version. */
  apiVersion?: ApiVersion
  /** Set on responses where a rate-limit decision was made (allowed OR rejected). */
  rateLimit?: RateLimitInfo
  /**
   * Seconds the client must wait before retrying. Set ONLY on 429
   * responses. Caller is responsible for the 429 status code itself.
   */
  retryAfterSec?: number
  /** Set on endpoints scheduled for removal. Adds `Sunset` + `Deprecation` + `Link`. */
  deprecation?: DeprecationInfo
}

/**
 * Generate a fresh request id. Caller should use this once per inbound
 * request and propagate the same value to logs, error reporting, and
 * the response header.
 */
export function newRequestId(): string {
  return randomUUID()
}

/**
 * Build the standard response-header set. Returns a `Headers` instance
 * that the caller merges with route-specific headers (`Content-Type`
 * etc.) before constructing the `Response`.
 */
export function buildResponseHeaders(input: BuildResponseHeadersInput): Headers {
  const headers = new Headers()
  headers.set('X-Request-Id', input.requestId)
  headers.set('X-API-Version', input.apiVersion ?? 'v1')

  if (input.rateLimit) {
    headers.set('X-RateLimit-Limit', String(input.rateLimit.limit))
    headers.set('X-RateLimit-Remaining', String(Math.max(0, input.rateLimit.remaining)))
    headers.set('X-RateLimit-Reset', String(input.rateLimit.resetAtSec))
  }

  if (typeof input.retryAfterSec === 'number' && input.retryAfterSec > 0) {
    headers.set('Retry-After', String(Math.ceil(input.retryAfterSec)))
  }

  if (input.deprecation) {
    // RFC 8594: Sunset is an HTTP-date.
    headers.set('Sunset', input.deprecation.sunsetDate.toUTCString())
    // draft-ietf-httpapi-deprecation-header: `@<unix-seconds>`.
    const depSec = Math.floor(input.deprecation.deprecationDate.getTime() / 1000)
    headers.set('Deprecation', `@${depSec}`)
    headers.set('Link', `<${input.deprecation.link}>; rel="deprecation"`)
  }

  return headers
}

/**
 * Convenience: merge a `Headers` instance into a plain `HeadersInit`
 * record so callers using `NextResponse.json(body, { headers: {...} })`
 * can spread the contract headers in without repeating the loop.
 */
export function headersToObject(headers: Headers): Record<string, string> {
  const out: Record<string, string> = {}
  headers.forEach((value, key) => {
    out[key] = value
  })
  return out
}
