/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/learning/*
 * Consolidates 8 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as adjust_goal from '@/lib/api-handlers/learning/adjust_goal';
import * as cycle from '@/lib/api-handlers/learning/cycle';
import * as dashboard from '@/lib/api-handlers/learning/dashboard';
import * as evaluate from '@/lib/api-handlers/learning/evaluate';
import * as history from '@/lib/api-handlers/learning/history';
import * as insights from '@/lib/api-handlers/learning/insights';
import * as recommendations from '@/lib/api-handlers/learning/recommendations';
import * as reprioritize from '@/lib/api-handlers/learning/reprioritize';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["adjust-goal"], paramNames: [], handlers: { POST: adjust_goal.POST } },
  { segments: ["cycle"], paramNames: [], handlers: { POST: cycle.POST } },
  { segments: ["dashboard"], paramNames: [], handlers: { GET: dashboard.GET } },
  { segments: ["evaluate"], paramNames: [], handlers: { POST: evaluate.POST } },
  { segments: ["history"], paramNames: [], handlers: { GET: history.GET } },
  { segments: ["insights"], paramNames: [], handlers: { GET: insights.GET } },
  { segments: ["recommendations"], paramNames: [], handlers: { GET: recommendations.GET } },
  { segments: ["reprioritize"], paramNames: [], handlers: { POST: reprioritize.POST } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
