/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/management-succession/*
 * Consolidates 27 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as candidates from '@/lib/api-handlers/management-succession/candidates';
import * as metrics from '@/lib/api-handlers/management-succession/metrics';
import * as plans from '@/lib/api-handlers/management-succession/plans';
import * as reviews from '@/lib/api-handlers/management-succession/reviews';
import * as stats from '@/lib/api-handlers/management-succession/stats';
import * as tracks from '@/lib/api-handlers/management-succession/tracks';
import * as candidates___id__develop from '@/lib/api-handlers/management-succession/candidates___id__develop';
import * as candidates___id__not_ready from '@/lib/api-handlers/management-succession/candidates___id__not_ready';
import * as candidates___id__place from '@/lib/api-handlers/management-succession/candidates___id__place';
import * as candidates___id__ready from '@/lib/api-handlers/management-succession/candidates___id__ready';
import * as candidates___id__ready_now from '@/lib/api-handlers/management-succession/candidates___id__ready_now';
import * as candidates___id__withdraw from '@/lib/api-handlers/management-succession/candidates___id__withdraw';
import * as plans___id__activate from '@/lib/api-handlers/management-succession/plans___id__activate';
import * as plans___id__approve from '@/lib/api-handlers/management-succession/plans___id__approve';
import * as plans___id__archive from '@/lib/api-handlers/management-succession/plans___id__archive';
import * as plans___id__execute from '@/lib/api-handlers/management-succession/plans___id__execute';
import * as plans___id__review from '@/lib/api-handlers/management-succession/plans___id__review';
import * as reviews___id__complete from '@/lib/api-handlers/management-succession/reviews___id__complete';
import * as reviews___id__overdue from '@/lib/api-handlers/management-succession/reviews___id__overdue';
import * as reviews___id__start from '@/lib/api-handlers/management-succession/reviews___id__start';
import * as tracks___id__complete from '@/lib/api-handlers/management-succession/tracks___id__complete';
import * as tracks___id__pause from '@/lib/api-handlers/management-succession/tracks___id__pause';
import * as tracks___id__start from '@/lib/api-handlers/management-succession/tracks___id__start';
import * as candidates___id from '@/lib/api-handlers/management-succession/candidates___id';
import * as plans___id from '@/lib/api-handlers/management-succession/plans___id';
import * as reviews___id from '@/lib/api-handlers/management-succession/reviews___id';
import * as tracks___id from '@/lib/api-handlers/management-succession/tracks___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["candidates"], paramNames: [], handlers: { GET: candidates.GET, POST: candidates.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["plans"], paramNames: [], handlers: { GET: plans.GET, POST: plans.POST } },
  { segments: ["reviews"], paramNames: [], handlers: { GET: reviews.GET, POST: reviews.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["tracks"], paramNames: [], handlers: { GET: tracks.GET, POST: tracks.POST } },
  { segments: ["candidates","[id]","develop"], paramNames: ["id"], handlers: { POST: candidates___id__develop.POST } },
  { segments: ["candidates","[id]","not-ready"], paramNames: ["id"], handlers: { POST: candidates___id__not_ready.POST } },
  { segments: ["candidates","[id]","place"], paramNames: ["id"], handlers: { POST: candidates___id__place.POST } },
  { segments: ["candidates","[id]","ready"], paramNames: ["id"], handlers: { POST: candidates___id__ready.POST } },
  { segments: ["candidates","[id]","ready-now"], paramNames: ["id"], handlers: { POST: candidates___id__ready_now.POST } },
  { segments: ["candidates","[id]","withdraw"], paramNames: ["id"], handlers: { POST: candidates___id__withdraw.POST } },
  { segments: ["plans","[id]","activate"], paramNames: ["id"], handlers: { POST: plans___id__activate.POST } },
  { segments: ["plans","[id]","approve"], paramNames: ["id"], handlers: { POST: plans___id__approve.POST } },
  { segments: ["plans","[id]","archive"], paramNames: ["id"], handlers: { POST: plans___id__archive.POST } },
  { segments: ["plans","[id]","execute"], paramNames: ["id"], handlers: { POST: plans___id__execute.POST } },
  { segments: ["plans","[id]","review"], paramNames: ["id"], handlers: { POST: plans___id__review.POST } },
  { segments: ["reviews","[id]","complete"], paramNames: ["id"], handlers: { POST: reviews___id__complete.POST } },
  { segments: ["reviews","[id]","overdue"], paramNames: ["id"], handlers: { POST: reviews___id__overdue.POST } },
  { segments: ["reviews","[id]","start"], paramNames: ["id"], handlers: { POST: reviews___id__start.POST } },
  { segments: ["tracks","[id]","complete"], paramNames: ["id"], handlers: { POST: tracks___id__complete.POST } },
  { segments: ["tracks","[id]","pause"], paramNames: ["id"], handlers: { POST: tracks___id__pause.POST } },
  { segments: ["tracks","[id]","start"], paramNames: ["id"], handlers: { POST: tracks___id__start.POST } },
  { segments: ["candidates","[id]"], paramNames: ["id"], handlers: { GET: candidates___id.GET, PATCH: candidates___id.PATCH, DELETE: candidates___id.DELETE } },
  { segments: ["plans","[id]"], paramNames: ["id"], handlers: { GET: plans___id.GET, PATCH: plans___id.PATCH, DELETE: plans___id.DELETE } },
  { segments: ["reviews","[id]"], paramNames: ["id"], handlers: { GET: reviews___id.GET, PATCH: reviews___id.PATCH, DELETE: reviews___id.DELETE } },
  { segments: ["tracks","[id]"], paramNames: ["id"], handlers: { GET: tracks___id.GET, PATCH: tracks___id.PATCH, DELETE: tracks___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
