/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/internal-audit/*
 * Consolidates 20 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as findings from '@/lib/api-handlers/internal-audit/findings';
import * as metrics from '@/lib/api-handlers/internal-audit/metrics';
import * as plans from '@/lib/api-handlers/internal-audit/plans';
import * as remediations from '@/lib/api-handlers/internal-audit/remediations';
import * as schedules from '@/lib/api-handlers/internal-audit/schedules';
import * as stats from '@/lib/api-handlers/internal-audit/stats';
import * as findings___id__accept_risk from '@/lib/api-handlers/internal-audit/findings___id__accept_risk';
import * as findings___id__remediate from '@/lib/api-handlers/internal-audit/findings___id__remediate';
import * as findings___id__verify from '@/lib/api-handlers/internal-audit/findings___id__verify';
import * as plans___id__complete from '@/lib/api-handlers/internal-audit/plans___id__complete';
import * as plans___id__start from '@/lib/api-handlers/internal-audit/plans___id__start';
import * as remediations___id__complete from '@/lib/api-handlers/internal-audit/remediations___id__complete';
import * as remediations___id__start from '@/lib/api-handlers/internal-audit/remediations___id__start';
import * as remediations___id__verify from '@/lib/api-handlers/internal-audit/remediations___id__verify';
import * as schedules___id__complete from '@/lib/api-handlers/internal-audit/schedules___id__complete';
import * as schedules___id__postpone from '@/lib/api-handlers/internal-audit/schedules___id__postpone';
import * as findings___id from '@/lib/api-handlers/internal-audit/findings___id';
import * as plans___id from '@/lib/api-handlers/internal-audit/plans___id';
import * as remediations___id from '@/lib/api-handlers/internal-audit/remediations___id';
import * as schedules___id from '@/lib/api-handlers/internal-audit/schedules___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["findings"], paramNames: [], handlers: { GET: findings.GET, POST: findings.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["plans"], paramNames: [], handlers: { GET: plans.GET, POST: plans.POST } },
  { segments: ["remediations"], paramNames: [], handlers: { GET: remediations.GET, POST: remediations.POST } },
  { segments: ["schedules"], paramNames: [], handlers: { GET: schedules.GET, POST: schedules.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["findings","[id]","accept-risk"], paramNames: ["id"], handlers: { POST: findings___id__accept_risk.POST } },
  { segments: ["findings","[id]","remediate"], paramNames: ["id"], handlers: { POST: findings___id__remediate.POST } },
  { segments: ["findings","[id]","verify"], paramNames: ["id"], handlers: { POST: findings___id__verify.POST } },
  { segments: ["plans","[id]","complete"], paramNames: ["id"], handlers: { POST: plans___id__complete.POST } },
  { segments: ["plans","[id]","start"], paramNames: ["id"], handlers: { POST: plans___id__start.POST } },
  { segments: ["remediations","[id]","complete"], paramNames: ["id"], handlers: { POST: remediations___id__complete.POST } },
  { segments: ["remediations","[id]","start"], paramNames: ["id"], handlers: { POST: remediations___id__start.POST } },
  { segments: ["remediations","[id]","verify"], paramNames: ["id"], handlers: { POST: remediations___id__verify.POST } },
  { segments: ["schedules","[id]","complete"], paramNames: ["id"], handlers: { POST: schedules___id__complete.POST } },
  { segments: ["schedules","[id]","postpone"], paramNames: ["id"], handlers: { POST: schedules___id__postpone.POST } },
  { segments: ["findings","[id]"], paramNames: ["id"], handlers: { GET: findings___id.GET, PATCH: findings___id.PATCH } },
  { segments: ["plans","[id]"], paramNames: ["id"], handlers: { GET: plans___id.GET, PATCH: plans___id.PATCH, DELETE: plans___id.DELETE } },
  { segments: ["remediations","[id]"], paramNames: ["id"], handlers: { GET: remediations___id.GET, PATCH: remediations___id.PATCH } },
  { segments: ["schedules","[id]"], paramNames: ["id"], handlers: { GET: schedules___id.GET, PATCH: schedules___id.PATCH } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
