/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/calendar/*
 * Consolidates 18 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as availability from '@/lib/api-handlers/calendar/availability';
import * as day from '@/lib/api-handlers/calendar/day';
import * as deadlines from '@/lib/api-handlers/calendar/deadlines';
import * as events from '@/lib/api-handlers/calendar/events';
import * as free_slots from '@/lib/api-handlers/calendar/free_slots';
import * as gantt from '@/lib/api-handlers/calendar/gantt';
import * as month from '@/lib/api-handlers/calendar/month';
import * as resources from '@/lib/api-handlers/calendar/resources';
import * as stats from '@/lib/api-handlers/calendar/stats';
import * as upcoming from '@/lib/api-handlers/calendar/upcoming';
import * as week from '@/lib/api-handlers/calendar/week';
import * as events___id__attendees from '@/lib/api-handlers/calendar/events___id__attendees';
import * as events___id__cancel from '@/lib/api-handlers/calendar/events___id__cancel';
import * as events___id__respond from '@/lib/api-handlers/calendar/events___id__respond';
import * as resources___id__availability from '@/lib/api-handlers/calendar/resources___id__availability';
import * as resources___id__bookings from '@/lib/api-handlers/calendar/resources___id__bookings';
import * as events___id from '@/lib/api-handlers/calendar/events___id';
import * as resources___id from '@/lib/api-handlers/calendar/resources___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["availability"], paramNames: [], handlers: { POST: availability.POST } },
  { segments: ["day"], paramNames: [], handlers: { GET: day.GET } },
  { segments: ["deadlines"], paramNames: [], handlers: { GET: deadlines.GET } },
  { segments: ["events"], paramNames: [], handlers: { GET: events.GET, POST: events.POST } },
  { segments: ["free-slots"], paramNames: [], handlers: { POST: free_slots.POST } },
  { segments: ["gantt"], paramNames: [], handlers: { GET: gantt.GET } },
  { segments: ["month"], paramNames: [], handlers: { GET: month.GET } },
  { segments: ["resources"], paramNames: [], handlers: { GET: resources.GET, POST: resources.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["upcoming"], paramNames: [], handlers: { GET: upcoming.GET } },
  { segments: ["week"], paramNames: [], handlers: { GET: week.GET } },
  { segments: ["events","[id]","attendees"], paramNames: ["id"], handlers: { GET: events___id__attendees.GET, POST: events___id__attendees.POST, DELETE: events___id__attendees.DELETE } },
  { segments: ["events","[id]","cancel"], paramNames: ["id"], handlers: { POST: events___id__cancel.POST } },
  { segments: ["events","[id]","respond"], paramNames: ["id"], handlers: { POST: events___id__respond.POST } },
  { segments: ["resources","[id]","availability"], paramNames: ["id"], handlers: { GET: resources___id__availability.GET } },
  { segments: ["resources","[id]","bookings"], paramNames: ["id"], handlers: { GET: resources___id__bookings.GET } },
  { segments: ["events","[id]"], paramNames: ["id"], handlers: { GET: events___id.GET, PATCH: events___id.PATCH, DELETE: events___id.DELETE } },
  { segments: ["resources","[id]"], paramNames: ["id"], handlers: { GET: resources___id.GET, PATCH: resources___id.PATCH, DELETE: resources___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
