/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/performance-management/*
 * Consolidates 22 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as feedback from '@/lib/api-handlers/performance-management/feedback';
import * as goals from '@/lib/api-handlers/performance-management/goals';
import * as metrics from '@/lib/api-handlers/performance-management/metrics';
import * as plans from '@/lib/api-handlers/performance-management/plans';
import * as reviews from '@/lib/api-handlers/performance-management/reviews';
import * as stats from '@/lib/api-handlers/performance-management/stats';
import * as feedback___id__acknowledge from '@/lib/api-handlers/performance-management/feedback___id__acknowledge';
import * as feedback___id__action from '@/lib/api-handlers/performance-management/feedback___id__action';
import * as feedback___id__deliver from '@/lib/api-handlers/performance-management/feedback___id__deliver';
import * as goals___id__achieve from '@/lib/api-handlers/performance-management/goals___id__achieve';
import * as goals___id__miss from '@/lib/api-handlers/performance-management/goals___id__miss';
import * as goals___id__start from '@/lib/api-handlers/performance-management/goals___id__start';
import * as plans___id__activate from '@/lib/api-handlers/performance-management/plans___id__activate';
import * as plans___id__complete from '@/lib/api-handlers/performance-management/plans___id__complete';
import * as plans___id__hold from '@/lib/api-handlers/performance-management/plans___id__hold';
import * as reviews___id__complete from '@/lib/api-handlers/performance-management/reviews___id__complete';
import * as reviews___id__send from '@/lib/api-handlers/performance-management/reviews___id__send';
import * as reviews___id__submit from '@/lib/api-handlers/performance-management/reviews___id__submit';
import * as feedback___id from '@/lib/api-handlers/performance-management/feedback___id';
import * as goals___id from '@/lib/api-handlers/performance-management/goals___id';
import * as plans___id from '@/lib/api-handlers/performance-management/plans___id';
import * as reviews___id from '@/lib/api-handlers/performance-management/reviews___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["feedback"], paramNames: [], handlers: { GET: feedback.GET, POST: feedback.POST } },
  { segments: ["goals"], paramNames: [], handlers: { GET: goals.GET, POST: goals.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["plans"], paramNames: [], handlers: { GET: plans.GET, POST: plans.POST } },
  { segments: ["reviews"], paramNames: [], handlers: { GET: reviews.GET, POST: reviews.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["feedback","[id]","acknowledge"], paramNames: ["id"], handlers: { POST: feedback___id__acknowledge.POST } },
  { segments: ["feedback","[id]","action"], paramNames: ["id"], handlers: { POST: feedback___id__action.POST } },
  { segments: ["feedback","[id]","deliver"], paramNames: ["id"], handlers: { POST: feedback___id__deliver.POST } },
  { segments: ["goals","[id]","achieve"], paramNames: ["id"], handlers: { POST: goals___id__achieve.POST } },
  { segments: ["goals","[id]","miss"], paramNames: ["id"], handlers: { POST: goals___id__miss.POST } },
  { segments: ["goals","[id]","start"], paramNames: ["id"], handlers: { POST: goals___id__start.POST } },
  { segments: ["plans","[id]","activate"], paramNames: ["id"], handlers: { POST: plans___id__activate.POST } },
  { segments: ["plans","[id]","complete"], paramNames: ["id"], handlers: { POST: plans___id__complete.POST } },
  { segments: ["plans","[id]","hold"], paramNames: ["id"], handlers: { POST: plans___id__hold.POST } },
  { segments: ["reviews","[id]","complete"], paramNames: ["id"], handlers: { POST: reviews___id__complete.POST } },
  { segments: ["reviews","[id]","send"], paramNames: ["id"], handlers: { POST: reviews___id__send.POST } },
  { segments: ["reviews","[id]","submit"], paramNames: ["id"], handlers: { POST: reviews___id__submit.POST } },
  { segments: ["feedback","[id]"], paramNames: ["id"], handlers: { GET: feedback___id.GET, PATCH: feedback___id.PATCH, DELETE: feedback___id.DELETE } },
  { segments: ["goals","[id]"], paramNames: ["id"], handlers: { GET: goals___id.GET, PATCH: goals___id.PATCH, DELETE: goals___id.DELETE } },
  { segments: ["plans","[id]"], paramNames: ["id"], handlers: { GET: plans___id.GET, PATCH: plans___id.PATCH, DELETE: plans___id.DELETE } },
  { segments: ["reviews","[id]"], paramNames: ["id"], handlers: { GET: reviews___id.GET, PATCH: reviews___id.PATCH, DELETE: reviews___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
