/**
 * Mock Atlas Cloud API server for local development.
 *
 * Run with: node scripts/mock-atlas.mjs
 *
 * Set these env vars in .env.local to redirect Atlas calls here:
 *   ATLASCLOUD_BASE=http://localhost:3099/api/v1
 *   ATLASCLOUD_LLM_BASE=http://localhost:3099/v1
 *   ATLASCLOUD_API_KEY=mock-key-for-dev
 *
 * Endpoints:
 *   POST /api/v1/model/uploadMedia       → returns { data: { download_url } }
 *   POST /api/v1/model/generateImage     → returns { code: 200, data: { id, urls: { get } } }
 *   POST /api/v1/model/generateVideo     → same
 *   POST /api/v1/model/generateAudio     → same
 *   GET  /api/v1/model/prediction/:id    → returns { data: { status, outputs } }
 *   POST /v1/chat/completions            → returns { choices: [{ message: { content } }] }
 *
 * Tasks transition: pending → processing → completed (after ~3 polls).
 * Generated outputs are small placeholder data URIs (1x1 pixel PNG / empty mp4).
 */
import { createServer } from 'http';
import { randomUUID } from 'crypto';
import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const PORT = Number(process.env.MOCK_ATLAS_PORT || 3099);
const __dirname = dirname(fileURLToPath(import.meta.url));
const MOCK_MEDIA_DIR = join(__dirname, '..', '.dev-media');
mkdirSync(MOCK_MEDIA_DIR, { recursive: true });

// In-memory task store: id → { status, outputs, error, createdAt, pollCount }
const tasks = new Map();

// Load real media files generated by ffmpeg (valid, browser-playable formats)
// Falls back to minimal byte buffers if the files don't exist
const PLACEHOLDER_PNG = existsSync(join(__dirname, 'mock-placeholder.png'))
  ? readFileSync(join(__dirname, 'mock-placeholder.png'))
  : Buffer.from(
      'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
      'base64',
    );

const PLACEHOLDER_MP4 = existsSync(join(__dirname, 'mock-placeholder.mp4'))
  ? readFileSync(join(__dirname, 'mock-placeholder.mp4'))
  : Buffer.from([
      0x00, 0x00, 0x00, 0x18, 0x66, 0x74, 0x79, 0x70, 0x6d, 0x70, 0x34, 0x32,
      0x00, 0x00, 0x00, 0x00, 0x6d, 0x70, 0x34, 0x32, 0x69, 0x73, 0x6f, 0x6d,
    ]);

const PLACEHOLDER_WAV = existsSync(join(__dirname, 'mock-placeholder.wav'))
  ? readFileSync(join(__dirname, 'mock-placeholder.wav'))
  : Buffer.from([
      0x52, 0x49, 0x46, 0x46, 0x24, 0x00, 0x00, 0x00, 0x57, 0x41, 0x56, 0x45,
      0x66, 0x6d, 0x74, 0x20, 0x10, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00,
      0x44, 0xac, 0x00, 0x00, 0x88, 0x58, 0x01, 0x00, 0x02, 0x00, 0x10, 0x00,
      0x64, 0x61, 0x74, 0x61, 0x00, 0x00, 0x00, 0x00,
    ]);

function servePlaceholder(req, res, type) {
  let buf, ct;
  if (type === 'image') {
    buf = PLACEHOLDER_PNG;
    ct = 'image/png';
  } else if (type === 'video') {
    buf = PLACEHOLDER_MP4;
    ct = 'video/mp4';
  } else {
    buf = PLACEHOLDER_WAV;
    ct = 'audio/wav';
  }
  res.writeHead(200, {
    'Content-Type': ct,
    'Content-Length': buf.length,
    'Access-Control-Allow-Origin': '*',
    'Cache-Control': 'no-store',
  });
  res.end(buf);
}

function jsonBody(req) {
  return new Promise((resolve) => {
    let data = '';
    req.on('data', (chunk) => (data += chunk));
    req.on('end', () => {
      try {
        resolve(data ? JSON.parse(data) : {});
      } catch {
        resolve({});
      }
    });
  });
}

function readFormBody(req) {
  return new Promise((resolve) => {
    const chunks = [];
    req.on('data', (chunk) => chunks.push(chunk));
    req.on('end', () => {
      resolve(Buffer.concat(chunks));
    });
  });
}

const server = createServer(async (req, res) => {
  // CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Headers', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  if (req.method === 'OPTIONS') {
    res.writeHead(204);
    res.end();
    return;
  }

  const url = new URL(req.url, `http://localhost:${PORT}`);
  const path = url.pathname;

  // --- Serve placeholder media files ---
  if (path.startsWith('/mock-media/')) {
    const parts = path.split('/');
    const type = parts[2]; // image | video | audio
    servePlaceholder(req, res, type);
    return;
  }

  // --- Upload media ---
  if (path === '/api/v1/model/uploadMedia' && req.method === 'POST') {
    // Just return a mock URL — don't actually store the upload
    const mockUrl = `http://localhost:${PORT}/mock-media/image/${randomUUID()}`;
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ data: { download_url: mockUrl, url: mockUrl } }));
    return;
  }

  // --- Generate (image/video/audio) ---
  if (
    path.match(/^\/api\/v1\/model\/(generateImage|generateVideo|generateAudio)$/) &&
    req.method === 'POST'
  ) {
    const body = await jsonBody(req);
    const id = randomUUID();
    const endpoint = path.split('/').pop();
    const mediaType = endpoint === 'generateImage' ? 'image' : endpoint === 'generateVideo' ? 'video' : 'audio';
    // Special trigger: if the prompt contains "FAIL_TEST", the task will transition to "failed" instead of "completed"
    const shouldFail = typeof body.prompt === 'string' && body.prompt.includes('FAIL_TEST');

    // Store task with initial pending state
    tasks.set(id, {
      status: 'pending',
      outputs: [],
      error: null,
      createdAt: Date.now(),
      pollCount: 0,
      mediaType,
      model: body.model || 'unknown',
      shouldFail,
    });

    const getUrl = `http://localhost:${PORT}/api/v1/model/prediction/${id}`;
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      code: 200,
      data: { id, urls: { get: getUrl } },
    }));
    return;
  }

  // --- Poll task status ---
  const predMatch = path.match(/^\/api\/v1\/model\/prediction\/(.+)$/);
  if (predMatch && req.method === 'GET') {
    const id = predMatch[1];
    const task = tasks.get(id);
    if (!task) {
      res.writeHead(404, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'task not found' }));
      return;
    }

    task.pollCount++;
    // Transition: pending (1 poll) → processing (2 polls) → completed/failed (3+ polls)
    if (task.pollCount >= 3) {
      if (task.shouldFail) {
        task.status = 'failed';
        task.error = 'Mock simulated generation failure (FAIL_TEST trigger)';
      } else {
        task.status = 'completed';
        const mediaUrl = `http://localhost:${PORT}/mock-media/${task.mediaType}/${randomUUID()}`;
        task.outputs = [mediaUrl];
      }
    } else if (task.pollCount >= 1) {
      task.status = 'processing';
    }

    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      data: {
        status: task.status,
        outputs: task.outputs,
        error: task.error,
      },
    }));
    return;
  }

  // --- Chat completions (LLM) ---
  if (path === '/v1/chat/completions' && req.method === 'POST') {
    const body = await jsonBody(req);

    // Generate a realistic response based on the messages
    const userMsg = body.messages?.find((m) => m.role === 'user');
    const systemMsg = body.messages?.find((m) => m.role === 'system');

    let content = '';
    if (systemMsg?.content?.includes?.('UGC video-ad prompt writer')) {
      // AI Expand prompt response
      content = 'A close-up shot of the product on a clean white surface, soft natural lighting. The presenter, a young woman with a warm smile, picks up the product and holds it toward the camera. She demonstrates the product naturally, showing its texture and quality. The scene is bright and inviting with a cozy home background. "Hey everyone, I just had to share this with you — it has honestly changed my daily routine for the better!"';
    } else if (systemMsg?.content?.includes?.('产品广告分镜师')) {
      // Marketing plan response — must return JSON with title, ratio, product, character, scene, shots
      content = JSON.stringify({
        title: 'Glow Serum UGC Ad',
        ratio: '9:16',
        product: 'A premium vitamin C serum in a 30ml amber glass dropper bottle with a minimalist white label, golden liquid visible inside',
        character: 'A young woman in her mid-20s with long brown hair, wearing a cozy cream sweater, natural makeup, warm and approachable smile',
        scene: 'A bright modern bathroom with natural daylight, white marble countertop, green plants in the background',
        shots: [
          { i: 1, shot: 'medium selfie shot holding product up toward camera', prompt: 'A young woman holds up the amber glass serum bottle toward the camera with a big smile. "Okay, I have to tell you about this serum — it changed my skin!" handheld selfie UGC feel, clear spoken English.' },
          { i: 2, shot: 'close-up of product being applied', prompt: 'Close-up of the amber dropper bottle dispensing a few drops of golden serum onto fingertips. The serum has a luxurious golden glow. "Just a few drops every morning and evening." handheld selfie UGC feel, clear spoken English.' },
          { i: 3, shot: 'close-up of glowing skin', prompt: 'Close-up of the woman cheek showing radiant glowing skin after applying the serum. "Look at this glow — two weeks and my dark spots are gone!" handheld selfie UGC feel, clear spoken English.' },
        ],
      });
    } else if (systemMsg?.content?.includes?.('短剧编剧') || systemMsg?.content?.includes?.('你是顶级爆款短视频广告创意导演')) {
      // Drama script response — must return JSON with title, logline, characters, segments, etc.
      content = JSON.stringify({
        title: 'The Tissue Hero',
        logline: 'A shy programmer saves dinner with his picky future mother-in-law using a pack of tissues.',
        sellingPoints: ['Soft and strong tissues', 'Saves awkward moments'],
        characters: [
          { key: 'char_a', name: 'Xiao Ming', persona: 'A shy but clever programmer who overthinks everything', appearance: 'A tall thin young man in his late 20s with messy black hair, glasses, a blue plaid shirt and khaki pants, nervous expression, holding a laptop bag' },
          { key: 'char_b', name: 'Mother Wang', persona: 'A sharp-tongued elegant woman who judges everyone', appearance: 'An elegant woman in her 50s with short permed hair, wearing a silk cheongsam dress in dark green, pearl earrings, critical expression' },
        ],
        setting: 'A fancy Chinese restaurant, private dining room with round table',
        sceneImagePrompt: 'A luxurious Chinese restaurant private dining room with a large round table, red tablecloth, warm golden lighting, tea set, no people, cinematic establishing shot',
        productImagePrompt: 'A pack of premium tissues with soft white packaging and blue accents, clean studio product shot on plain white background',
        segments: [
          { i: 1, durationSec: 6, cast: ['char_a', 'char_b'], product: false, scene: 'Wide shot of the restaurant table, Xiao Ming nervously sits across from Mother Wang', action: 'Xiao Ming sweats as Mother Wang scrutinizes him, she sneezes suddenly', dialogue: 'Mother Wang: So, what do you do? Xiao Ming: I... I write code...', hook: 'The sneeze breaks the tension' },
          { i: 2, durationSec: 5, cast: ['char_a'], product: true, scene: 'Close-up on Xiao Ming fumbling in his bag', action: 'Xiao Ming pulls out a pack of tissues and offers it to Mother Wang', dialogue: 'Xiao Ming: Here, please use these', hook: 'The product appears at the perfect moment' },
          { i: 3, durationSec: 6, cast: ['char_b'], product: true, scene: 'Close-up on Mother Wang examining the tissue', action: 'Mother Wang feels the tissue quality, her expression softens', dialogue: 'Mother Wang: Hmm... these are actually quite soft', hook: 'The critical mother-in-law is impressed' },
          { i: 4, durationSec: 5, cast: ['char_a', 'char_b'], product: false, scene: 'Two-shot, both smiling', action: 'They share a laugh, the ice is broken', dialogue: 'Mother Wang: Maybe programmers are not so bad after all', hook: 'Heartwarming resolution' },
        ],
        climax: 'The picky mother-in-law is won over by the simple gesture of offering quality tissues at the perfect moment',
      });
    } else if (systemMsg?.content?.includes?.('skit') || systemMsg?.content?.includes?.('Skit') || (userMsg && typeof userMsg.content === 'string' && userMsg.content.includes('双人喜剧'))) {
      // Ad skit plan response — must return JSON with idea, productImagePrompt, videoPrompt, caption
      content = JSON.stringify({
        idea: 'Two friends compare their skin after using the serum — one used it for a week, the other didn\'t. The twist: the one who didn\'t use it thinks it\'s a filter!',
        productImagePrompt: 'A premium vitamin C serum bottle with a minimalist white label on a clean white background, soft studio lighting, e-commerce product photography style',
        videoPrompt: 'Two young women sit side by side in a bright cafe. Friend A has radiant glowing skin, Friend B looks tired. Friend B stares at Friend A: "Is that a filter?" Friend A laughs and holds up the Glow Serum bottle: "No filter, just this!" Friend B grabs the bottle eagerly. Close-up on the serum bottle. Both laugh. @image1',
        caption: 'Glow Serum — Real radiance, no filter needed',
      });
    } else if (systemMsg?.content?.includes?.('爆款短视频广告编剧')) {
      // Ad-reference gen-script response — first-person UGC spoken dialogue
      content = 'Okay so I have to tell you about this serum — I was skeptical at first, but after two weeks? My dark spots are basically gone and my skin literally glows. Just a few drops morning and night, that\'s it. Trust me, your future self will thank you.';
    } else {
      // Generic response — structured to be useful for any JSON-expecting caller
      const isJsonExpected = systemMsg?.content?.includes?.('JSON') || systemMsg?.content?.includes?.('json');
      if (isJsonExpected) {
        content = JSON.stringify({
          title: 'Mock Generated Ad',
          description: 'A product showcase ad generated by the mock Atlas server for local development.',
          prompt: 'A clean product shot with soft lighting and a friendly presenter demonstrating the product.',
        });
      } else {
        content = 'Here is a mock response from the local development Atlas server. In production, the real Atlas Cloud AI would generate contextually relevant content based on your product and creative preferences. This mock allows you to test the full generation workflow, polling lifecycle, and media handling without consuming real credits.';
      }
    }

    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      choices: [{ message: { content, role: 'assistant' } }],
      usage: { total_tokens: 100 },
    }));
    return;
  }

  // --- 404 for everything else ---
  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ error: 'not found', path }));
});

server.listen(PORT, () => {
  console.log(`[mock-atlas] Mock Atlas Cloud API server running on http://localhost:${PORT}`);
  console.log(`[mock-atlas] Set ATLASCLOUD_BASE=http://localhost:${PORT}/api/v1`);
  console.log(`[mock-atlas] Set ATLASCLOUD_LLM_BASE=http://localhost:${PORT}/v1`);
  console.log(`[mock-atlas] Set ATLASCLOUD_API_KEY=mock-key-for-dev`);
});
