/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/estate-planning/*
 * Consolidates 26 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as beneficiaries from '@/lib/api-handlers/estate-planning/beneficiaries';
import * as executors from '@/lib/api-handlers/estate-planning/executors';
import * as metrics from '@/lib/api-handlers/estate-planning/metrics';
import * as stats from '@/lib/api-handlers/estate-planning/stats';
import * as trusts from '@/lib/api-handlers/estate-planning/trusts';
import * as wills from '@/lib/api-handlers/estate-planning/wills';
import * as beneficiaries___id__disclaim from '@/lib/api-handlers/estate-planning/beneficiaries___id__disclaim';
import * as beneficiaries___id__remove from '@/lib/api-handlers/estate-planning/beneficiaries___id__remove';
import * as executors___id__activate from '@/lib/api-handlers/estate-planning/executors___id__activate';
import * as executors___id__decline from '@/lib/api-handlers/estate-planning/executors___id__decline';
import * as executors___id__remove from '@/lib/api-handlers/estate-planning/executors___id__remove';
import * as executors___id__resign from '@/lib/api-handlers/estate-planning/executors___id__resign';
import * as trusts___id__activate from '@/lib/api-handlers/estate-planning/trusts___id__activate';
import * as trusts___id__amend from '@/lib/api-handlers/estate-planning/trusts___id__amend';
import * as trusts___id__fund from '@/lib/api-handlers/estate-planning/trusts___id__fund';
import * as trusts___id__suspend from '@/lib/api-handlers/estate-planning/trusts___id__suspend';
import * as trusts___id__terminate from '@/lib/api-handlers/estate-planning/trusts___id__terminate';
import * as wills___id__amend from '@/lib/api-handlers/estate-planning/wills___id__amend';
import * as wills___id__contest from '@/lib/api-handlers/estate-planning/wills___id__contest';
import * as wills___id__execute from '@/lib/api-handlers/estate-planning/wills___id__execute';
import * as wills___id__probate from '@/lib/api-handlers/estate-planning/wills___id__probate';
import * as wills___id__revoke from '@/lib/api-handlers/estate-planning/wills___id__revoke';
import * as beneficiaries___id from '@/lib/api-handlers/estate-planning/beneficiaries___id';
import * as executors___id from '@/lib/api-handlers/estate-planning/executors___id';
import * as trusts___id from '@/lib/api-handlers/estate-planning/trusts___id';
import * as wills___id from '@/lib/api-handlers/estate-planning/wills___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["beneficiaries"], paramNames: [], handlers: { GET: beneficiaries.GET, POST: beneficiaries.POST } },
  { segments: ["executors"], paramNames: [], handlers: { GET: executors.GET, POST: executors.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["trusts"], paramNames: [], handlers: { GET: trusts.GET, POST: trusts.POST } },
  { segments: ["wills"], paramNames: [], handlers: { GET: wills.GET, POST: wills.POST } },
  { segments: ["beneficiaries","[id]","disclaim"], paramNames: ["id"], handlers: { POST: beneficiaries___id__disclaim.POST } },
  { segments: ["beneficiaries","[id]","remove"], paramNames: ["id"], handlers: { POST: beneficiaries___id__remove.POST } },
  { segments: ["executors","[id]","activate"], paramNames: ["id"], handlers: { POST: executors___id__activate.POST } },
  { segments: ["executors","[id]","decline"], paramNames: ["id"], handlers: { POST: executors___id__decline.POST } },
  { segments: ["executors","[id]","remove"], paramNames: ["id"], handlers: { POST: executors___id__remove.POST } },
  { segments: ["executors","[id]","resign"], paramNames: ["id"], handlers: { POST: executors___id__resign.POST } },
  { segments: ["trusts","[id]","activate"], paramNames: ["id"], handlers: { POST: trusts___id__activate.POST } },
  { segments: ["trusts","[id]","amend"], paramNames: ["id"], handlers: { POST: trusts___id__amend.POST } },
  { segments: ["trusts","[id]","fund"], paramNames: ["id"], handlers: { POST: trusts___id__fund.POST } },
  { segments: ["trusts","[id]","suspend"], paramNames: ["id"], handlers: { POST: trusts___id__suspend.POST } },
  { segments: ["trusts","[id]","terminate"], paramNames: ["id"], handlers: { POST: trusts___id__terminate.POST } },
  { segments: ["wills","[id]","amend"], paramNames: ["id"], handlers: { POST: wills___id__amend.POST } },
  { segments: ["wills","[id]","contest"], paramNames: ["id"], handlers: { POST: wills___id__contest.POST } },
  { segments: ["wills","[id]","execute"], paramNames: ["id"], handlers: { POST: wills___id__execute.POST } },
  { segments: ["wills","[id]","probate"], paramNames: ["id"], handlers: { POST: wills___id__probate.POST } },
  { segments: ["wills","[id]","revoke"], paramNames: ["id"], handlers: { POST: wills___id__revoke.POST } },
  { segments: ["beneficiaries","[id]"], paramNames: ["id"], handlers: { GET: beneficiaries___id.GET, PATCH: beneficiaries___id.PATCH, DELETE: beneficiaries___id.DELETE } },
  { segments: ["executors","[id]"], paramNames: ["id"], handlers: { GET: executors___id.GET, PATCH: executors___id.PATCH, DELETE: executors___id.DELETE } },
  { segments: ["trusts","[id]"], paramNames: ["id"], handlers: { GET: trusts___id.GET, PATCH: trusts___id.PATCH, DELETE: trusts___id.DELETE } },
  { segments: ["wills","[id]"], paramNames: ["id"], handlers: { GET: wills___id.GET, PATCH: wills___id.PATCH, DELETE: wills___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
