/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/alerts/*
 * Consolidates 7 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as evaluate_all from '@/lib/api-handlers/alerts/evaluate_all';
import * as summary from '@/lib/api-handlers/alerts/summary';
import * as index from '@/lib/api-handlers/alerts/index';
import * as _id__acknowledge from '@/lib/api-handlers/alerts/_id__acknowledge';
import * as _id__evaluate from '@/lib/api-handlers/alerts/_id__evaluate';
import * as _id__resolve from '@/lib/api-handlers/alerts/_id__resolve';
import * as _id from '@/lib/api-handlers/alerts/_id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["evaluate-all"], paramNames: [], handlers: { POST: evaluate_all.POST } },
  { segments: ["summary"], paramNames: [], handlers: { GET: summary.GET } },
  { segments: [], paramNames: [], handlers: { GET: index.GET, POST: index.POST } },
  { segments: ["[id]","acknowledge"], paramNames: ["id"], handlers: { POST: _id__acknowledge.POST } },
  { segments: ["[id]","evaluate"], paramNames: ["id"], handlers: { POST: _id__evaluate.POST } },
  { segments: ["[id]","resolve"], paramNames: ["id"], handlers: { POST: _id__resolve.POST } },
  { segments: ["[id]"], paramNames: ["id"], handlers: { GET: _id.GET, PATCH: _id.PATCH } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path?: string[] }> },
) {
  const { path = [] } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
