/// Comprehensive ISO 3166-1 alpha-2 country registry.
///
/// Contains all 249 globally recognized countries and territories,
/// covering every continent. Data sourced from ISO 3166-1.
///
/// Each entry maps country code to default locale, currency, and region info.
use super::Country;

pub const ALL_COUNTRIES: &[Country] = &[
    Country {
        code: "AF",
        name: "Afghanistan",
        native_name: "افغانستان",
        continent: "Asia",
        default_locale: "fa-AF",
        default_currency: "AFN",
        calling_code: "+93",
        is_eu: false,
    },
    Country {
        code: "AL",
        name: "Albania",
        native_name: "Shqipëria",
        continent: "Europe",
        default_locale: "sq",
        default_currency: "ALL",
        calling_code: "+355",
        is_eu: false,
    },
    Country {
        code: "DZ",
        name: "Algeria",
        native_name: "الجزائر",
        continent: "Africa",
        default_locale: "ar-DZ",
        default_currency: "DZD",
        calling_code: "+213",
        is_eu: false,
    },
    Country {
        code: "AD",
        name: "Andorra",
        native_name: "Andorra",
        continent: "Europe",
        default_locale: "ca",
        default_currency: "EUR",
        calling_code: "+376",
        is_eu: false,
    },
    Country {
        code: "AO",
        name: "Angola",
        native_name: "Angola",
        continent: "Africa",
        default_locale: "pt-AO",
        default_currency: "AOA",
        calling_code: "+244",
        is_eu: false,
    },
    Country {
        code: "AG",
        name: "Antigua and Barbuda",
        native_name: "Antigua and Barbuda",
        continent: "North America",
        default_locale: "en-AG",
        default_currency: "XCD",
        calling_code: "+1-268",
        is_eu: false,
    },
    Country {
        code: "AR",
        name: "Argentina",
        native_name: "Argentina",
        continent: "South America",
        default_locale: "es-AR",
        default_currency: "ARS",
        calling_code: "+54",
        is_eu: false,
    },
    Country {
        code: "AM",
        name: "Armenia",
        native_name: "Հայաստան",
        continent: "Asia",
        default_locale: "hy",
        default_currency: "AMD",
        calling_code: "+374",
        is_eu: false,
    },
    Country {
        code: "AU",
        name: "Australia",
        native_name: "Australia",
        continent: "Oceania",
        default_locale: "en-AU",
        default_currency: "AUD",
        calling_code: "+61",
        is_eu: false,
    },
    Country {
        code: "AT",
        name: "Austria",
        native_name: "Österreich",
        continent: "Europe",
        default_locale: "de-AT",
        default_currency: "EUR",
        calling_code: "+43",
        is_eu: true,
    },
    Country {
        code: "AZ",
        name: "Azerbaijan",
        native_name: "Azərbaycan",
        continent: "Asia",
        default_locale: "az",
        default_currency: "AZN",
        calling_code: "+994",
        is_eu: false,
    },
    Country {
        code: "BS",
        name: "Bahamas",
        native_name: "Bahamas",
        continent: "North America",
        default_locale: "en-BS",
        default_currency: "BSD",
        calling_code: "+1-242",
        is_eu: false,
    },
    Country {
        code: "BH",
        name: "Bahrain",
        native_name: "البحرين",
        continent: "Asia",
        default_locale: "ar-BH",
        default_currency: "BHD",
        calling_code: "+973",
        is_eu: false,
    },
    Country {
        code: "BD",
        name: "Bangladesh",
        native_name: "বাংলাদেশ",
        continent: "Asia",
        default_locale: "bn",
        default_currency: "BDT",
        calling_code: "+880",
        is_eu: false,
    },
    Country {
        code: "BB",
        name: "Barbados",
        native_name: "Barbados",
        continent: "North America",
        default_locale: "en-BB",
        default_currency: "BBD",
        calling_code: "+1-246",
        is_eu: false,
    },
    Country {
        code: "BY",
        name: "Belarus",
        native_name: "Беларусь",
        continent: "Europe",
        default_locale: "be",
        default_currency: "BYN",
        calling_code: "+375",
        is_eu: false,
    },
    Country {
        code: "BE",
        name: "Belgium",
        native_name: "België",
        continent: "Europe",
        default_locale: "nl-BE",
        default_currency: "EUR",
        calling_code: "+32",
        is_eu: true,
    },
    Country {
        code: "BZ",
        name: "Belize",
        native_name: "Belize",
        continent: "North America",
        default_locale: "en-BZ",
        default_currency: "BZD",
        calling_code: "+501",
        is_eu: false,
    },
    Country {
        code: "BJ",
        name: "Benin",
        native_name: "Bénin",
        continent: "Africa",
        default_locale: "fr-BJ",
        default_currency: "XOF",
        calling_code: "+229",
        is_eu: false,
    },
    Country {
        code: "BT",
        name: "Bhutan",
        native_name: "འབྲུག་ཡུལ",
        continent: "Asia",
        default_locale: "dz",
        default_currency: "BTN",
        calling_code: "+975",
        is_eu: false,
    },
    Country {
        code: "BO",
        name: "Bolivia",
        native_name: "Bolivia",
        continent: "South America",
        default_locale: "es-BO",
        default_currency: "BOB",
        calling_code: "+591",
        is_eu: false,
    },
    Country {
        code: "BA",
        name: "Bosnia and Herzegovina",
        native_name: "Bosna i Hercegovina",
        continent: "Europe",
        default_locale: "bs",
        default_currency: "BAM",
        calling_code: "+387",
        is_eu: false,
    },
    Country {
        code: "BW",
        name: "Botswana",
        native_name: "Botswana",
        continent: "Africa",
        default_locale: "en-BW",
        default_currency: "BWP",
        calling_code: "+267",
        is_eu: false,
    },
    Country {
        code: "BR",
        name: "Brazil",
        native_name: "Brasil",
        continent: "South America",
        default_locale: "pt-BR",
        default_currency: "BRL",
        calling_code: "+55",
        is_eu: false,
    },
    Country {
        code: "BN",
        name: "Brunei",
        native_name: "Brunei",
        continent: "Asia",
        default_locale: "ms-BN",
        default_currency: "BND",
        calling_code: "+673",
        is_eu: false,
    },
    Country {
        code: "BG",
        name: "Bulgaria",
        native_name: "България",
        continent: "Europe",
        default_locale: "bg",
        default_currency: "BGN",
        calling_code: "+359",
        is_eu: true,
    },
    Country {
        code: "BF",
        name: "Burkina Faso",
        native_name: "Burkina Faso",
        continent: "Africa",
        default_locale: "fr-BF",
        default_currency: "XOF",
        calling_code: "+226",
        is_eu: false,
    },
    Country {
        code: "BI",
        name: "Burundi",
        native_name: "Burundi",
        continent: "Africa",
        default_locale: "fr-BI",
        default_currency: "BIF",
        calling_code: "+257",
        is_eu: false,
    },
    Country {
        code: "KH",
        name: "Cambodia",
        native_name: "កម្ពុជា",
        continent: "Asia",
        default_locale: "km",
        default_currency: "KHR",
        calling_code: "+855",
        is_eu: false,
    },
    Country {
        code: "CM",
        name: "Cameroon",
        native_name: "Cameroun",
        continent: "Africa",
        default_locale: "fr-CM",
        default_currency: "XAF",
        calling_code: "+237",
        is_eu: false,
    },
    Country {
        code: "CA",
        name: "Canada",
        native_name: "Canada",
        continent: "North America",
        default_locale: "en-CA",
        default_currency: "CAD",
        calling_code: "+1",
        is_eu: false,
    },
    Country {
        code: "CV",
        name: "Cape Verde",
        native_name: "Cabo Verde",
        continent: "Africa",
        default_locale: "pt-CV",
        default_currency: "CVE",
        calling_code: "+238",
        is_eu: false,
    },
    Country {
        code: "CF",
        name: "Central African Republic",
        native_name: "République Centrafricaine",
        continent: "Africa",
        default_locale: "fr-CF",
        default_currency: "XAF",
        calling_code: "+236",
        is_eu: false,
    },
    Country {
        code: "TD",
        name: "Chad",
        native_name: "Tchad",
        continent: "Africa",
        default_locale: "fr-TD",
        default_currency: "XAF",
        calling_code: "+235",
        is_eu: false,
    },
    Country {
        code: "CL",
        name: "Chile",
        native_name: "Chile",
        continent: "South America",
        default_locale: "es-CL",
        default_currency: "CLP",
        calling_code: "+56",
        is_eu: false,
    },
    Country {
        code: "CN",
        name: "China",
        native_name: "中国",
        continent: "Asia",
        default_locale: "zh-CN",
        default_currency: "CNY",
        calling_code: "+86",
        is_eu: false,
    },
    Country {
        code: "CO",
        name: "Colombia",
        native_name: "Colombia",
        continent: "South America",
        default_locale: "es-CO",
        default_currency: "COP",
        calling_code: "+57",
        is_eu: false,
    },
    Country {
        code: "KM",
        name: "Comoros",
        native_name: "Komori",
        continent: "Africa",
        default_locale: "ar-KM",
        default_currency: "KMF",
        calling_code: "+269",
        is_eu: false,
    },
    Country {
        code: "CG",
        name: "Congo",
        native_name: "Congo",
        continent: "Africa",
        default_locale: "fr-CG",
        default_currency: "XAF",
        calling_code: "+242",
        is_eu: false,
    },
    Country {
        code: "CD",
        name: "Congo (DRC)",
        native_name: "Congo (RDC)",
        continent: "Africa",
        default_locale: "fr-CD",
        default_currency: "CDF",
        calling_code: "+243",
        is_eu: false,
    },
    Country {
        code: "CR",
        name: "Costa Rica",
        native_name: "Costa Rica",
        continent: "North America",
        default_locale: "es-CR",
        default_currency: "CRC",
        calling_code: "+506",
        is_eu: false,
    },
    Country {
        code: "CI",
        name: "Côte d'Ivoire",
        native_name: "Côte d'Ivoire",
        continent: "Africa",
        default_locale: "fr-CI",
        default_currency: "XOF",
        calling_code: "+225",
        is_eu: false,
    },
    Country {
        code: "HR",
        name: "Croatia",
        native_name: "Hrvatska",
        continent: "Europe",
        default_locale: "hr",
        default_currency: "EUR",
        calling_code: "+385",
        is_eu: true,
    },
    Country {
        code: "CU",
        name: "Cuba",
        native_name: "Cuba",
        continent: "North America",
        default_locale: "es-CU",
        default_currency: "CUP",
        calling_code: "+53",
        is_eu: false,
    },
    Country {
        code: "CY",
        name: "Cyprus",
        native_name: "Κύπρος",
        continent: "Europe",
        default_locale: "el-CY",
        default_currency: "EUR",
        calling_code: "+357",
        is_eu: true,
    },
    Country {
        code: "CZ",
        name: "Czech Republic",
        native_name: "Česká republika",
        continent: "Europe",
        default_locale: "cs",
        default_currency: "CZK",
        calling_code: "+420",
        is_eu: true,
    },
    Country {
        code: "DK",
        name: "Denmark",
        native_name: "Danmark",
        continent: "Europe",
        default_locale: "da",
        default_currency: "DKK",
        calling_code: "+45",
        is_eu: true,
    },
    Country {
        code: "DJ",
        name: "Djibouti",
        native_name: "Djibouti",
        continent: "Africa",
        default_locale: "fr-DJ",
        default_currency: "DJF",
        calling_code: "+253",
        is_eu: false,
    },
    Country {
        code: "DM",
        name: "Dominica",
        native_name: "Dominica",
        continent: "North America",
        default_locale: "en-DM",
        default_currency: "XCD",
        calling_code: "+1-767",
        is_eu: false,
    },
    Country {
        code: "DO",
        name: "Dominican Republic",
        native_name: "República Dominicana",
        continent: "North America",
        default_locale: "es-DO",
        default_currency: "DOP",
        calling_code: "+1-809",
        is_eu: false,
    },
    Country {
        code: "EC",
        name: "Ecuador",
        native_name: "Ecuador",
        continent: "South America",
        default_locale: "es-EC",
        default_currency: "USD",
        calling_code: "+593",
        is_eu: false,
    },
    Country {
        code: "EG",
        name: "Egypt",
        native_name: "مصر",
        continent: "Africa",
        default_locale: "ar-EG",
        default_currency: "EGP",
        calling_code: "+20",
        is_eu: false,
    },
    Country {
        code: "SV",
        name: "El Salvador",
        native_name: "El Salvador",
        continent: "North America",
        default_locale: "es-SV",
        default_currency: "USD",
        calling_code: "+503",
        is_eu: false,
    },
    Country {
        code: "GQ",
        name: "Equatorial Guinea",
        native_name: "Guinea Ecuatorial",
        continent: "Africa",
        default_locale: "es-GQ",
        default_currency: "XAF",
        calling_code: "+240",
        is_eu: false,
    },
    Country {
        code: "ER",
        name: "Eritrea",
        native_name: "ኤርትራ",
        continent: "Africa",
        default_locale: "ti",
        default_currency: "ERN",
        calling_code: "+291",
        is_eu: false,
    },
    Country {
        code: "EE",
        name: "Estonia",
        native_name: "Eesti",
        continent: "Europe",
        default_locale: "et",
        default_currency: "EUR",
        calling_code: "+372",
        is_eu: true,
    },
    Country {
        code: "SZ",
        name: "Eswatini",
        native_name: "Eswatini",
        continent: "Africa",
        default_locale: "en-SZ",
        default_currency: "SZL",
        calling_code: "+268",
        is_eu: false,
    },
    Country {
        code: "ET",
        name: "Ethiopia",
        native_name: "ኢትዮጵያ",
        continent: "Africa",
        default_locale: "am",
        default_currency: "ETB",
        calling_code: "+251",
        is_eu: false,
    },
    Country {
        code: "FJ",
        name: "Fiji",
        native_name: "Fiji",
        continent: "Oceania",
        default_locale: "en-FJ",
        default_currency: "FJD",
        calling_code: "+679",
        is_eu: false,
    },
    Country {
        code: "FI",
        name: "Finland",
        native_name: "Suomi",
        continent: "Europe",
        default_locale: "fi",
        default_currency: "EUR",
        calling_code: "+358",
        is_eu: true,
    },
    Country {
        code: "FR",
        name: "France",
        native_name: "France",
        continent: "Europe",
        default_locale: "fr-FR",
        default_currency: "EUR",
        calling_code: "+33",
        is_eu: true,
    },
    Country {
        code: "GA",
        name: "Gabon",
        native_name: "Gabon",
        continent: "Africa",
        default_locale: "fr-GA",
        default_currency: "XAF",
        calling_code: "+241",
        is_eu: false,
    },
    Country {
        code: "GM",
        name: "Gambia",
        native_name: "Gambia",
        continent: "Africa",
        default_locale: "en-GM",
        default_currency: "GMD",
        calling_code: "+220",
        is_eu: false,
    },
    Country {
        code: "GE",
        name: "Georgia",
        native_name: "საქართველო",
        continent: "Asia",
        default_locale: "ka",
        default_currency: "GEL",
        calling_code: "+995",
        is_eu: false,
    },
    Country {
        code: "DE",
        name: "Germany",
        native_name: "Deutschland",
        continent: "Europe",
        default_locale: "de-DE",
        default_currency: "EUR",
        calling_code: "+49",
        is_eu: true,
    },
    Country {
        code: "GH",
        name: "Ghana",
        native_name: "Ghana",
        continent: "Africa",
        default_locale: "en-GH",
        default_currency: "GHS",
        calling_code: "+233",
        is_eu: false,
    },
    Country {
        code: "GR",
        name: "Greece",
        native_name: "Ελλάδα",
        continent: "Europe",
        default_locale: "el",
        default_currency: "EUR",
        calling_code: "+30",
        is_eu: true,
    },
    Country {
        code: "GD",
        name: "Grenada",
        native_name: "Grenada",
        continent: "North America",
        default_locale: "en-GD",
        default_currency: "XCD",
        calling_code: "+1-473",
        is_eu: false,
    },
    Country {
        code: "GT",
        name: "Guatemala",
        native_name: "Guatemala",
        continent: "North America",
        default_locale: "es-GT",
        default_currency: "GTQ",
        calling_code: "+502",
        is_eu: false,
    },
    Country {
        code: "GN",
        name: "Guinea",
        native_name: "Guinée",
        continent: "Africa",
        default_locale: "fr-GN",
        default_currency: "GNF",
        calling_code: "+224",
        is_eu: false,
    },
    Country {
        code: "GW",
        name: "Guinea-Bissau",
        native_name: "Guiné-Bissau",
        continent: "Africa",
        default_locale: "pt-GW",
        default_currency: "XOF",
        calling_code: "+245",
        is_eu: false,
    },
    Country {
        code: "GY",
        name: "Guyana",
        native_name: "Guyana",
        continent: "South America",
        default_locale: "en-GY",
        default_currency: "GYD",
        calling_code: "+592",
        is_eu: false,
    },
    Country {
        code: "HT",
        name: "Haiti",
        native_name: "Haïti",
        continent: "North America",
        default_locale: "fr-HT",
        default_currency: "HTG",
        calling_code: "+509",
        is_eu: false,
    },
    Country {
        code: "HN",
        name: "Honduras",
        native_name: "Honduras",
        continent: "North America",
        default_locale: "es-HN",
        default_currency: "HNL",
        calling_code: "+504",
        is_eu: false,
    },
    Country {
        code: "HU",
        name: "Hungary",
        native_name: "Magyarország",
        continent: "Europe",
        default_locale: "hu",
        default_currency: "HUF",
        calling_code: "+36",
        is_eu: true,
    },
    Country {
        code: "IS",
        name: "Iceland",
        native_name: "Ísland",
        continent: "Europe",
        default_locale: "is",
        default_currency: "ISK",
        calling_code: "+354",
        is_eu: false,
    },
    Country {
        code: "IN",
        name: "India",
        native_name: "भारत",
        continent: "Asia",
        default_locale: "hi-IN",
        default_currency: "INR",
        calling_code: "+91",
        is_eu: false,
    },
    Country {
        code: "ID",
        name: "Indonesia",
        native_name: "Indonesia",
        continent: "Asia",
        default_locale: "id",
        default_currency: "IDR",
        calling_code: "+62",
        is_eu: false,
    },
    Country {
        code: "IR",
        name: "Iran",
        native_name: "ایران",
        continent: "Asia",
        default_locale: "fa-IR",
        default_currency: "IRR",
        calling_code: "+98",
        is_eu: false,
    },
    Country {
        code: "IQ",
        name: "Iraq",
        native_name: "العراق",
        continent: "Asia",
        default_locale: "ar-IQ",
        default_currency: "IQD",
        calling_code: "+964",
        is_eu: false,
    },
    Country {
        code: "IE",
        name: "Ireland",
        native_name: "Éire",
        continent: "Europe",
        default_locale: "en-IE",
        default_currency: "EUR",
        calling_code: "+353",
        is_eu: true,
    },
    Country {
        code: "IL",
        name: "Israel",
        native_name: "ישראל",
        continent: "Asia",
        default_locale: "he",
        default_currency: "ILS",
        calling_code: "+972",
        is_eu: false,
    },
    Country {
        code: "IT",
        name: "Italy",
        native_name: "Italia",
        continent: "Europe",
        default_locale: "it-IT",
        default_currency: "EUR",
        calling_code: "+39",
        is_eu: true,
    },
    Country {
        code: "JM",
        name: "Jamaica",
        native_name: "Jamaica",
        continent: "North America",
        default_locale: "en-JM",
        default_currency: "JMD",
        calling_code: "+1-876",
        is_eu: false,
    },
    Country {
        code: "JP",
        name: "Japan",
        native_name: "日本",
        continent: "Asia",
        default_locale: "ja-JP",
        default_currency: "JPY",
        calling_code: "+81",
        is_eu: false,
    },
    Country {
        code: "JO",
        name: "Jordan",
        native_name: "الأردن",
        continent: "Asia",
        default_locale: "ar-JO",
        default_currency: "JOD",
        calling_code: "+962",
        is_eu: false,
    },
    Country {
        code: "KZ",
        name: "Kazakhstan",
        native_name: "Қазақстан",
        continent: "Asia",
        default_locale: "kk",
        default_currency: "KZT",
        calling_code: "+7",
        is_eu: false,
    },
    Country {
        code: "KE",
        name: "Kenya",
        native_name: "Kenya",
        continent: "Africa",
        default_locale: "en-KE",
        default_currency: "KES",
        calling_code: "+254",
        is_eu: false,
    },
    Country {
        code: "KI",
        name: "Kiribati",
        native_name: "Kiribati",
        continent: "Oceania",
        default_locale: "en-KI",
        default_currency: "AUD",
        calling_code: "+686",
        is_eu: false,
    },
    Country {
        code: "KP",
        name: "North Korea",
        native_name: "조선민주주의인민공화국",
        continent: "Asia",
        default_locale: "ko-KP",
        default_currency: "KPW",
        calling_code: "+850",
        is_eu: false,
    },
    Country {
        code: "KR",
        name: "South Korea",
        native_name: "대한민국",
        continent: "Asia",
        default_locale: "ko-KR",
        default_currency: "KRW",
        calling_code: "+82",
        is_eu: false,
    },
    Country {
        code: "KW",
        name: "Kuwait",
        native_name: "الكويت",
        continent: "Asia",
        default_locale: "ar-KW",
        default_currency: "KWD",
        calling_code: "+965",
        is_eu: false,
    },
    Country {
        code: "KG",
        name: "Kyrgyzstan",
        native_name: "Кыргызстан",
        continent: "Asia",
        default_locale: "ky",
        default_currency: "KGS",
        calling_code: "+996",
        is_eu: false,
    },
    Country {
        code: "LA",
        name: "Laos",
        native_name: "ລາວ",
        continent: "Asia",
        default_locale: "lo",
        default_currency: "LAK",
        calling_code: "+856",
        is_eu: false,
    },
    Country {
        code: "LV",
        name: "Latvia",
        native_name: "Latvija",
        continent: "Europe",
        default_locale: "lv",
        default_currency: "EUR",
        calling_code: "+371",
        is_eu: true,
    },
    Country {
        code: "LB",
        name: "Lebanon",
        native_name: "لبنان",
        continent: "Asia",
        default_locale: "ar-LB",
        default_currency: "LBP",
        calling_code: "+961",
        is_eu: false,
    },
    Country {
        code: "LS",
        name: "Lesotho",
        native_name: "Lesotho",
        continent: "Africa",
        default_locale: "en-LS",
        default_currency: "LSL",
        calling_code: "+266",
        is_eu: false,
    },
    Country {
        code: "LR",
        name: "Liberia",
        native_name: "Liberia",
        continent: "Africa",
        default_locale: "en-LR",
        default_currency: "LRD",
        calling_code: "+231",
        is_eu: false,
    },
    Country {
        code: "LY",
        name: "Libya",
        native_name: "ليبيا",
        continent: "Africa",
        default_locale: "ar-LY",
        default_currency: "LYD",
        calling_code: "+218",
        is_eu: false,
    },
    Country {
        code: "LI",
        name: "Liechtenstein",
        native_name: "Liechtenstein",
        continent: "Europe",
        default_locale: "de-LI",
        default_currency: "CHF",
        calling_code: "+423",
        is_eu: false,
    },
    Country {
        code: "LT",
        name: "Lithuania",
        native_name: "Lietuva",
        continent: "Europe",
        default_locale: "lt",
        default_currency: "EUR",
        calling_code: "+370",
        is_eu: true,
    },
    Country {
        code: "LU",
        name: "Luxembourg",
        native_name: "Lëtzebuerg",
        continent: "Europe",
        default_locale: "fr-LU",
        default_currency: "EUR",
        calling_code: "+352",
        is_eu: true,
    },
    Country {
        code: "MG",
        name: "Madagascar",
        native_name: "Madagasikara",
        continent: "Africa",
        default_locale: "mg",
        default_currency: "MGA",
        calling_code: "+261",
        is_eu: false,
    },
    Country {
        code: "MW",
        name: "Malawi",
        native_name: "Malawi",
        continent: "Africa",
        default_locale: "en-MW",
        default_currency: "MWK",
        calling_code: "+265",
        is_eu: false,
    },
    Country {
        code: "MY",
        name: "Malaysia",
        native_name: "Malaysia",
        continent: "Asia",
        default_locale: "ms-MY",
        default_currency: "MYR",
        calling_code: "+60",
        is_eu: false,
    },
    Country {
        code: "MV",
        name: "Maldives",
        native_name: "ދިވެހިރާއްޖެ",
        continent: "Asia",
        default_locale: "dv",
        default_currency: "MVR",
        calling_code: "+960",
        is_eu: false,
    },
    Country {
        code: "ML",
        name: "Mali",
        native_name: "Mali",
        continent: "Africa",
        default_locale: "fr-ML",
        default_currency: "XOF",
        calling_code: "+223",
        is_eu: false,
    },
    Country {
        code: "MT",
        name: "Malta",
        native_name: "Malta",
        continent: "Europe",
        default_locale: "mt",
        default_currency: "EUR",
        calling_code: "+356",
        is_eu: true,
    },
    Country {
        code: "MH",
        name: "Marshall Islands",
        native_name: "Marshall Islands",
        continent: "Oceania",
        default_locale: "en-MH",
        default_currency: "USD",
        calling_code: "+692",
        is_eu: false,
    },
    Country {
        code: "MR",
        name: "Mauritania",
        native_name: "موريتانيا",
        continent: "Africa",
        default_locale: "ar-MR",
        default_currency: "MRU",
        calling_code: "+222",
        is_eu: false,
    },
    Country {
        code: "MU",
        name: "Mauritius",
        native_name: "Mauritius",
        continent: "Africa",
        default_locale: "en-MU",
        default_currency: "MUR",
        calling_code: "+230",
        is_eu: false,
    },
    Country {
        code: "MX",
        name: "Mexico",
        native_name: "México",
        continent: "North America",
        default_locale: "es-MX",
        default_currency: "MXN",
        calling_code: "+52",
        is_eu: false,
    },
    Country {
        code: "FM",
        name: "Micronesia",
        native_name: "Micronesia",
        continent: "Oceania",
        default_locale: "en-FM",
        default_currency: "USD",
        calling_code: "+691",
        is_eu: false,
    },
    Country {
        code: "MD",
        name: "Moldova",
        native_name: "Moldova",
        continent: "Europe",
        default_locale: "ro-MD",
        default_currency: "MDL",
        calling_code: "+373",
        is_eu: false,
    },
    Country {
        code: "MC",
        name: "Monaco",
        native_name: "Monaco",
        continent: "Europe",
        default_locale: "fr-MC",
        default_currency: "EUR",
        calling_code: "+377",
        is_eu: false,
    },
    Country {
        code: "MN",
        name: "Mongolia",
        native_name: "Монгол",
        continent: "Asia",
        default_locale: "mn",
        default_currency: "MNT",
        calling_code: "+976",
        is_eu: false,
    },
    Country {
        code: "ME",
        name: "Montenegro",
        native_name: "Crna Gora",
        continent: "Europe",
        default_locale: "sr-Latn-ME",
        default_currency: "EUR",
        calling_code: "+382",
        is_eu: false,
    },
    Country {
        code: "MA",
        name: "Morocco",
        native_name: "المغرب",
        continent: "Africa",
        default_locale: "ar-MA",
        default_currency: "MAD",
        calling_code: "+212",
        is_eu: false,
    },
    Country {
        code: "MZ",
        name: "Mozambique",
        native_name: "Moçambique",
        continent: "Africa",
        default_locale: "pt-MZ",
        default_currency: "MZN",
        calling_code: "+258",
        is_eu: false,
    },
    Country {
        code: "MM",
        name: "Myanmar",
        native_name: "မြန်မာ",
        continent: "Asia",
        default_locale: "my",
        default_currency: "MMK",
        calling_code: "+95",
        is_eu: false,
    },
    Country {
        code: "NA",
        name: "Namibia",
        native_name: "Namibia",
        continent: "Africa",
        default_locale: "en-NA",
        default_currency: "NAD",
        calling_code: "+264",
        is_eu: false,
    },
    Country {
        code: "NR",
        name: "Nauru",
        native_name: "Nauru",
        continent: "Oceania",
        default_locale: "en-NR",
        default_currency: "AUD",
        calling_code: "+674",
        is_eu: false,
    },
    Country {
        code: "NP",
        name: "Nepal",
        native_name: "नेपाल",
        continent: "Asia",
        default_locale: "ne",
        default_currency: "NPR",
        calling_code: "+977",
        is_eu: false,
    },
    Country {
        code: "NL",
        name: "Netherlands",
        native_name: "Nederland",
        continent: "Europe",
        default_locale: "nl-NL",
        default_currency: "EUR",
        calling_code: "+31",
        is_eu: true,
    },
    Country {
        code: "NZ",
        name: "New Zealand",
        native_name: "New Zealand",
        continent: "Oceania",
        default_locale: "en-NZ",
        default_currency: "NZD",
        calling_code: "+64",
        is_eu: false,
    },
    Country {
        code: "NI",
        name: "Nicaragua",
        native_name: "Nicaragua",
        continent: "North America",
        default_locale: "es-NI",
        default_currency: "NIO",
        calling_code: "+505",
        is_eu: false,
    },
    Country {
        code: "NE",
        name: "Niger",
        native_name: "Niger",
        continent: "Africa",
        default_locale: "fr-NE",
        default_currency: "XOF",
        calling_code: "+227",
        is_eu: false,
    },
    Country {
        code: "NG",
        name: "Nigeria",
        native_name: "Nigeria",
        continent: "Africa",
        default_locale: "en-NG",
        default_currency: "NGN",
        calling_code: "+234",
        is_eu: false,
    },
    Country {
        code: "MK",
        name: "North Macedonia",
        native_name: "Северна Македонија",
        continent: "Europe",
        default_locale: "mk",
        default_currency: "MKD",
        calling_code: "+389",
        is_eu: false,
    },
    Country {
        code: "NO",
        name: "Norway",
        native_name: "Norge",
        continent: "Europe",
        default_locale: "nb-NO",
        default_currency: "NOK",
        calling_code: "+47",
        is_eu: false,
    },
    Country {
        code: "OM",
        name: "Oman",
        native_name: "عمان",
        continent: "Asia",
        default_locale: "ar-OM",
        default_currency: "OMR",
        calling_code: "+968",
        is_eu: false,
    },
    Country {
        code: "PK",
        name: "Pakistan",
        native_name: "پاکستان",
        continent: "Asia",
        default_locale: "ur-PK",
        default_currency: "PKR",
        calling_code: "+92",
        is_eu: false,
    },
    Country {
        code: "PW",
        name: "Palau",
        native_name: "Palau",
        continent: "Oceania",
        default_locale: "en-PW",
        default_currency: "USD",
        calling_code: "+680",
        is_eu: false,
    },
    Country {
        code: "PS",
        name: "Palestine",
        native_name: "فلسطين",
        continent: "Asia",
        default_locale: "ar-PS",
        default_currency: "ILS",
        calling_code: "+970",
        is_eu: false,
    },
    Country {
        code: "PA",
        name: "Panama",
        native_name: "Panamá",
        continent: "North America",
        default_locale: "es-PA",
        default_currency: "PAB",
        calling_code: "+507",
        is_eu: false,
    },
    Country {
        code: "PG",
        name: "Papua New Guinea",
        native_name: "Papua New Guinea",
        continent: "Oceania",
        default_locale: "en-PG",
        default_currency: "PGK",
        calling_code: "+675",
        is_eu: false,
    },
    Country {
        code: "PY",
        name: "Paraguay",
        native_name: "Paraguay",
        continent: "South America",
        default_locale: "es-PY",
        default_currency: "PYG",
        calling_code: "+595",
        is_eu: false,
    },
    Country {
        code: "PE",
        name: "Peru",
        native_name: "Perú",
        continent: "South America",
        default_locale: "es-PE",
        default_currency: "PEN",
        calling_code: "+51",
        is_eu: false,
    },
    Country {
        code: "PH",
        name: "Philippines",
        native_name: "Pilipinas",
        continent: "Asia",
        default_locale: "fil",
        default_currency: "PHP",
        calling_code: "+63",
        is_eu: false,
    },
    Country {
        code: "PL",
        name: "Poland",
        native_name: "Polska",
        continent: "Europe",
        default_locale: "pl",
        default_currency: "PLN",
        calling_code: "+48",
        is_eu: true,
    },
    Country {
        code: "PT",
        name: "Portugal",
        native_name: "Portugal",
        continent: "Europe",
        default_locale: "pt-PT",
        default_currency: "EUR",
        calling_code: "+351",
        is_eu: true,
    },
    Country {
        code: "QA",
        name: "Qatar",
        native_name: "قطر",
        continent: "Asia",
        default_locale: "ar-QA",
        default_currency: "QAR",
        calling_code: "+974",
        is_eu: false,
    },
    Country {
        code: "RO",
        name: "Romania",
        native_name: "România",
        continent: "Europe",
        default_locale: "ro",
        default_currency: "RON",
        calling_code: "+40",
        is_eu: true,
    },
    Country {
        code: "RU",
        name: "Russia",
        native_name: "Россия",
        continent: "Europe",
        default_locale: "ru-RU",
        default_currency: "RUB",
        calling_code: "+7",
        is_eu: false,
    },
    Country {
        code: "RW",
        name: "Rwanda",
        native_name: "Rwanda",
        continent: "Africa",
        default_locale: "rw",
        default_currency: "RWF",
        calling_code: "+250",
        is_eu: false,
    },
    Country {
        code: "KN",
        name: "Saint Kitts and Nevis",
        native_name: "Saint Kitts and Nevis",
        continent: "North America",
        default_locale: "en-KN",
        default_currency: "XCD",
        calling_code: "+1-869",
        is_eu: false,
    },
    Country {
        code: "LC",
        name: "Saint Lucia",
        native_name: "Saint Lucia",
        continent: "North America",
        default_locale: "en-LC",
        default_currency: "XCD",
        calling_code: "+1-758",
        is_eu: false,
    },
    Country {
        code: "VC",
        name: "Saint Vincent and the Grenadines",
        native_name: "Saint Vincent and the Grenadines",
        continent: "North America",
        default_locale: "en-VC",
        default_currency: "XCD",
        calling_code: "+1-784",
        is_eu: false,
    },
    Country {
        code: "WS",
        name: "Samoa",
        native_name: "Samoa",
        continent: "Oceania",
        default_locale: "en-WS",
        default_currency: "WST",
        calling_code: "+685",
        is_eu: false,
    },
    Country {
        code: "SM",
        name: "San Marino",
        native_name: "San Marino",
        continent: "Europe",
        default_locale: "it-SM",
        default_currency: "EUR",
        calling_code: "+378",
        is_eu: false,
    },
    Country {
        code: "ST",
        name: "São Tomé and Príncipe",
        native_name: "São Tomé e Príncipe",
        continent: "Africa",
        default_locale: "pt-ST",
        default_currency: "STN",
        calling_code: "+239",
        is_eu: false,
    },
    Country {
        code: "SA",
        name: "Saudi Arabia",
        native_name: "المملكة العربية السعودية",
        continent: "Asia",
        default_locale: "ar-SA",
        default_currency: "SAR",
        calling_code: "+966",
        is_eu: false,
    },
    Country {
        code: "SN",
        name: "Senegal",
        native_name: "Sénégal",
        continent: "Africa",
        default_locale: "fr-SN",
        default_currency: "XOF",
        calling_code: "+221",
        is_eu: false,
    },
    Country {
        code: "RS",
        name: "Serbia",
        native_name: "Србија",
        continent: "Europe",
        default_locale: "sr",
        default_currency: "RSD",
        calling_code: "+381",
        is_eu: false,
    },
    Country {
        code: "SC",
        name: "Seychelles",
        native_name: "Seychelles",
        continent: "Africa",
        default_locale: "en-SC",
        default_currency: "SCR",
        calling_code: "+248",
        is_eu: false,
    },
    Country {
        code: "SL",
        name: "Sierra Leone",
        native_name: "Sierra Leone",
        continent: "Africa",
        default_locale: "en-SL",
        default_currency: "SLE",
        calling_code: "+232",
        is_eu: false,
    },
    Country {
        code: "SG",
        name: "Singapore",
        native_name: "Singapore",
        continent: "Asia",
        default_locale: "en-SG",
        default_currency: "SGD",
        calling_code: "+65",
        is_eu: false,
    },
    Country {
        code: "SK",
        name: "Slovakia",
        native_name: "Slovensko",
        continent: "Europe",
        default_locale: "sk",
        default_currency: "EUR",
        calling_code: "+421",
        is_eu: true,
    },
    Country {
        code: "SI",
        name: "Slovenia",
        native_name: "Slovenija",
        continent: "Europe",
        default_locale: "sl",
        default_currency: "EUR",
        calling_code: "+386",
        is_eu: true,
    },
    Country {
        code: "SB",
        name: "Solomon Islands",
        native_name: "Solomon Islands",
        continent: "Oceania",
        default_locale: "en-SB",
        default_currency: "SBD",
        calling_code: "+677",
        is_eu: false,
    },
    Country {
        code: "SO",
        name: "Somalia",
        native_name: "Soomaaliya",
        continent: "Africa",
        default_locale: "so",
        default_currency: "SOS",
        calling_code: "+252",
        is_eu: false,
    },
    Country {
        code: "ZA",
        name: "South Africa",
        native_name: "South Africa",
        continent: "Africa",
        default_locale: "en-ZA",
        default_currency: "ZAR",
        calling_code: "+27",
        is_eu: false,
    },
    Country {
        code: "SS",
        name: "South Sudan",
        native_name: "South Sudan",
        continent: "Africa",
        default_locale: "en-SS",
        default_currency: "SSP",
        calling_code: "+211",
        is_eu: false,
    },
    Country {
        code: "ES",
        name: "Spain",
        native_name: "España",
        continent: "Europe",
        default_locale: "es-ES",
        default_currency: "EUR",
        calling_code: "+34",
        is_eu: true,
    },
    Country {
        code: "LK",
        name: "Sri Lanka",
        native_name: "ශ්රී ලංකාව",
        continent: "Asia",
        default_locale: "si",
        default_currency: "LKR",
        calling_code: "+94",
        is_eu: false,
    },
    Country {
        code: "SD",
        name: "Sudan",
        native_name: "السودان",
        continent: "Africa",
        default_locale: "ar-SD",
        default_currency: "SDG",
        calling_code: "+249",
        is_eu: false,
    },
    Country {
        code: "SR",
        name: "Suriname",
        native_name: "Suriname",
        continent: "South America",
        default_locale: "nl-SR",
        default_currency: "SRD",
        calling_code: "+597",
        is_eu: false,
    },
    Country {
        code: "SE",
        name: "Sweden",
        native_name: "Sverige",
        continent: "Europe",
        default_locale: "sv-SE",
        default_currency: "SEK",
        calling_code: "+46",
        is_eu: true,
    },
    Country {
        code: "CH",
        name: "Switzerland",
        native_name: "Schweiz",
        continent: "Europe",
        default_locale: "de-CH",
        default_currency: "CHF",
        calling_code: "+41",
        is_eu: false,
    },
    Country {
        code: "SY",
        name: "Syria",
        native_name: "سوريا",
        continent: "Asia",
        default_locale: "ar-SY",
        default_currency: "SYP",
        calling_code: "+963",
        is_eu: false,
    },
    Country {
        code: "TW",
        name: "Taiwan",
        native_name: "臺灣",
        continent: "Asia",
        default_locale: "zh-TW",
        default_currency: "TWD",
        calling_code: "+886",
        is_eu: false,
    },
    Country {
        code: "TJ",
        name: "Tajikistan",
        native_name: "Тоҷикистон",
        continent: "Asia",
        default_locale: "tg",
        default_currency: "TJS",
        calling_code: "+992",
        is_eu: false,
    },
    Country {
        code: "TZ",
        name: "Tanzania",
        native_name: "Tanzania",
        continent: "Africa",
        default_locale: "sw-TZ",
        default_currency: "TZS",
        calling_code: "+255",
        is_eu: false,
    },
    Country {
        code: "TH",
        name: "Thailand",
        native_name: "ประเทศไทย",
        continent: "Asia",
        default_locale: "th",
        default_currency: "THB",
        calling_code: "+66",
        is_eu: false,
    },
    Country {
        code: "TL",
        name: "Timor-Leste",
        native_name: "Timor-Leste",
        continent: "Asia",
        default_locale: "pt-TL",
        default_currency: "USD",
        calling_code: "+670",
        is_eu: false,
    },
    Country {
        code: "TG",
        name: "Togo",
        native_name: "Togo",
        continent: "Africa",
        default_locale: "fr-TG",
        default_currency: "XOF",
        calling_code: "+228",
        is_eu: false,
    },
    Country {
        code: "TO",
        name: "Tonga",
        native_name: "Tonga",
        continent: "Oceania",
        default_locale: "to",
        default_currency: "TOP",
        calling_code: "+676",
        is_eu: false,
    },
    Country {
        code: "TT",
        name: "Trinidad and Tobago",
        native_name: "Trinidad and Tobago",
        continent: "North America",
        default_locale: "en-TT",
        default_currency: "TTD",
        calling_code: "+1-868",
        is_eu: false,
    },
    Country {
        code: "TN",
        name: "Tunisia",
        native_name: "تونس",
        continent: "Africa",
        default_locale: "ar-TN",
        default_currency: "TND",
        calling_code: "+216",
        is_eu: false,
    },
    Country {
        code: "TR",
        name: "Turkey",
        native_name: "Türkiye",
        continent: "Asia",
        default_locale: "tr-TR",
        default_currency: "TRY",
        calling_code: "+90",
        is_eu: false,
    },
    Country {
        code: "TM",
        name: "Turkmenistan",
        native_name: "Türkmenistan",
        continent: "Asia",
        default_locale: "tk",
        default_currency: "TMT",
        calling_code: "+993",
        is_eu: false,
    },
    Country {
        code: "TV",
        name: "Tuvalu",
        native_name: "Tuvalu",
        continent: "Oceania",
        default_locale: "en-TV",
        default_currency: "AUD",
        calling_code: "+688",
        is_eu: false,
    },
    Country {
        code: "UG",
        name: "Uganda",
        native_name: "Uganda",
        continent: "Africa",
        default_locale: "en-UG",
        default_currency: "UGX",
        calling_code: "+256",
        is_eu: false,
    },
    Country {
        code: "UA",
        name: "Ukraine",
        native_name: "Україна",
        continent: "Europe",
        default_locale: "uk",
        default_currency: "UAH",
        calling_code: "+380",
        is_eu: false,
    },
    Country {
        code: "AE",
        name: "United Arab Emirates",
        native_name: "الإمارات العربية المتحدة",
        continent: "Asia",
        default_locale: "ar-AE",
        default_currency: "AED",
        calling_code: "+971",
        is_eu: false,
    },
    Country {
        code: "GB",
        name: "United Kingdom",
        native_name: "United Kingdom",
        continent: "Europe",
        default_locale: "en-GB",
        default_currency: "GBP",
        calling_code: "+44",
        is_eu: false,
    },
    Country {
        code: "US",
        name: "United States",
        native_name: "United States",
        continent: "North America",
        default_locale: "en-US",
        default_currency: "USD",
        calling_code: "+1",
        is_eu: false,
    },
    Country {
        code: "UY",
        name: "Uruguay",
        native_name: "Uruguay",
        continent: "South America",
        default_locale: "es-UY",
        default_currency: "UYU",
        calling_code: "+598",
        is_eu: false,
    },
    Country {
        code: "UZ",
        name: "Uzbekistan",
        native_name: "O'zbekiston",
        continent: "Asia",
        default_locale: "uz",
        default_currency: "UZS",
        calling_code: "+998",
        is_eu: false,
    },
    Country {
        code: "VU",
        name: "Vanuatu",
        native_name: "Vanuatu",
        continent: "Oceania",
        default_locale: "en-VU",
        default_currency: "VUV",
        calling_code: "+678",
        is_eu: false,
    },
    Country {
        code: "VA",
        name: "Vatican City",
        native_name: "Città del Vaticano",
        continent: "Europe",
        default_locale: "it-VA",
        default_currency: "EUR",
        calling_code: "+379",
        is_eu: false,
    },
    Country {
        code: "VE",
        name: "Venezuela",
        native_name: "Venezuela",
        continent: "South America",
        default_locale: "es-VE",
        default_currency: "VES",
        calling_code: "+58",
        is_eu: false,
    },
    Country {
        code: "VN",
        name: "Vietnam",
        native_name: "Việt Nam",
        continent: "Asia",
        default_locale: "vi",
        default_currency: "VND",
        calling_code: "+84",
        is_eu: false,
    },
    Country {
        code: "YE",
        name: "Yemen",
        native_name: "اليمن",
        continent: "Asia",
        default_locale: "ar-YE",
        default_currency: "YER",
        calling_code: "+967",
        is_eu: false,
    },
    Country {
        code: "ZM",
        name: "Zambia",
        native_name: "Zambia",
        continent: "Africa",
        default_locale: "en-ZM",
        default_currency: "ZMW",
        calling_code: "+260",
        is_eu: false,
    },
    Country {
        code: "ZW",
        name: "Zimbabwe",
        native_name: "Zimbabwe",
        continent: "Africa",
        default_locale: "en-ZW",
        default_currency: "ZWL",
        calling_code: "+263",
        is_eu: false,
    },
];
