/// Comprehensive ISO 4217 currency registry.
///
/// Contains all globally active currencies with their formatting parameters,
/// symbols, and minor unit exponents (decimal digits).
use super::Currency;

pub const ALL_CURRENCIES: &[Currency] = &[
    Currency {
        code: "AED",
        numeric: 784,
        name: "UAE Dirham",
        symbol: "د.إ",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "AFN",
        numeric: 971,
        name: "Afghani",
        symbol: "؋",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "ALL",
        numeric: 8,
        name: "Lek",
        symbol: "L",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "AMD",
        numeric: 51,
        name: "Armenian Dram",
        symbol: "֏",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "ANG",
        numeric: 532,
        name: "Netherlands Antillean Guilder",
        symbol: "ƒ",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "AOA",
        numeric: 973,
        name: "Kwanza",
        symbol: "Kz",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "ARS",
        numeric: 32,
        name: "Argentine Peso",
        symbol: "$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "AUD",
        numeric: 36,
        name: "Australian Dollar",
        symbol: "A$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "AWG",
        numeric: 533,
        name: "Aruban Florin",
        symbol: "ƒ",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "AZN",
        numeric: 944,
        name: "Azerbaijan Manat",
        symbol: "₼",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "BAM",
        numeric: 977,
        name: "Convertible Mark",
        symbol: "KM",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "BBD",
        numeric: 52,
        name: "Barbados Dollar",
        symbol: "Bds$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "BDT",
        numeric: 50,
        name: "Taka",
        symbol: "৳",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "BGN",
        numeric: 975,
        name: "Bulgarian Lev",
        symbol: "лв.",
        decimals: 2,
        symbol_before: false,
    },
    Currency {
        code: "BHD",
        numeric: 48,
        name: "Bahraini Dinar",
        symbol: ".د.ب",
        decimals: 3,
        symbol_before: true,
    },
    Currency {
        code: "BIF",
        numeric: 108,
        name: "Burundi Franc",
        symbol: "FBu",
        decimals: 0,
        symbol_before: true,
    },
    Currency {
        code: "BMD",
        numeric: 60,
        name: "Bermudian Dollar",
        symbol: "BD$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "BND",
        numeric: 96,
        name: "Brunei Dollar",
        symbol: "B$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "BOB",
        numeric: 68,
        name: "Boliviano",
        symbol: "Bs.",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "BRL",
        numeric: 986,
        name: "Brazilian Real",
        symbol: "R$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "BSD",
        numeric: 44,
        name: "Bahamian Dollar",
        symbol: "B$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "BTN",
        numeric: 64,
        name: "Ngultrum",
        symbol: "Nu.",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "BWP",
        numeric: 72,
        name: "Pula",
        symbol: "P",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "BYN",
        numeric: 933,
        name: "Belarusian Ruble",
        symbol: "Br",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "BZD",
        numeric: 84,
        name: "Belize Dollar",
        symbol: "BZ$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "CAD",
        numeric: 124,
        name: "Canadian Dollar",
        symbol: "C$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "CDF",
        numeric: 976,
        name: "Congolese Franc",
        symbol: "FC",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "CHF",
        numeric: 756,
        name: "Swiss Franc",
        symbol: "Fr.",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "CLP",
        numeric: 152,
        name: "Chilean Peso",
        symbol: "$",
        decimals: 0,
        symbol_before: true,
    },
    Currency {
        code: "CNY",
        numeric: 156,
        name: "Yuan Renminbi",
        symbol: "¥",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "COP",
        numeric: 170,
        name: "Colombian Peso",
        symbol: "$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "CRC",
        numeric: 188,
        name: "Costa Rican Colon",
        symbol: "₡",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "CUP",
        numeric: 192,
        name: "Cuban Peso",
        symbol: "$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "CVE",
        numeric: 132,
        name: "Cabo Verde Escudo",
        symbol: "$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "CZK",
        numeric: 203,
        name: "Czech Koruna",
        symbol: "Kč",
        decimals: 2,
        symbol_before: false,
    },
    Currency {
        code: "DJF",
        numeric: 262,
        name: "Djibouti Franc",
        symbol: "Fdj",
        decimals: 0,
        symbol_before: true,
    },
    Currency {
        code: "DKK",
        numeric: 208,
        name: "Danish Krone",
        symbol: "kr.",
        decimals: 2,
        symbol_before: false,
    },
    Currency {
        code: "DOP",
        numeric: 214,
        name: "Dominican Peso",
        symbol: "RD$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "DZD",
        numeric: 12,
        name: "Algerian Dinar",
        symbol: "د.ج",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "EGP",
        numeric: 818,
        name: "Egyptian Pound",
        symbol: "ج.م",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "ERN",
        numeric: 232,
        name: "Nakfa",
        symbol: "Nfk",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "ETB",
        numeric: 230,
        name: "Ethiopian Birr",
        symbol: "Br",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "EUR",
        numeric: 978,
        name: "Euro",
        symbol: "€",
        decimals: 2,
        symbol_before: false,
    },
    Currency {
        code: "FJD",
        numeric: 242,
        name: "Fiji Dollar",
        symbol: "FJ$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "FKP",
        numeric: 238,
        name: "Falkland Islands Pound",
        symbol: "£",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "GBP",
        numeric: 826,
        name: "Pound Sterling",
        symbol: "£",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "GEL",
        numeric: 981,
        name: "Lari",
        symbol: "₾",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "GHS",
        numeric: 936,
        name: "Ghana Cedi",
        symbol: "₵",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "GIP",
        numeric: 292,
        name: "Gibraltar Pound",
        symbol: "£",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "GMD",
        numeric: 270,
        name: "Dalasi",
        symbol: "D",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "GNF",
        numeric: 324,
        name: "Guinean Franc",
        symbol: "FG",
        decimals: 0,
        symbol_before: true,
    },
    Currency {
        code: "GTQ",
        numeric: 320,
        name: "Quetzal",
        symbol: "Q",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "GYD",
        numeric: 328,
        name: "Guyana Dollar",
        symbol: "G$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "HKD",
        numeric: 344,
        name: "Hong Kong Dollar",
        symbol: "HK$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "HNL",
        numeric: 340,
        name: "Lempira",
        symbol: "L",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "HRK",
        numeric: 191,
        name: "Kuna",
        symbol: "kn",
        decimals: 2,
        symbol_before: false,
    },
    Currency {
        code: "HTG",
        numeric: 332,
        name: "Gourde",
        symbol: "G",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "HUF",
        numeric: 348,
        name: "Forint",
        symbol: "Ft",
        decimals: 2,
        symbol_before: false,
    },
    Currency {
        code: "IDR",
        numeric: 360,
        name: "Rupiah",
        symbol: "Rp",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "ILS",
        numeric: 376,
        name: "New Israeli Sheqel",
        symbol: "₪",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "INR",
        numeric: 356,
        name: "Indian Rupee",
        symbol: "₹",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "IQD",
        numeric: 368,
        name: "Iraqi Dinar",
        symbol: "ع.د",
        decimals: 3,
        symbol_before: true,
    },
    Currency {
        code: "IRR",
        numeric: 364,
        name: "Iranian Rial",
        symbol: "﷼",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "ISK",
        numeric: 352,
        name: "Iceland Krona",
        symbol: "kr",
        decimals: 0,
        symbol_before: false,
    },
    Currency {
        code: "JMD",
        numeric: 388,
        name: "Jamaican Dollar",
        symbol: "J$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "JOD",
        numeric: 400,
        name: "Jordanian Dinar",
        symbol: "د.أ",
        decimals: 3,
        symbol_before: true,
    },
    Currency {
        code: "JPY",
        numeric: 392,
        name: "Yen",
        symbol: "¥",
        decimals: 0,
        symbol_before: true,
    },
    Currency {
        code: "KES",
        numeric: 404,
        name: "Kenyan Shilling",
        symbol: "KSh",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "KGS",
        numeric: 417,
        name: "Som",
        symbol: "с",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "KHR",
        numeric: 116,
        name: "Riel",
        symbol: "៛",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "KMF",
        numeric: 174,
        name: "Comorian Franc",
        symbol: "CF",
        decimals: 0,
        symbol_before: true,
    },
    Currency {
        code: "KPW",
        numeric: 408,
        name: "North Korean Won",
        symbol: "₩",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "KRW",
        numeric: 410,
        name: "Won",
        symbol: "₩",
        decimals: 0,
        symbol_before: true,
    },
    Currency {
        code: "KWD",
        numeric: 414,
        name: "Kuwaiti Dinar",
        symbol: "د.ك",
        decimals: 3,
        symbol_before: true,
    },
    Currency {
        code: "KYD",
        numeric: 136,
        name: "Cayman Islands Dollar",
        symbol: "CI$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "KZT",
        numeric: 398,
        name: "Tenge",
        symbol: "₸",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "LAK",
        numeric: 418,
        name: "Lao Kip",
        symbol: "₭",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "LBP",
        numeric: 422,
        name: "Lebanese Pound",
        symbol: "ل.ل",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "LKR",
        numeric: 144,
        name: "Sri Lanka Rupee",
        symbol: "රු.",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "LRD",
        numeric: 430,
        name: "Liberian Dollar",
        symbol: "L$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "LSL",
        numeric: 426,
        name: "Loti",
        symbol: "L",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "LYD",
        numeric: 434,
        name: "Libyan Dinar",
        symbol: "ل.د",
        decimals: 3,
        symbol_before: true,
    },
    Currency {
        code: "MAD",
        numeric: 504,
        name: "Moroccan Dirham",
        symbol: "د.م.",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "MDL",
        numeric: 498,
        name: "Moldovan Leu",
        symbol: "L",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "MGA",
        numeric: 969,
        name: "Malagasy Ariary",
        symbol: "Ar",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "MKD",
        numeric: 807,
        name: "Denar",
        symbol: "ден",
        decimals: 2,
        symbol_before: false,
    },
    Currency {
        code: "MMK",
        numeric: 104,
        name: "Kyat",
        symbol: "K",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "MNT",
        numeric: 496,
        name: "Tugrik",
        symbol: "₮",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "MOP",
        numeric: 446,
        name: "Pataca",
        symbol: "MOP$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "MRU",
        numeric: 929,
        name: "Ouguiya",
        symbol: "UM",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "MUR",
        numeric: 480,
        name: "Mauritius Rupee",
        symbol: "₨",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "MVR",
        numeric: 462,
        name: "Rufiyaa",
        symbol: "ރ.",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "MWK",
        numeric: 454,
        name: "Malawi Kwacha",
        symbol: "MK",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "MXN",
        numeric: 484,
        name: "Mexican Peso",
        symbol: "Mex$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "MYR",
        numeric: 458,
        name: "Malaysian Ringgit",
        symbol: "RM",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "MZN",
        numeric: 943,
        name: "Mozambique Metical",
        symbol: "MT",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "NAD",
        numeric: 516,
        name: "Namibia Dollar",
        symbol: "N$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "NGN",
        numeric: 566,
        name: "Naira",
        symbol: "₦",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "NIO",
        numeric: 558,
        name: "Cordoba Oro",
        symbol: "C$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "NOK",
        numeric: 578,
        name: "Norwegian Krone",
        symbol: "kr",
        decimals: 2,
        symbol_before: false,
    },
    Currency {
        code: "NPR",
        numeric: 524,
        name: "Nepalese Rupee",
        symbol: "रू",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "NZD",
        numeric: 554,
        name: "New Zealand Dollar",
        symbol: "NZ$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "OMR",
        numeric: 512,
        name: "Rial Omani",
        symbol: "ر.ع.",
        decimals: 3,
        symbol_before: true,
    },
    Currency {
        code: "PAB",
        numeric: 590,
        name: "Balboa",
        symbol: "B/.",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "PEN",
        numeric: 604,
        name: "Sol",
        symbol: "S/",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "PGK",
        numeric: 598,
        name: "Kina",
        symbol: "K",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "PHP",
        numeric: 608,
        name: "Philippine Peso",
        symbol: "₱",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "PKR",
        numeric: 586,
        name: "Pakistan Rupee",
        symbol: "Rs.",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "PLN",
        numeric: 985,
        name: "Zloty",
        symbol: "zł",
        decimals: 2,
        symbol_before: false,
    },
    Currency {
        code: "PYG",
        numeric: 600,
        name: "Guarani",
        symbol: "₲",
        decimals: 0,
        symbol_before: true,
    },
    Currency {
        code: "QAR",
        numeric: 634,
        name: "Qatari Rial",
        symbol: "ر.ق",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "RON",
        numeric: 946,
        name: "Romanian Leu",
        symbol: "lei",
        decimals: 2,
        symbol_before: false,
    },
    Currency {
        code: "RSD",
        numeric: 941,
        name: "Serbian Dinar",
        symbol: "дин",
        decimals: 2,
        symbol_before: false,
    },
    Currency {
        code: "RUB",
        numeric: 643,
        name: "Russian Ruble",
        symbol: "₽",
        decimals: 2,
        symbol_before: false,
    },
    Currency {
        code: "RWF",
        numeric: 646,
        name: "Rwanda Franc",
        symbol: "FRw",
        decimals: 0,
        symbol_before: true,
    },
    Currency {
        code: "SAR",
        numeric: 682,
        name: "Saudi Riyal",
        symbol: "ر.س",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "SBD",
        numeric: 90,
        name: "Solomon Islands Dollar",
        symbol: "SI$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "SCR",
        numeric: 690,
        name: "Seychelles Rupee",
        symbol: "₨",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "SDG",
        numeric: 938,
        name: "Sudanese Pound",
        symbol: "ج.س.",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "SEK",
        numeric: 752,
        name: "Swedish Krona",
        symbol: "kr",
        decimals: 2,
        symbol_before: false,
    },
    Currency {
        code: "SGD",
        numeric: 702,
        name: "Singapore Dollar",
        symbol: "S$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "SHP",
        numeric: 654,
        name: "Saint Helena Pound",
        symbol: "£",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "SLE",
        numeric: 925,
        name: "Leone",
        symbol: "Le",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "SLL",
        numeric: 694,
        name: "Leone (old)",
        symbol: "Le",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "SOS",
        numeric: 706,
        name: "Somali Shilling",
        symbol: "Sh.So.",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "SRD",
        numeric: 968,
        name: "Surinam Dollar",
        symbol: "Sr$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "SSP",
        numeric: 728,
        name: "South Sudanese Pound",
        symbol: "£",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "STN",
        numeric: 930,
        name: "Dobra",
        symbol: "Db",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "SYP",
        numeric: 760,
        name: "Syrian Pound",
        symbol: "ل.س",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "SZL",
        numeric: 748,
        name: "Lilangeni",
        symbol: "E",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "THB",
        numeric: 764,
        name: "Baht",
        symbol: "฿",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "TJS",
        numeric: 972,
        name: "Somoni",
        symbol: "ЅМ",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "TMT",
        numeric: 934,
        name: "Turkmenistan New Manat",
        symbol: "m",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "TND",
        numeric: 788,
        name: "Tunisian Dinar",
        symbol: "د.ت",
        decimals: 3,
        symbol_before: true,
    },
    Currency {
        code: "TOP",
        numeric: 776,
        name: "Pa'anga",
        symbol: "T$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "TRY",
        numeric: 949,
        name: "Turkish Lira",
        symbol: "₺",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "TTD",
        numeric: 780,
        name: "Trinidad and Tobago Dollar",
        symbol: "TT$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "TWD",
        numeric: 901,
        name: "New Taiwan Dollar",
        symbol: "NT$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "TZS",
        numeric: 834,
        name: "Tanzanian Shilling",
        symbol: "TSh",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "UAH",
        numeric: 980,
        name: "Hryvnia",
        symbol: "₴",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "UGX",
        numeric: 800,
        name: "Uganda Shilling",
        symbol: "USh",
        decimals: 0,
        symbol_before: true,
    },
    Currency {
        code: "USD",
        numeric: 840,
        name: "US Dollar",
        symbol: "$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "UYU",
        numeric: 858,
        name: "Peso Uruguayo",
        symbol: "$U",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "UZS",
        numeric: 860,
        name: "Uzbekistan Sum",
        symbol: "so'm",
        decimals: 2,
        symbol_before: false,
    },
    Currency {
        code: "VES",
        numeric: 928,
        name: "Bolívar Soberano",
        symbol: "Bs.",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "VND",
        numeric: 704,
        name: "Dong",
        symbol: "₫",
        decimals: 0,
        symbol_before: true,
    },
    Currency {
        code: "VUV",
        numeric: 548,
        name: "Vatu",
        symbol: "VT",
        decimals: 0,
        symbol_before: true,
    },
    Currency {
        code: "WST",
        numeric: 882,
        name: "Tala",
        symbol: "WS$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "XAF",
        numeric: 950,
        name: "CFA Franc BEAC",
        symbol: "FCFA",
        decimals: 0,
        symbol_before: false,
    },
    Currency {
        code: "XCD",
        numeric: 951,
        name: "East Caribbean Dollar",
        symbol: "EC$",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "XOF",
        numeric: 952,
        name: "CFA Franc BCEAO",
        symbol: "CFA",
        decimals: 0,
        symbol_before: false,
    },
    Currency {
        code: "XPF",
        numeric: 953,
        name: "CFP Franc",
        symbol: "₣",
        decimals: 0,
        symbol_before: false,
    },
    Currency {
        code: "YER",
        numeric: 886,
        name: "Yemeni Rial",
        symbol: "ر.ي",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "ZAR",
        numeric: 710,
        name: "Rand",
        symbol: "R",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "ZMW",
        numeric: 967,
        name: "Zambian Kwacha",
        symbol: "ZK",
        decimals: 2,
        symbol_before: true,
    },
    Currency {
        code: "ZWL",
        numeric: 932,
        name: "Zimbabwe Dollar",
        symbol: "Z$",
        decimals: 2,
        symbol_before: true,
    },
];
