/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/occupational-health/*
 * Consolidates 30 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as exams from '@/lib/api-handlers/occupational-health/exams';
import * as exposures from '@/lib/api-handlers/occupational-health/exposures';
import * as metrics from '@/lib/api-handlers/occupational-health/metrics';
import * as stats from '@/lib/api-handlers/occupational-health/stats';
import * as surveillances from '@/lib/api-handlers/occupational-health/surveillances';
import * as vaccinations from '@/lib/api-handlers/occupational-health/vaccinations';
import * as index from '@/lib/api-handlers/occupational-health/index';
import * as exams___id__cancel from '@/lib/api-handlers/occupational-health/exams___id__cancel';
import * as exams___id__complete from '@/lib/api-handlers/occupational-health/exams___id__complete';
import * as exams___id__fail from '@/lib/api-handlers/occupational-health/exams___id__fail';
import * as exams___id__no_show from '@/lib/api-handlers/occupational-health/exams___id__no_show';
import * as exams___id__schedule from '@/lib/api-handlers/occupational-health/exams___id__schedule';
import * as exposures___id__archive from '@/lib/api-handlers/occupational-health/exposures___id__archive';
import * as exposures___id__mitigate from '@/lib/api-handlers/occupational-health/exposures___id__mitigate';
import * as exposures___id__monitor from '@/lib/api-handlers/occupational-health/exposures___id__monitor';
import * as exposures___id__resolve from '@/lib/api-handlers/occupational-health/exposures___id__resolve';
import * as surveillances___id__cancel from '@/lib/api-handlers/occupational-health/surveillances___id__cancel';
import * as surveillances___id__complete from '@/lib/api-handlers/occupational-health/surveillances___id__complete';
import * as surveillances___id__overdue from '@/lib/api-handlers/occupational-health/surveillances___id__overdue';
import * as surveillances___id__schedule from '@/lib/api-handlers/occupational-health/surveillances___id__schedule';
import * as surveillances___id__start from '@/lib/api-handlers/occupational-health/surveillances___id__start';
import * as vaccinations___id__administer from '@/lib/api-handlers/occupational-health/vaccinations___id__administer';
import * as vaccinations___id__boost from '@/lib/api-handlers/occupational-health/vaccinations___id__boost';
import * as vaccinations___id__expire from '@/lib/api-handlers/occupational-health/vaccinations___id__expire';
import * as vaccinations___id__refuse from '@/lib/api-handlers/occupational-health/vaccinations___id__refuse';
import * as exams___id from '@/lib/api-handlers/occupational-health/exams___id';
import * as exposures___id from '@/lib/api-handlers/occupational-health/exposures___id';
import * as surveillances___id from '@/lib/api-handlers/occupational-health/surveillances___id';
import * as vaccinations___id from '@/lib/api-handlers/occupational-health/vaccinations___id';
import * as _id from '@/lib/api-handlers/occupational-health/_id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["exams"], paramNames: [], handlers: { GET: exams.GET, POST: exams.POST } },
  { segments: ["exposures"], paramNames: [], handlers: { GET: exposures.GET, POST: exposures.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["surveillances"], paramNames: [], handlers: { GET: surveillances.GET, POST: surveillances.POST } },
  { segments: ["vaccinations"], paramNames: [], handlers: { GET: vaccinations.GET, POST: vaccinations.POST } },
  { segments: [], paramNames: [], handlers: { GET: index.GET, POST: index.POST } },
  { segments: ["exams","[id]","cancel"], paramNames: ["id"], handlers: { POST: exams___id__cancel.POST } },
  { segments: ["exams","[id]","complete"], paramNames: ["id"], handlers: { POST: exams___id__complete.POST } },
  { segments: ["exams","[id]","fail"], paramNames: ["id"], handlers: { POST: exams___id__fail.POST } },
  { segments: ["exams","[id]","no-show"], paramNames: ["id"], handlers: { POST: exams___id__no_show.POST } },
  { segments: ["exams","[id]","schedule"], paramNames: ["id"], handlers: { POST: exams___id__schedule.POST } },
  { segments: ["exposures","[id]","archive"], paramNames: ["id"], handlers: { POST: exposures___id__archive.POST } },
  { segments: ["exposures","[id]","mitigate"], paramNames: ["id"], handlers: { POST: exposures___id__mitigate.POST } },
  { segments: ["exposures","[id]","monitor"], paramNames: ["id"], handlers: { POST: exposures___id__monitor.POST } },
  { segments: ["exposures","[id]","resolve"], paramNames: ["id"], handlers: { POST: exposures___id__resolve.POST } },
  { segments: ["surveillances","[id]","cancel"], paramNames: ["id"], handlers: { POST: surveillances___id__cancel.POST } },
  { segments: ["surveillances","[id]","complete"], paramNames: ["id"], handlers: { POST: surveillances___id__complete.POST } },
  { segments: ["surveillances","[id]","overdue"], paramNames: ["id"], handlers: { POST: surveillances___id__overdue.POST } },
  { segments: ["surveillances","[id]","schedule"], paramNames: ["id"], handlers: { POST: surveillances___id__schedule.POST } },
  { segments: ["surveillances","[id]","start"], paramNames: ["id"], handlers: { POST: surveillances___id__start.POST } },
  { segments: ["vaccinations","[id]","administer"], paramNames: ["id"], handlers: { POST: vaccinations___id__administer.POST } },
  { segments: ["vaccinations","[id]","boost"], paramNames: ["id"], handlers: { POST: vaccinations___id__boost.POST } },
  { segments: ["vaccinations","[id]","expire"], paramNames: ["id"], handlers: { POST: vaccinations___id__expire.POST } },
  { segments: ["vaccinations","[id]","refuse"], paramNames: ["id"], handlers: { POST: vaccinations___id__refuse.POST } },
  { segments: ["exams","[id]"], paramNames: ["id"], handlers: { GET: exams___id.GET, PATCH: exams___id.PATCH, DELETE: exams___id.DELETE } },
  { segments: ["exposures","[id]"], paramNames: ["id"], handlers: { GET: exposures___id.GET, PATCH: exposures___id.PATCH, DELETE: exposures___id.DELETE } },
  { segments: ["surveillances","[id]"], paramNames: ["id"], handlers: { GET: surveillances___id.GET, PATCH: surveillances___id.PATCH, DELETE: surveillances___id.DELETE } },
  { segments: ["vaccinations","[id]"], paramNames: ["id"], handlers: { GET: vaccinations___id.GET, PATCH: vaccinations___id.PATCH, DELETE: vaccinations___id.DELETE } },
  { segments: ["[id]"], paramNames: ["id"], handlers: { GET: _id.GET, PATCH: _id.PATCH, DELETE: _id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path?: string[] }> },
) {
  const { path = [] } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
