---
- name: Setup Lazynext Bare-Metal Nodes
  hosts: all
  become: yes
  roles:
    - common
    - docker
    - role: nvidia
      when: "'gpu_nodes' in group_names"
    - k8s

- name: Deploy Monitoring Stack
  hosts: masters
  become: yes
  roles:
    - monitoring
