/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/procurement-v2/*
 * Consolidates 29 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as purchase_orders__by_status from '@/lib/api-handlers/procurement-v2/purchase_orders__by_status';
import * as purchase_orders__by_vendor from '@/lib/api-handlers/procurement-v2/purchase_orders__by_vendor';
import * as purchase_orders__open from '@/lib/api-handlers/procurement-v2/purchase_orders__open';
import * as purchase_orders__pending from '@/lib/api-handlers/procurement-v2/purchase_orders__pending';
import * as purchase_orders__spend from '@/lib/api-handlers/procurement-v2/purchase_orders__spend';
import * as purchase_orders__stats from '@/lib/api-handlers/procurement-v2/purchase_orders__stats';
import * as rfqs__open from '@/lib/api-handlers/procurement-v2/rfqs__open';
import * as rfqs__stats from '@/lib/api-handlers/procurement-v2/rfqs__stats';
import * as scorecards__grade_distribution from '@/lib/api-handlers/procurement-v2/scorecards__grade_distribution';
import * as scorecards__stats from '@/lib/api-handlers/procurement-v2/scorecards__stats';
import * as scorecards__top from '@/lib/api-handlers/procurement-v2/scorecards__top';
import * as purchase_orders from '@/lib/api-handlers/procurement-v2/purchase_orders';
import * as rfqs from '@/lib/api-handlers/procurement-v2/rfqs';
import * as scorecards from '@/lib/api-handlers/procurement-v2/scorecards';
import * as stats from '@/lib/api-handlers/procurement-v2/stats';
import * as purchase_orders___id__approve from '@/lib/api-handlers/procurement-v2/purchase_orders___id__approve';
import * as purchase_orders___id__cancel from '@/lib/api-handlers/procurement-v2/purchase_orders___id__cancel';
import * as purchase_orders___id__receive from '@/lib/api-handlers/procurement-v2/purchase_orders___id__receive';
import * as purchase_orders___id__reject from '@/lib/api-handlers/procurement-v2/purchase_orders___id__reject';
import * as purchase_orders___id__send from '@/lib/api-handlers/procurement-v2/purchase_orders___id__send';
import * as purchase_orders___id__submit from '@/lib/api-handlers/procurement-v2/purchase_orders___id__submit';
import * as rfqs___id__cancel from '@/lib/api-handlers/procurement-v2/rfqs___id__cancel';
import * as rfqs___id__close from '@/lib/api-handlers/procurement-v2/rfqs___id__close';
import * as rfqs___id__quotes from '@/lib/api-handlers/procurement-v2/rfqs___id__quotes';
import * as purchase_orders___id from '@/lib/api-handlers/procurement-v2/purchase_orders___id';
import * as rfqs___id from '@/lib/api-handlers/procurement-v2/rfqs___id';
import * as scorecards___id from '@/lib/api-handlers/procurement-v2/scorecards___id';
import * as rfqs___id__quotes___quoteId__accept from '@/lib/api-handlers/procurement-v2/rfqs___id__quotes___quoteId__accept';
import * as rfqs___id__quotes___quoteId__reject from '@/lib/api-handlers/procurement-v2/rfqs___id__quotes___quoteId__reject';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["purchase-orders","by-status"], paramNames: [], handlers: { GET: purchase_orders__by_status.GET } },
  { segments: ["purchase-orders","by-vendor"], paramNames: [], handlers: { GET: purchase_orders__by_vendor.GET } },
  { segments: ["purchase-orders","open"], paramNames: [], handlers: { GET: purchase_orders__open.GET } },
  { segments: ["purchase-orders","pending"], paramNames: [], handlers: { GET: purchase_orders__pending.GET } },
  { segments: ["purchase-orders","spend"], paramNames: [], handlers: { GET: purchase_orders__spend.GET } },
  { segments: ["purchase-orders","stats"], paramNames: [], handlers: { GET: purchase_orders__stats.GET } },
  { segments: ["rfqs","open"], paramNames: [], handlers: { GET: rfqs__open.GET } },
  { segments: ["rfqs","stats"], paramNames: [], handlers: { GET: rfqs__stats.GET } },
  { segments: ["scorecards","grade-distribution"], paramNames: [], handlers: { GET: scorecards__grade_distribution.GET } },
  { segments: ["scorecards","stats"], paramNames: [], handlers: { GET: scorecards__stats.GET } },
  { segments: ["scorecards","top"], paramNames: [], handlers: { GET: scorecards__top.GET } },
  { segments: ["purchase-orders"], paramNames: [], handlers: { GET: purchase_orders.GET, POST: purchase_orders.POST } },
  { segments: ["rfqs"], paramNames: [], handlers: { GET: rfqs.GET, POST: rfqs.POST } },
  { segments: ["scorecards"], paramNames: [], handlers: { GET: scorecards.GET, POST: scorecards.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["purchase-orders","[id]","approve"], paramNames: ["id"], handlers: { POST: purchase_orders___id__approve.POST } },
  { segments: ["purchase-orders","[id]","cancel"], paramNames: ["id"], handlers: { POST: purchase_orders___id__cancel.POST } },
  { segments: ["purchase-orders","[id]","receive"], paramNames: ["id"], handlers: { POST: purchase_orders___id__receive.POST } },
  { segments: ["purchase-orders","[id]","reject"], paramNames: ["id"], handlers: { POST: purchase_orders___id__reject.POST } },
  { segments: ["purchase-orders","[id]","send"], paramNames: ["id"], handlers: { POST: purchase_orders___id__send.POST } },
  { segments: ["purchase-orders","[id]","submit"], paramNames: ["id"], handlers: { POST: purchase_orders___id__submit.POST } },
  { segments: ["rfqs","[id]","cancel"], paramNames: ["id"], handlers: { POST: rfqs___id__cancel.POST } },
  { segments: ["rfqs","[id]","close"], paramNames: ["id"], handlers: { POST: rfqs___id__close.POST } },
  { segments: ["rfqs","[id]","quotes"], paramNames: ["id"], handlers: { GET: rfqs___id__quotes.GET, POST: rfqs___id__quotes.POST } },
  { segments: ["purchase-orders","[id]"], paramNames: ["id"], handlers: { GET: purchase_orders___id.GET, PATCH: purchase_orders___id.PATCH, DELETE: purchase_orders___id.DELETE } },
  { segments: ["rfqs","[id]"], paramNames: ["id"], handlers: { GET: rfqs___id.GET, PATCH: rfqs___id.PATCH, DELETE: rfqs___id.DELETE } },
  { segments: ["scorecards","[id]"], paramNames: ["id"], handlers: { GET: scorecards___id.GET, PATCH: scorecards___id.PATCH, DELETE: scorecards___id.DELETE } },
  { segments: ["rfqs","[id]","quotes","[quoteId]","accept"], paramNames: ["id","quoteId"], handlers: { POST: rfqs___id__quotes___quoteId__accept.POST } },
  { segments: ["rfqs","[id]","quotes","[quoteId]","reject"], paramNames: ["id","quoteId"], handlers: { POST: rfqs___id__quotes___quoteId__reject.POST } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
