/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/sustainability/*
 * Consolidates 17 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as assessments from '@/lib/api-handlers/sustainability/assessments';
import * as carbon_emissions from '@/lib/api-handlers/sustainability/carbon_emissions';
import * as carbon_footprint from '@/lib/api-handlers/sustainability/carbon_footprint';
import * as esg_score from '@/lib/api-handlers/sustainability/esg_score';
import * as initiatives from '@/lib/api-handlers/sustainability/initiatives';
import * as metrics from '@/lib/api-handlers/sustainability/metrics';
import * as metrics_summary from '@/lib/api-handlers/sustainability/metrics_summary';
import * as reports from '@/lib/api-handlers/sustainability/reports';
import * as stats from '@/lib/api-handlers/sustainability/stats';
import * as targets from '@/lib/api-handlers/sustainability/targets';
import * as reports___id__publish from '@/lib/api-handlers/sustainability/reports___id__publish';
import * as assessments___id from '@/lib/api-handlers/sustainability/assessments___id';
import * as carbon_emissions___id from '@/lib/api-handlers/sustainability/carbon_emissions___id';
import * as initiatives___id from '@/lib/api-handlers/sustainability/initiatives___id';
import * as metrics___id from '@/lib/api-handlers/sustainability/metrics___id';
import * as reports___id from '@/lib/api-handlers/sustainability/reports___id';
import * as targets___id from '@/lib/api-handlers/sustainability/targets___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["assessments"], paramNames: [], handlers: { GET: assessments.GET, POST: assessments.POST } },
  { segments: ["carbon-emissions"], paramNames: [], handlers: { GET: carbon_emissions.GET, POST: carbon_emissions.POST } },
  { segments: ["carbon-footprint"], paramNames: [], handlers: { GET: carbon_footprint.GET } },
  { segments: ["esg-score"], paramNames: [], handlers: { GET: esg_score.GET } },
  { segments: ["initiatives"], paramNames: [], handlers: { GET: initiatives.GET, POST: initiatives.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET, POST: metrics.POST } },
  { segments: ["metrics-summary"], paramNames: [], handlers: { GET: metrics_summary.GET } },
  { segments: ["reports"], paramNames: [], handlers: { GET: reports.GET, POST: reports.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["targets"], paramNames: [], handlers: { GET: targets.GET, POST: targets.POST } },
  { segments: ["reports","[id]","publish"], paramNames: ["id"], handlers: { POST: reports___id__publish.POST } },
  { segments: ["assessments","[id]"], paramNames: ["id"], handlers: { GET: assessments___id.GET, PATCH: assessments___id.PATCH } },
  { segments: ["carbon-emissions","[id]"], paramNames: ["id"], handlers: { GET: carbon_emissions___id.GET, PATCH: carbon_emissions___id.PATCH, DELETE: carbon_emissions___id.DELETE } },
  { segments: ["initiatives","[id]"], paramNames: ["id"], handlers: { GET: initiatives___id.GET, PATCH: initiatives___id.PATCH, DELETE: initiatives___id.DELETE } },
  { segments: ["metrics","[id]"], paramNames: ["id"], handlers: { GET: metrics___id.GET, PATCH: metrics___id.PATCH, DELETE: metrics___id.DELETE } },
  { segments: ["reports","[id]"], paramNames: ["id"], handlers: { GET: reports___id.GET, PATCH: reports___id.PATCH } },
  { segments: ["targets","[id]"], paramNames: ["id"], handlers: { GET: targets___id.GET, PATCH: targets___id.PATCH, DELETE: targets___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
