/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/partners/*
 * Consolidates 15 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as comarketing from '@/lib/api-handlers/partners/comarketing';
import * as deals from '@/lib/api-handlers/partners/deals';
import * as metrics from '@/lib/api-handlers/partners/metrics';
import * as partners from '@/lib/api-handlers/partners/partners';
import * as programs from '@/lib/api-handlers/partners/programs';
import * as stats from '@/lib/api-handlers/partners/stats';
import * as tiers from '@/lib/api-handlers/partners/tiers';
import * as comarketing___id__complete from '@/lib/api-handlers/partners/comarketing___id__complete';
import * as deals___id__close from '@/lib/api-handlers/partners/deals___id__close';
import * as partners___id__upgrade from '@/lib/api-handlers/partners/partners___id__upgrade';
import * as comarketing___id from '@/lib/api-handlers/partners/comarketing___id';
import * as deals___id from '@/lib/api-handlers/partners/deals___id';
import * as partners___id from '@/lib/api-handlers/partners/partners___id';
import * as programs___id from '@/lib/api-handlers/partners/programs___id';
import * as tiers___id from '@/lib/api-handlers/partners/tiers___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["comarketing"], paramNames: [], handlers: { GET: comarketing.GET, POST: comarketing.POST } },
  { segments: ["deals"], paramNames: [], handlers: { GET: deals.GET, POST: deals.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["partners"], paramNames: [], handlers: { GET: partners.GET, POST: partners.POST } },
  { segments: ["programs"], paramNames: [], handlers: { GET: programs.GET, POST: programs.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["tiers"], paramNames: [], handlers: { GET: tiers.GET, POST: tiers.POST } },
  { segments: ["comarketing","[id]","complete"], paramNames: ["id"], handlers: { POST: comarketing___id__complete.POST } },
  { segments: ["deals","[id]","close"], paramNames: ["id"], handlers: { POST: deals___id__close.POST } },
  { segments: ["partners","[id]","upgrade"], paramNames: ["id"], handlers: { POST: partners___id__upgrade.POST } },
  { segments: ["comarketing","[id]"], paramNames: ["id"], handlers: { GET: comarketing___id.GET, PATCH: comarketing___id.PATCH } },
  { segments: ["deals","[id]"], paramNames: ["id"], handlers: { GET: deals___id.GET, PATCH: deals___id.PATCH } },
  { segments: ["partners","[id]"], paramNames: ["id"], handlers: { GET: partners___id.GET, PATCH: partners___id.PATCH, DELETE: partners___id.DELETE } },
  { segments: ["programs","[id]"], paramNames: ["id"], handlers: { GET: programs___id.GET, PATCH: programs___id.PATCH, DELETE: programs___id.DELETE } },
  { segments: ["tiers","[id]"], paramNames: ["id"], handlers: { GET: tiers___id.GET, PATCH: tiers___id.PATCH, DELETE: tiers___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
