import { Bot } from 'lucide-react';
import { auth } from '@/../auth';

export const dynamic = 'force-dynamic';

export default async function AiUsagePolicyPage() {
  const session = await auth().catch(() => null);
  const year = new Date().getFullYear();

  return (
    <div className="min-h-screen text-fg bg-app">
      <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
        <div
          className="flex items-center gap-3 mb-8 border-2 bg-surface p-4"
          style={{ borderColor: 'var(--c-ink)', borderRadius: 'var(--radius-sm)' }}
        >
          <Bot className="h-6 w-6 shrink-0" />
          <div>
            <h1 className="heading-display text-3xl">AI/Agent Usage Policy</h1>
            <p className="mt-1 text-sm text-fg-faint">Last updated: {year}</p>
          </div>
        </div>

        {session?.user?.name && (
          <p className="mb-6 text-sm text-fg-secondary">
            Signed in as {session.user.name}. This policy governs your use of AI features on Lazynext.
          </p>
        )}

        <div className="prose prose-neutral max-w-none text-sm leading-relaxed text-fg-secondary">
          <p>
            This AI/Agent Usage Policy governs the use of AI-powered features on the Lazynext
            platform, including content generation, AI agents, and automated workflows. AI generation
            is powered by Atlas Cloud and other provider models. By using AI features you agree to
            this policy. <strong className="text-fg">[REQUIRES COUNSEL]</strong>
          </p>
          <h2 className="text-lg font-semibold text-fg">1. Acceptable AI Use Cases</h2>
          <ul className="list-disc space-y-2 pl-5">
            <li>Generating marketing copy, ad scripts, and creative briefs for your brand.</li>
            <li>Producing storyboards, hooks, and content variants for A/B testing.</li>
            <li>Automating repetitive creative workflows within your authorized workspace.</li>
            <li>Using AI agents to manage tasks, schedules, and internal data you own.</li>
            <li>Analyzing performance data and generating insights for campaign optimization.</li>
          </ul>
          <h2 className="text-lg font-semibold text-fg">2. Prohibited AI Use Cases</h2>
          <ul className="list-disc space-y-2 pl-5">
            <li>Generating deepfakes or synthetic media that impersonate real people without consent.</li>
            <li>Creating misinformation, disinformation, or content designed to deceive the public.</li>
            <li>Harassment, bullying, or content that targets individuals or protected groups.</li>
            <li>Generating illegal content, including content that promotes illegal activities.</li>
            <li>Producing content that infringes on intellectual property rights.</li>
            <li>Using AI to circumvent safety controls, access controls, or rate limits.</li>
            <li>Deploying AI agents that operate without appropriate human oversight for high-risk decisions.</li>
          </ul>
          <h2 className="text-lg font-semibold text-fg">3. User Responsibility for AI-Generated Content</h2>
          <p>
            You are solely responsible for the prompts you submit, the content generated by AI features,
            and the actions taken by AI agents you create. You must review AI-generated content before
            publishing or distributing it. AI-generated content may contain inaccuracies, biases, or
            unintended outputs. <strong className="text-fg">[REQUIRES COUNSEL]</strong>
          </p>
          <h2 className="text-lg font-semibold text-fg">4. AI Agent Constraints</h2>
          <p>
            AI agents and automations you create operate under your account and workspace credentials.
            You are responsible for configuring appropriate instructions, tool access, and scope
            limitations. Agents that cause harm through unauthorized actions are your responsibility.
            We recommend human-in-the-loop review for automations that affect production systems,
            financial transactions, or external communications. <strong className="text-fg">[REQUIRES COUNSEL]</strong>
          </p>
          <h2 className="text-lg font-semibold text-fg">5. Data Used for AI Processing</h2>
          <p>
            When you use AI features, your inputs (prompts, images, documents) are sent to AI providers
            (Atlas Cloud and others) for processing. These providers may retain data temporarily for
            safety and quality purposes. We do not use your private workspace content to train AI models.
            See our Privacy Policy and subprocessor list for details. <strong className="text-fg">[REQUIRES COUNSEL]</strong>
          </p>
          <h2 className="text-lg font-semibold text-fg">6. Model Provider Disclosures</h2>
          <p>
            AI generation on Lazynext is powered by Atlas Cloud and other providers. Your use of AI
            features is also subject to the usage policies of these providers. We may restrict or modify
            AI features based on provider policy changes. Provider-specific terms apply to outputs
            generated using their models. <strong className="text-fg">[REQUIRES COUNSEL]</strong>
          </p>
          <h2 className="text-lg font-semibold text-fg">7. Human Oversight Requirements</h2>
          <ul className="list-disc space-y-2 pl-5">
            <li>Review AI-generated content before publishing or sending to external audiences.</li>
            <li>Maintain human-in-the-loop approval for automations affecting production systems.</li>
            <li>Verify AI-generated claims, statistics, and facts before public distribution.</li>
            <li>Monitor AI agent actions and intervene when outputs deviate from intent.</li>
          </ul>
          <h2 className="text-lg font-semibold text-fg">8. Reporting Violations</h2>
          <p>
            If you become aware of AI-generated content or agent behavior that violates this policy,
            report it promptly to{' '}
            <a href="mailto:ai-policy@lazynext.com" className="text-fg underline">ai-policy@lazynext.com</a>.
            We investigate reports and may suspend access for users who violate this policy.
            <strong className="text-fg"> [REQUIRES COUNSEL]</strong>
          </p>
          <h2 className="text-lg font-semibold text-fg">9. Changes to Policy</h2>
          <p>
            We may update this AI/Agent Usage Policy as AI technology and regulations evolve. Continued
            use of AI features after changes constitutes acceptance of the revised policy.
            <strong className="text-fg"> [REQUIRES COUNSEL]</strong>
          </p>
        </div>

        <div className="mt-12 pt-8 border-t-2" style={{ borderColor: 'var(--c-ink)' }}>
          <a href="/" className="text-sm text-fg-faint hover:text-fg transition">← Back to Lazynext</a>
        </div>
      </div>
    </div>
  );
}
