default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "ios/Lazynext.xcodeproj")
    build_app(workspace: "ios/Lazynext.xcworkspace", scheme: "Lazynext")
    upload_to_testflight
  end
end

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: 'beta')
  end
end
