/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/portfolio/*
 * Consolidates 12 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as allocations from '@/lib/api-handlers/portfolio/allocations';
import * as holdings from '@/lib/api-handlers/portfolio/holdings';
import * as metrics from '@/lib/api-handlers/portfolio/metrics';
import * as risks from '@/lib/api-handlers/portfolio/risks';
import * as stats from '@/lib/api-handlers/portfolio/stats';
import * as transactions from '@/lib/api-handlers/portfolio/transactions';
import * as allocations___id__rebalance from '@/lib/api-handlers/portfolio/allocations___id__rebalance';
import * as holdings___id__sell from '@/lib/api-handlers/portfolio/holdings___id__sell';
import * as allocations___id from '@/lib/api-handlers/portfolio/allocations___id';
import * as holdings___id from '@/lib/api-handlers/portfolio/holdings___id';
import * as risks___id from '@/lib/api-handlers/portfolio/risks___id';
import * as transactions___id from '@/lib/api-handlers/portfolio/transactions___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["allocations"], paramNames: [], handlers: { GET: allocations.GET, POST: allocations.POST } },
  { segments: ["holdings"], paramNames: [], handlers: { GET: holdings.GET, POST: holdings.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["risks"], paramNames: [], handlers: { GET: risks.GET, POST: risks.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["transactions"], paramNames: [], handlers: { GET: transactions.GET, POST: transactions.POST } },
  { segments: ["allocations","[id]","rebalance"], paramNames: ["id"], handlers: { POST: allocations___id__rebalance.POST } },
  { segments: ["holdings","[id]","sell"], paramNames: ["id"], handlers: { POST: holdings___id__sell.POST } },
  { segments: ["allocations","[id]"], paramNames: ["id"], handlers: { GET: allocations___id.GET, PATCH: allocations___id.PATCH, DELETE: allocations___id.DELETE } },
  { segments: ["holdings","[id]"], paramNames: ["id"], handlers: { GET: holdings___id.GET, PATCH: holdings___id.PATCH, DELETE: holdings___id.DELETE } },
  { segments: ["risks","[id]"], paramNames: ["id"], handlers: { GET: risks___id.GET, PATCH: risks___id.PATCH, DELETE: risks___id.DELETE } },
  { segments: ["transactions","[id]"], paramNames: ["id"], handlers: { GET: transactions___id.GET, PATCH: transactions___id.PATCH, DELETE: transactions___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
