/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/data/*
 * Consolidates 28 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as backup__cleanup from '@/lib/api-handlers/data/backup__cleanup';
import * as backup__retention from '@/lib/api-handlers/data/backup__retention';
import * as backup__schedule from '@/lib/api-handlers/data/backup__schedule';
import * as backup__stats from '@/lib/api-handlers/data/backup__stats';
import * as export__entities from '@/lib/api-handlers/data/export__entities';
import * as export__stats from '@/lib/api-handlers/data/export__stats';
import * as gdpr__anonymize from '@/lib/api-handlers/data/gdpr__anonymize';
import * as gdpr__consent from '@/lib/api-handlers/data/gdpr__consent';
import * as gdpr__delete from '@/lib/api-handlers/data/gdpr__delete';
import * as gdpr__export from '@/lib/api-handlers/data/gdpr__export';
import * as gdpr__inventory from '@/lib/api-handlers/data/gdpr__inventory';
import * as gdpr__requests from '@/lib/api-handlers/data/gdpr__requests';
import * as gdpr__stats from '@/lib/api-handlers/data/gdpr__stats';
import * as lineage__graph from '@/lib/api-handlers/data/lineage__graph';
import * as lineage__stats from '@/lib/api-handlers/data/lineage__stats';
import * as migration__templates from '@/lib/api-handlers/data/migration__templates';
import * as backup from '@/lib/api-handlers/data/backup';
import * as _export from '@/lib/api-handlers/data/export';
import * as lineage from '@/lib/api-handlers/data/lineage';
import * as migration from '@/lib/api-handlers/data/migration';
import * as backup___id__restore from '@/lib/api-handlers/data/backup___id__restore';
import * as export___id__download from '@/lib/api-handlers/data/export___id__download';
import * as export___id__run from '@/lib/api-handlers/data/export___id__run';
import * as gdpr__requests___id from '@/lib/api-handlers/data/gdpr__requests___id';
import * as migration___id__execute from '@/lib/api-handlers/data/migration___id__execute';
import * as backup___id from '@/lib/api-handlers/data/backup___id';
import * as export___id from '@/lib/api-handlers/data/export___id';
import * as migration___id from '@/lib/api-handlers/data/migration___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["backup","cleanup"], paramNames: [], handlers: { POST: backup__cleanup.POST } },
  { segments: ["backup","retention"], paramNames: [], handlers: { GET: backup__retention.GET, PATCH: backup__retention.PATCH } },
  { segments: ["backup","schedule"], paramNames: [], handlers: { GET: backup__schedule.GET, POST: backup__schedule.POST, DELETE: backup__schedule.DELETE } },
  { segments: ["backup","stats"], paramNames: [], handlers: { GET: backup__stats.GET } },
  { segments: ["export","entities"], paramNames: [], handlers: { GET: export__entities.GET } },
  { segments: ["export","stats"], paramNames: [], handlers: { GET: export__stats.GET } },
  { segments: ["gdpr","anonymize"], paramNames: [], handlers: { POST: gdpr__anonymize.POST } },
  { segments: ["gdpr","consent"], paramNames: [], handlers: { GET: gdpr__consent.GET, PATCH: gdpr__consent.PATCH } },
  { segments: ["gdpr","delete"], paramNames: [], handlers: { POST: gdpr__delete.POST } },
  { segments: ["gdpr","export"], paramNames: [], handlers: { POST: gdpr___export.POST } },
  { segments: ["gdpr","inventory"], paramNames: [], handlers: { GET: gdpr__inventory.GET } },
  { segments: ["gdpr","requests"], paramNames: [], handlers: { GET: gdpr__requests.GET, POST: gdpr__requests.POST } },
  { segments: ["gdpr","stats"], paramNames: [], handlers: { GET: gdpr__stats.GET } },
  { segments: ["lineage","graph"], paramNames: [], handlers: { GET: lineage__graph.GET } },
  { segments: ["lineage","stats"], paramNames: [], handlers: { GET: lineage__stats.GET } },
  { segments: ["migration","templates"], paramNames: [], handlers: { GET: migration__templates.GET } },
  { segments: ["backup"], paramNames: [], handlers: { GET: backup.GET, POST: backup.POST } },
  { segments: ["export"], paramNames: [], handlers: { GET: _export.GET, POST: _export.POST } },
  { segments: ["lineage"], paramNames: [], handlers: { GET: lineage.GET, POST: lineage.POST } },
  { segments: ["migration"], paramNames: [], handlers: { GET: migration.GET, POST: migration.POST } },
  { segments: ["backup","[id]","restore"], paramNames: ["id"], handlers: { POST: backup___id__restore.POST } },
  { segments: ["export","[id]","download"], paramNames: ["id"], handlers: { GET: export___id__download.GET } },
  { segments: ["export","[id]","run"], paramNames: ["id"], handlers: { POST: export___id__run.POST } },
  { segments: ["gdpr","requests","[id]"], paramNames: ["id"], handlers: { GET: gdpr__requests___id.GET, POST: gdpr__requests___id.POST } },
  { segments: ["migration","[id]","execute"], paramNames: ["id"], handlers: { POST: migration___id__execute.POST } },
  { segments: ["backup","[id]"], paramNames: ["id"], handlers: { GET: backup___id.GET, DELETE: backup___id.DELETE } },
  { segments: ["export","[id]"], paramNames: ["id"], handlers: { GET: export___id.GET, DELETE: export___id.DELETE } },
  { segments: ["migration","[id]"], paramNames: ["id"], handlers: { GET: migration___id.GET, DELETE: migration___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
