/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/itsm/*
 * Consolidates 27 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as changes__stats from '@/lib/api-handlers/itsm/changes__stats';
import * as incidents__by_priority from '@/lib/api-handlers/itsm/incidents__by_priority';
import * as incidents__by_status from '@/lib/api-handlers/itsm/incidents__by_status';
import * as incidents__sla_breaches from '@/lib/api-handlers/itsm/incidents__sla_breaches';
import * as incidents__stats from '@/lib/api-handlers/itsm/incidents__stats';
import * as knowledge__popular from '@/lib/api-handlers/itsm/knowledge__popular';
import * as knowledge__search from '@/lib/api-handlers/itsm/knowledge__search';
import * as knowledge__stats from '@/lib/api-handlers/itsm/knowledge__stats';
import * as changes from '@/lib/api-handlers/itsm/changes';
import * as incidents from '@/lib/api-handlers/itsm/incidents';
import * as knowledge from '@/lib/api-handlers/itsm/knowledge';
import * as stats from '@/lib/api-handlers/itsm/stats';
import * as changes___id__approve from '@/lib/api-handlers/itsm/changes___id__approve';
import * as changes___id__complete from '@/lib/api-handlers/itsm/changes___id__complete';
import * as changes___id__implement from '@/lib/api-handlers/itsm/changes___id__implement';
import * as changes___id__reject from '@/lib/api-handlers/itsm/changes___id__reject';
import * as incidents___id__assign from '@/lib/api-handlers/itsm/incidents___id__assign';
import * as incidents___id__close from '@/lib/api-handlers/itsm/incidents___id__close';
import * as incidents___id__escalate from '@/lib/api-handlers/itsm/incidents___id__escalate';
import * as incidents___id__resolve from '@/lib/api-handlers/itsm/incidents___id__resolve';
import * as incidents___id__status from '@/lib/api-handlers/itsm/incidents___id__status';
import * as knowledge___id__archive from '@/lib/api-handlers/itsm/knowledge___id__archive';
import * as knowledge___id__publish from '@/lib/api-handlers/itsm/knowledge___id__publish';
import * as knowledge___id__vote from '@/lib/api-handlers/itsm/knowledge___id__vote';
import * as changes___id from '@/lib/api-handlers/itsm/changes___id';
import * as incidents___id from '@/lib/api-handlers/itsm/incidents___id';
import * as knowledge___id from '@/lib/api-handlers/itsm/knowledge___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["changes","stats"], paramNames: [], handlers: { GET: changes__stats.GET } },
  { segments: ["incidents","by-priority"], paramNames: [], handlers: { GET: incidents__by_priority.GET } },
  { segments: ["incidents","by-status"], paramNames: [], handlers: { GET: incidents__by_status.GET } },
  { segments: ["incidents","sla-breaches"], paramNames: [], handlers: { GET: incidents__sla_breaches.GET } },
  { segments: ["incidents","stats"], paramNames: [], handlers: { GET: incidents__stats.GET } },
  { segments: ["knowledge","popular"], paramNames: [], handlers: { GET: knowledge__popular.GET } },
  { segments: ["knowledge","search"], paramNames: [], handlers: { GET: knowledge__search.GET } },
  { segments: ["knowledge","stats"], paramNames: [], handlers: { GET: knowledge__stats.GET } },
  { segments: ["changes"], paramNames: [], handlers: { GET: changes.GET, POST: changes.POST } },
  { segments: ["incidents"], paramNames: [], handlers: { GET: incidents.GET, POST: incidents.POST } },
  { segments: ["knowledge"], paramNames: [], handlers: { GET: knowledge.GET, POST: knowledge.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["changes","[id]","approve"], paramNames: ["id"], handlers: { POST: changes___id__approve.POST } },
  { segments: ["changes","[id]","complete"], paramNames: ["id"], handlers: { POST: changes___id__complete.POST } },
  { segments: ["changes","[id]","implement"], paramNames: ["id"], handlers: { POST: changes___id__implement.POST } },
  { segments: ["changes","[id]","reject"], paramNames: ["id"], handlers: { POST: changes___id__reject.POST } },
  { segments: ["incidents","[id]","assign"], paramNames: ["id"], handlers: { POST: incidents___id__assign.POST } },
  { segments: ["incidents","[id]","close"], paramNames: ["id"], handlers: { POST: incidents___id__close.POST } },
  { segments: ["incidents","[id]","escalate"], paramNames: ["id"], handlers: { POST: incidents___id__escalate.POST } },
  { segments: ["incidents","[id]","resolve"], paramNames: ["id"], handlers: { POST: incidents___id__resolve.POST } },
  { segments: ["incidents","[id]","status"], paramNames: ["id"], handlers: { POST: incidents___id__status.POST } },
  { segments: ["knowledge","[id]","archive"], paramNames: ["id"], handlers: { POST: knowledge___id__archive.POST } },
  { segments: ["knowledge","[id]","publish"], paramNames: ["id"], handlers: { POST: knowledge___id__publish.POST } },
  { segments: ["knowledge","[id]","vote"], paramNames: ["id"], handlers: { POST: knowledge___id__vote.POST } },
  { segments: ["changes","[id]"], paramNames: ["id"], handlers: { GET: changes___id.GET, PATCH: changes___id.PATCH, DELETE: changes___id.DELETE } },
  { segments: ["incidents","[id]"], paramNames: ["id"], handlers: { GET: incidents___id.GET, PATCH: incidents___id.PATCH, DELETE: incidents___id.DELETE } },
  { segments: ["knowledge","[id]"], paramNames: ["id"], handlers: { GET: knowledge___id.GET, PATCH: knowledge___id.PATCH, DELETE: knowledge___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
