/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/ad-reference/*
 * Consolidates 8 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as character from '@/lib/api-handlers/ad-reference/character';
import * as edit from '@/lib/api-handlers/ad-reference/edit';
import * as gen_script from '@/lib/api-handlers/ad-reference/gen_script';
import * as lipsync from '@/lib/api-handlers/ad-reference/lipsync';
import * as motion from '@/lib/api-handlers/ad-reference/motion';
import * as save from '@/lib/api-handlers/ad-reference/save';
import * as upload from '@/lib/api-handlers/ad-reference/upload';
import * as voice from '@/lib/api-handlers/ad-reference/voice';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routeTable: RouteEntry[] = [
  { segments: ["character"], paramNames: [], handlers: { POST: character.POST } },
  { segments: ["edit"], paramNames: [], handlers: { POST: edit.POST } },
  { segments: ["gen-script"], paramNames: [], handlers: { POST: gen_script.POST } },
  { segments: ["lipsync"], paramNames: [], handlers: { POST: lipsync.POST } },
  { segments: ["motion"], paramNames: [], handlers: { POST: motion.POST } },
  { segments: ["save"], paramNames: [], handlers: { POST: save.POST } },
  { segments: ["upload"], paramNames: [], handlers: {  } },
  { segments: ["voice"], paramNames: [], handlers: { POST: voice.POST } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routeTable) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatchRequest(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatchRequest(req, 'OPTIONS', ctx);
}
