name: Debug SSL
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/769665933727/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "github-actions-deploy@vertexaiopencode.iam.gserviceaccount.com"
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
      - name: 'Check SSL'
        run: gcloud compute ssl-certificates describe lazynext-cert-dev-v3 --global
