/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/email/*
 * Consolidates 32 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as campaigns__overview from '@/lib/api-handlers/email/campaigns__overview';
import * as drip_sequences__process from '@/lib/api-handlers/email/drip_sequences__process';
import * as subscribers__export from '@/lib/api-handlers/email/subscribers__export';
import * as subscribers__import from '@/lib/api-handlers/email/subscribers__import';
import * as templates__categories from '@/lib/api-handlers/email/templates__categories';
import * as ab_tests from '@/lib/api-handlers/email/ab_tests';
import * as campaigns from '@/lib/api-handlers/email/campaigns';
import * as drip_sequences from '@/lib/api-handlers/email/drip_sequences';
import * as lists from '@/lib/api-handlers/email/lists';
import * as segments from '@/lib/api-handlers/email/segments';
import * as subscribers from '@/lib/api-handlers/email/subscribers';
import * as templates from '@/lib/api-handlers/email/templates';
import * as ab_tests___id__results from '@/lib/api-handlers/email/ab_tests___id__results';
import * as ab_tests___id__winner from '@/lib/api-handlers/email/ab_tests___id__winner';
import * as campaigns___id__cancel_schedule from '@/lib/api-handlers/email/campaigns___id__cancel_schedule';
import * as campaigns___id__duplicate from '@/lib/api-handlers/email/campaigns___id__duplicate';
import * as campaigns___id__schedule from '@/lib/api-handlers/email/campaigns___id__schedule';
import * as campaigns___id__send from '@/lib/api-handlers/email/campaigns___id__send';
import * as campaigns___id__stats from '@/lib/api-handlers/email/campaigns___id__stats';
import * as drip_sequences___id__enroll from '@/lib/api-handlers/email/drip_sequences___id__enroll';
import * as drip_sequences___id__stats from '@/lib/api-handlers/email/drip_sequences___id__stats';
import * as drip_sequences___id__unenroll from '@/lib/api-handlers/email/drip_sequences___id__unenroll';
import * as lists___id__stats from '@/lib/api-handlers/email/lists___id__stats';
import * as lists___id__subscribers from '@/lib/api-handlers/email/lists___id__subscribers';
import * as segments___id__evaluate from '@/lib/api-handlers/email/segments___id__evaluate';
import * as templates___id__render from '@/lib/api-handlers/email/templates___id__render';
import * as ab_tests___id from '@/lib/api-handlers/email/ab_tests___id';
import * as campaigns___id from '@/lib/api-handlers/email/campaigns___id';
import * as drip_sequences___id from '@/lib/api-handlers/email/drip_sequences___id';
import * as lists___id from '@/lib/api-handlers/email/lists___id';
import * as subscribers___id from '@/lib/api-handlers/email/subscribers___id';
import * as templates___id from '@/lib/api-handlers/email/templates___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["campaigns","overview"], paramNames: [], handlers: { GET: campaigns__overview.GET } },
  { segments: ["drip-sequences","process"], paramNames: [], handlers: { POST: drip_sequences__process.POST } },
  { segments: ["subscribers","export"], paramNames: [], handlers: { GET: subscribers__export.GET } },
  { segments: ["subscribers","import"], paramNames: [], handlers: { POST: subscribers__import.POST } },
  { segments: ["templates","categories"], paramNames: [], handlers: { GET: templates__categories.GET } },
  { segments: ["ab-tests"], paramNames: [], handlers: { GET: ab_tests.GET, POST: ab_tests.POST } },
  { segments: ["campaigns"], paramNames: [], handlers: { GET: campaigns.GET, POST: campaigns.POST } },
  { segments: ["drip-sequences"], paramNames: [], handlers: { GET: drip_sequences.GET, POST: drip_sequences.POST } },
  { segments: ["lists"], paramNames: [], handlers: { GET: lists.GET, POST: lists.POST } },
  { segments: ["segments"], paramNames: [], handlers: { GET: segments.GET, POST: segments.POST } },
  { segments: ["subscribers"], paramNames: [], handlers: { GET: subscribers.GET, POST: subscribers.POST } },
  { segments: ["templates"], paramNames: [], handlers: { GET: templates.GET, POST: templates.POST } },
  { segments: ["ab-tests","[id]","results"], paramNames: ["id"], handlers: { GET: ab_tests___id__results.GET } },
  { segments: ["ab-tests","[id]","winner"], paramNames: ["id"], handlers: { POST: ab_tests___id__winner.POST } },
  { segments: ["campaigns","[id]","cancel-schedule"], paramNames: ["id"], handlers: { POST: campaigns___id__cancel_schedule.POST } },
  { segments: ["campaigns","[id]","duplicate"], paramNames: ["id"], handlers: { POST: campaigns___id__duplicate.POST } },
  { segments: ["campaigns","[id]","schedule"], paramNames: ["id"], handlers: { POST: campaigns___id__schedule.POST } },
  { segments: ["campaigns","[id]","send"], paramNames: ["id"], handlers: { POST: campaigns___id__send.POST } },
  { segments: ["campaigns","[id]","stats"], paramNames: ["id"], handlers: { GET: campaigns___id__stats.GET } },
  { segments: ["drip-sequences","[id]","enroll"], paramNames: ["id"], handlers: { POST: drip_sequences___id__enroll.POST } },
  { segments: ["drip-sequences","[id]","stats"], paramNames: ["id"], handlers: { GET: drip_sequences___id__stats.GET } },
  { segments: ["drip-sequences","[id]","unenroll"], paramNames: ["id"], handlers: { POST: drip_sequences___id__unenroll.POST } },
  { segments: ["lists","[id]","stats"], paramNames: ["id"], handlers: { GET: lists___id__stats.GET } },
  { segments: ["lists","[id]","subscribers"], paramNames: ["id"], handlers: { POST: lists___id__subscribers.POST, DELETE: lists___id__subscribers.DELETE } },
  { segments: ["segments","[id]","evaluate"], paramNames: ["id"], handlers: { POST: segments___id__evaluate.POST } },
  { segments: ["templates","[id]","render"], paramNames: ["id"], handlers: { POST: templates___id__render.POST } },
  { segments: ["ab-tests","[id]"], paramNames: ["id"], handlers: { GET: ab_tests___id.GET, DELETE: ab_tests___id.DELETE } },
  { segments: ["campaigns","[id]"], paramNames: ["id"], handlers: { GET: campaigns___id.GET, PATCH: campaigns___id.PATCH, DELETE: campaigns___id.DELETE } },
  { segments: ["drip-sequences","[id]"], paramNames: ["id"], handlers: { GET: drip_sequences___id.GET, PATCH: drip_sequences___id.PATCH, DELETE: drip_sequences___id.DELETE } },
  { segments: ["lists","[id]"], paramNames: ["id"], handlers: { GET: lists___id.GET, PATCH: lists___id.PATCH, DELETE: lists___id.DELETE } },
  { segments: ["subscribers","[id]"], paramNames: ["id"], handlers: { GET: subscribers___id.GET, PATCH: subscribers___id.PATCH, DELETE: subscribers___id.DELETE } },
  { segments: ["templates","[id]"], paramNames: ["id"], handlers: { GET: templates___id.GET, PATCH: templates___id.PATCH, DELETE: templates___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
