/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/asset-tracking/*
 * Consolidates 16 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as assets from '@/lib/api-handlers/asset-tracking/assets';
import * as assignments from '@/lib/api-handlers/asset-tracking/assignments';
import * as audits from '@/lib/api-handlers/asset-tracking/audits';
import * as depreciation from '@/lib/api-handlers/asset-tracking/depreciation';
import * as metrics from '@/lib/api-handlers/asset-tracking/metrics';
import * as stats from '@/lib/api-handlers/asset-tracking/stats';
import * as assignments___id__return from '@/lib/api-handlers/asset-tracking/assignments___id__return';
import * as assignments___id__transfer from '@/lib/api-handlers/asset-tracking/assignments___id__transfer';
import * as audits___id__complete from '@/lib/api-handlers/asset-tracking/audits___id__complete';
import * as audits___id__start from '@/lib/api-handlers/asset-tracking/audits___id__start';
import * as depreciation___id__complete from '@/lib/api-handlers/asset-tracking/depreciation___id__complete';
import * as depreciation___id__suspend from '@/lib/api-handlers/asset-tracking/depreciation___id__suspend';
import * as assets___id from '@/lib/api-handlers/asset-tracking/assets___id';
import * as assignments___id from '@/lib/api-handlers/asset-tracking/assignments___id';
import * as audits___id from '@/lib/api-handlers/asset-tracking/audits___id';
import * as depreciation___id from '@/lib/api-handlers/asset-tracking/depreciation___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["assets"], paramNames: [], handlers: { GET: assets.GET, POST: assets.POST } },
  { segments: ["assignments"], paramNames: [], handlers: { GET: assignments.GET, POST: assignments.POST } },
  { segments: ["audits"], paramNames: [], handlers: { GET: audits.GET, POST: audits.POST } },
  { segments: ["depreciation"], paramNames: [], handlers: { GET: depreciation.GET, POST: depreciation.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["assignments","[id]","return"], paramNames: ["id"], handlers: { POST: assignments___id__return.POST } },
  { segments: ["assignments","[id]","transfer"], paramNames: ["id"], handlers: { POST: assignments___id__transfer.POST } },
  { segments: ["audits","[id]","complete"], paramNames: ["id"], handlers: { POST: audits___id__complete.POST } },
  { segments: ["audits","[id]","start"], paramNames: ["id"], handlers: { POST: audits___id__start.POST } },
  { segments: ["depreciation","[id]","complete"], paramNames: ["id"], handlers: { POST: depreciation___id__complete.POST } },
  { segments: ["depreciation","[id]","suspend"], paramNames: ["id"], handlers: { POST: depreciation___id__suspend.POST } },
  { segments: ["assets","[id]"], paramNames: ["id"], handlers: { GET: assets___id.GET, PATCH: assets___id.PATCH, DELETE: assets___id.DELETE } },
  { segments: ["assignments","[id]"], paramNames: ["id"], handlers: { GET: assignments___id.GET, PATCH: assignments___id.PATCH, DELETE: assignments___id.DELETE } },
  { segments: ["audits","[id]"], paramNames: ["id"], handlers: { GET: audits___id.GET, PATCH: audits___id.PATCH, DELETE: audits___id.DELETE } },
  { segments: ["depreciation","[id]"], paramNames: ["id"], handlers: { GET: depreciation___id.GET, PATCH: depreciation___id.PATCH, DELETE: depreciation___id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
