/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/business-continuity/*
 * Consolidates 30 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as bias from '@/lib/api-handlers/business-continuity/bias';
import * as metrics from '@/lib/api-handlers/business-continuity/metrics';
import * as plans from '@/lib/api-handlers/business-continuity/plans';
import * as stats from '@/lib/api-handlers/business-continuity/stats';
import * as strategies from '@/lib/api-handlers/business-continuity/strategies';
import * as tests from '@/lib/api-handlers/business-continuity/tests';
import * as index from '@/lib/api-handlers/business-continuity/index';
import * as bias___id__archive from '@/lib/api-handlers/business-continuity/bias___id__archive';
import * as bias___id__complete from '@/lib/api-handlers/business-continuity/bias___id__complete';
import * as bias___id__review from '@/lib/api-handlers/business-continuity/bias___id__review';
import * as bias___id__start from '@/lib/api-handlers/business-continuity/bias___id__start';
import * as plans___id__activate from '@/lib/api-handlers/business-continuity/plans___id__activate';
import * as plans___id__approve from '@/lib/api-handlers/business-continuity/plans___id__approve';
import * as plans___id__archive from '@/lib/api-handlers/business-continuity/plans___id__archive';
import * as plans___id__deprecate from '@/lib/api-handlers/business-continuity/plans___id__deprecate';
import * as plans___id__test from '@/lib/api-handlers/business-continuity/plans___id__test';
import * as strategies___id__approve from '@/lib/api-handlers/business-continuity/strategies___id__approve';
import * as strategies___id__deprecate from '@/lib/api-handlers/business-continuity/strategies___id__deprecate';
import * as strategies___id__implement from '@/lib/api-handlers/business-continuity/strategies___id__implement';
import * as strategies___id__test from '@/lib/api-handlers/business-continuity/strategies___id__test';
import * as tests___id__cancel from '@/lib/api-handlers/business-continuity/tests___id__cancel';
import * as tests___id__complete from '@/lib/api-handlers/business-continuity/tests___id__complete';
import * as tests___id__fail from '@/lib/api-handlers/business-continuity/tests___id__fail';
import * as tests___id__schedule from '@/lib/api-handlers/business-continuity/tests___id__schedule';
import * as tests___id__start from '@/lib/api-handlers/business-continuity/tests___id__start';
import * as bias___id from '@/lib/api-handlers/business-continuity/bias___id';
import * as plans___id from '@/lib/api-handlers/business-continuity/plans___id';
import * as strategies___id from '@/lib/api-handlers/business-continuity/strategies___id';
import * as tests___id from '@/lib/api-handlers/business-continuity/tests___id';
import * as _id from '@/lib/api-handlers/business-continuity/_id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, any>;
}

const routes: RouteEntry[] = [
  { segments: ["bias"], paramNames: [], handlers: { GET: bias.GET, POST: bias.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["plans"], paramNames: [], handlers: { GET: plans.GET, POST: plans.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["strategies"], paramNames: [], handlers: { GET: strategies.GET, POST: strategies.POST } },
  { segments: ["tests"], paramNames: [], handlers: { GET: tests.GET, POST: tests.POST } },
  { segments: [], paramNames: [], handlers: { GET: index.GET, POST: index.POST } },
  { segments: ["bias","[id]","archive"], paramNames: ["id"], handlers: { POST: bias___id__archive.POST } },
  { segments: ["bias","[id]","complete"], paramNames: ["id"], handlers: { POST: bias___id__complete.POST } },
  { segments: ["bias","[id]","review"], paramNames: ["id"], handlers: { POST: bias___id__review.POST } },
  { segments: ["bias","[id]","start"], paramNames: ["id"], handlers: { POST: bias___id__start.POST } },
  { segments: ["plans","[id]","activate"], paramNames: ["id"], handlers: { POST: plans___id__activate.POST } },
  { segments: ["plans","[id]","approve"], paramNames: ["id"], handlers: { POST: plans___id__approve.POST } },
  { segments: ["plans","[id]","archive"], paramNames: ["id"], handlers: { POST: plans___id__archive.POST } },
  { segments: ["plans","[id]","deprecate"], paramNames: ["id"], handlers: { POST: plans___id__deprecate.POST } },
  { segments: ["plans","[id]","test"], paramNames: ["id"], handlers: { POST: plans___id__test.POST } },
  { segments: ["strategies","[id]","approve"], paramNames: ["id"], handlers: { POST: strategies___id__approve.POST } },
  { segments: ["strategies","[id]","deprecate"], paramNames: ["id"], handlers: { POST: strategies___id__deprecate.POST } },
  { segments: ["strategies","[id]","implement"], paramNames: ["id"], handlers: { POST: strategies___id__implement.POST } },
  { segments: ["strategies","[id]","test"], paramNames: ["id"], handlers: { POST: strategies___id__test.POST } },
  { segments: ["tests","[id]","cancel"], paramNames: ["id"], handlers: { POST: tests___id__cancel.POST } },
  { segments: ["tests","[id]","complete"], paramNames: ["id"], handlers: { POST: tests___id__complete.POST } },
  { segments: ["tests","[id]","fail"], paramNames: ["id"], handlers: { POST: tests___id__fail.POST } },
  { segments: ["tests","[id]","schedule"], paramNames: ["id"], handlers: { POST: tests___id__schedule.POST } },
  { segments: ["tests","[id]","start"], paramNames: ["id"], handlers: { POST: tests___id__start.POST } },
  { segments: ["bias","[id]"], paramNames: ["id"], handlers: { GET: bias___id.GET, PATCH: bias___id.PATCH, DELETE: bias___id.DELETE } },
  { segments: ["plans","[id]"], paramNames: ["id"], handlers: { GET: plans___id.GET, PATCH: plans___id.PATCH, DELETE: plans___id.DELETE } },
  { segments: ["strategies","[id]"], paramNames: ["id"], handlers: { GET: strategies___id.GET, PATCH: strategies___id.PATCH, DELETE: strategies___id.DELETE } },
  { segments: ["tests","[id]"], paramNames: ["id"], handlers: { GET: tests___id.GET, PATCH: tests___id.PATCH, DELETE: tests___id.DELETE } },
  { segments: ["[id]"], paramNames: ["id"], handlers: { GET: _id.GET, PATCH: _id.PATCH, DELETE: _id.DELETE } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
