/**
 * AUTO-GENERATED by scripts/consolidate-all-routes.mjs
 * Catch-all route handler for /api/customer-success/*
 * Consolidates 19 routes into a single entry point.
 */
import { NextRequest, NextResponse } from 'next/server';
import * as churn_risks from '@/lib/api-handlers/customer-success/churn_risks';
import * as expansions from '@/lib/api-handlers/customer-success/expansions';
import * as health_scores from '@/lib/api-handlers/customer-success/health_scores';
import * as metrics from '@/lib/api-handlers/customer-success/metrics';
import * as renewals from '@/lib/api-handlers/customer-success/renewals';
import * as stats from '@/lib/api-handlers/customer-success/stats';
import * as success_plans from '@/lib/api-handlers/customer-success/success_plans';
import * as touchpoints from '@/lib/api-handlers/customer-success/touchpoints';
import * as churn_risks___id__mitigate from '@/lib/api-handlers/customer-success/churn_risks___id__mitigate';
import * as churn_risks___id__resolve from '@/lib/api-handlers/customer-success/churn_risks___id__resolve';
import * as expansions___id__close from '@/lib/api-handlers/customer-success/expansions___id__close';
import * as health_scores__customer___customerId from '@/lib/api-handlers/customer-success/health_scores__customer___customerId';
import * as renewals___id__close from '@/lib/api-handlers/customer-success/renewals___id__close';
import * as churn_risks___id from '@/lib/api-handlers/customer-success/churn_risks___id';
import * as expansions___id from '@/lib/api-handlers/customer-success/expansions___id';
import * as health_scores___id from '@/lib/api-handlers/customer-success/health_scores___id';
import * as renewals___id from '@/lib/api-handlers/customer-success/renewals___id';
import * as success_plans___id from '@/lib/api-handlers/customer-success/success_plans___id';
import * as touchpoints___id from '@/lib/api-handlers/customer-success/touchpoints___id';

interface RouteEntry {
  segments: string[];
  paramNames: string[];
  handlers: Record<string, (req: NextRequest, ctx?: { params: Record<string, string> }) => any>;
}

const routes: RouteEntry[] = [
  { segments: ["churn-risks"], paramNames: [], handlers: { GET: churn_risks.GET, POST: churn_risks.POST } },
  { segments: ["expansions"], paramNames: [], handlers: { GET: expansions.GET, POST: expansions.POST } },
  { segments: ["health-scores"], paramNames: [], handlers: { GET: health_scores.GET, POST: health_scores.POST } },
  { segments: ["metrics"], paramNames: [], handlers: { GET: metrics.GET } },
  { segments: ["renewals"], paramNames: [], handlers: { GET: renewals.GET, POST: renewals.POST } },
  { segments: ["stats"], paramNames: [], handlers: { GET: stats.GET } },
  { segments: ["success-plans"], paramNames: [], handlers: { GET: success_plans.GET, POST: success_plans.POST } },
  { segments: ["touchpoints"], paramNames: [], handlers: { GET: touchpoints.GET, POST: touchpoints.POST } },
  { segments: ["churn-risks","[id]","mitigate"], paramNames: ["id"], handlers: { POST: churn_risks___id__mitigate.POST } },
  { segments: ["churn-risks","[id]","resolve"], paramNames: ["id"], handlers: { POST: churn_risks___id__resolve.POST } },
  { segments: ["expansions","[id]","close"], paramNames: ["id"], handlers: { POST: expansions___id__close.POST } },
  { segments: ["health-scores","customer","[customerId]"], paramNames: ["customerId"], handlers: { GET: health_scores__customer___customerId.GET } },
  { segments: ["renewals","[id]","close"], paramNames: ["id"], handlers: { POST: renewals___id__close.POST } },
  { segments: ["churn-risks","[id]"], paramNames: ["id"], handlers: { GET: churn_risks___id.GET, PATCH: churn_risks___id.PATCH } },
  { segments: ["expansions","[id]"], paramNames: ["id"], handlers: { GET: expansions___id.GET, PATCH: expansions___id.PATCH } },
  { segments: ["health-scores","[id]"], paramNames: ["id"], handlers: { GET: health_scores___id.GET, PATCH: health_scores___id.PATCH, DELETE: health_scores___id.DELETE } },
  { segments: ["renewals","[id]"], paramNames: ["id"], handlers: { GET: renewals___id.GET, PATCH: renewals___id.PATCH } },
  { segments: ["success-plans","[id]"], paramNames: ["id"], handlers: { GET: success_plans___id.GET, PATCH: success_plans___id.PATCH, DELETE: success_plans___id.DELETE } },
  { segments: ["touchpoints","[id]"], paramNames: ["id"], handlers: { GET: touchpoints___id.GET, PATCH: touchpoints___id.PATCH } },
];

function matchRoute(pathSegments: string[]): { route: RouteEntry; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.segments.length !== pathSegments.length) continue;
    const params: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < route.segments.length; i++) {
      const pattern = route.segments[i];
      const actual = pathSegments[i];
      if (pattern.startsWith('[') && pattern.endsWith(']')) {
        // Dynamic segment - extract param
        const paramName = pattern.slice(1, -1).replace(/\./g, '_');
        params[paramName] = actual;
      } else if (pattern !== actual) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, params };
  }
  return null;
}

function extractParams(pattern: string, actual: string): string {
  return actual;
}

async function dispatch(
  req: NextRequest,
  method: string,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { path } = await params;
  const match = matchRoute(path);
  if (!match) {
    return NextResponse.json({ error: 'not_found' }, { status: 404 });
  }
  const handler = match.route.handlers[method];
  if (!handler) {
    return NextResponse.json({ error: 'method_not_allowed' }, { status: 405 });
  }
  const ctx = match.route.paramNames.length > 0 ? { params: match.params } : undefined;
  return handler(req, ctx);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'GET', ctx);
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'POST', ctx);
}

export async function PUT(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PUT', ctx);
}

export async function PATCH(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'PATCH', ctx);
}

export async function DELETE(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'DELETE', ctx);
}

export async function HEAD(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'HEAD', ctx);
}

export async function OPTIONS(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  return dispatch(req, 'OPTIONS', ctx);
}
